### ISSUE TITLE
Custom Tensorflow Model - Object detction using Webcam in a website

### ISSUE THREAD

**Issue by Fawcett-cpu** [tensorflow/tfjs#4848] opened 2021-03-21 13:00 UTC
Im attempting to create a web application that uses a custom model I have created and converted to tenorflow JS to be used with a webcam for object detection. My current code uses a COCO-SSD model but I want it to use the model I have trained myself. the model is (https://github.com/Fawcett-cpu/GraphScanning/tree/main/Graph)

and this is what the code looks like HTML
`  <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8" />
        <title>Lets Scan</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="CSS/LetsScan.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
        <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    </head>

    <body>
        
        <nav class="navbar">
            <a href="index.html"> Home</a>
            <a href="LetsScan.html">Lets Scan</a>
            <a href="AboutUs.html">About Us</a>
            <a href="ContactUs.html">Contact Us</a>
        </nav>
        <h1 class="pageHeader">Lets Scan</h1>
        <div class="container">
            <article class="howTo">
                <h3 class="howToHeader">What To Do!</h3>
                <p>To start, hold up a graph to your camera. Ensuring that the graph is clear and completely in view</p>
            </article>
            <section id="demos" class="invisible">
                <div id="liveView" class="camView">
                    <button id="webcamButton">Enable Webcam</button>
                    <video id="webcam" autoplay width="640" height="480"></video>
                </div>
            </section>
        </div>
...`

The JS File 
`const demosSection = document.getElementById('demos');

var model = undefined;

// Before we can use COCO-SSD class we must wait for it to finish
// loading. Machine Learning models can be large and take a moment to
// get everything needed to run.
cocoSsd.load().then(function (loadedModel) {
    model = loadedModel;
    // Show demo section now model is ready to use.
    demosSection.classList.remove('invisible');
});

/********************************************************************
// Demo 2: Continuously grab image from webcam stream and classify it.
// Note: You must access the demo on https for this to work:
// https://tensorflow-js-image-classification.glitch.me/
********************************************************************/

const video = document.getElementById('webcam');
const liveView = document.getElementById('liveView');

// Check if webcam access is supported.
function hasGetUserMedia() {
    return !!(navigator.mediaDevices &&
        navigator.mediaDevices.getUserMedia);
}

// Keep a reference of all the child elements we create
// so we can remove them easilly on each render.
var children = [];

// If webcam supported, add event listener to button for when user
// wants to activate it.
if (hasGetUserMedia()) {
    const enableWebcamButton = document.getElementById('webcamButton');
    enableWebcamButton.addEventListener('click', enableCam);
} else {
    console.warn('getUserMedia() is not supported by your browser');
}

// Enable the live webcam view and start classification.
function enableCam(event) {
    if (!model) {
        console.log('Wait! Model not loaded yet.')
        return;
    }

    // Hide the button.
    event.target.classList.add('removed');

    // getUsermedia parameters.
    const constraints = {
        video: true
    };

    // Activate the webcam stream.
    navigator.mediaDevices.getUserMedia(constraints).then(function (stream) {
        video.srcObject = stream;
        video.addEventListener('loadeddata', predictWebcam);
    });
}

function predictWebcam() {
    // Now let's start classifying the stream.
    model.detect(video).then(function (predictions) {
        // Remove any highlighting we did previous frame.
        for (let i = 0; i < children.length; i++) {
            liveView.removeChild(children[i]);
        }
        children.splice(0);

        // Now lets loop through predictions and draw them to the live view if
        // they have a high confidence score.
        for (let n = 0; n < predictions.length; n++) {
            // If we are over 66% sure we are sure we classified it right, draw it!
            if (predictions[n].score > 0.66) {
                const p = document.createElement('p');
                p.innerText = predictions[n].class + ' - with '
                    + Math.round(parseFloat(predictions[n].score) * 100)
                    + '% confidence.';
                // Draw in top left of bounding box outline.
                p.style = 'left: ' + predictions[n].bbox[0] + 'px;' +
                    'top: ' + predictions[n].bbox[1] + 'px;' +
                    'width: ' + (predictions[n].bbox[2] - 10) + 'px;';

                // Draw the actual bounding box.
                const highlighter = document.createElement('div');
                highlighter.setAttribute('class', 'highlighter');
                highlighter.style = 'left: ' + predictions[n].bbox[0] + 'px; top: '
                    + predictions[n].bbox[1] + 'px; width: '
                    + predictions[n].bbox[2] + 'px; height: '
                    + predictions[n].bbox[3] + 'px;';

                liveView.appendChild(highlighter);
                liveView.appendChild(p);

                // Store drawn objects in memory so we can delete them next time around.
                children.push(highlighter);
                children.push(p);
            }
        }

        // Call this function again to keep predicting when the browser is ready.
        window.requestAnimationFrame(predictWebcam);
    });
}`

and there also a css file.

so far in the code I have tried to change the cocoSsd.load In my js file to

`async function load_model() {
    // It's possible to load the model locally or from a repo
    // You can choose whatever IP and PORT you want in the "http://127.0.0.1:8080/model.json" just set it before in your https server
    //const model = await loadGraphModel("http://127.0.0.1:8080/model.json");
    const model = await loadGraphModel("https://raw.githubusercontent.com/Fawcett-cpu/GraphScanning/tree/main/Graph/model.json");
    return model;
}`

which it does nothing I dont understand how I can use my custom model in my current site like I did with the COCO-SSD model

**Comment by rthadur** [comment] 2021-03-23 18:56
Here is the sample code to load the model from local , please check 

```
`let model;
$( document ).ready(async function () {
	$('.progress-bar').show();
    console.log( "Loading model..." );
    model = await tf.loadGraphModel('model/model.json');
    console.log( "Model loaded." );
	$('.progress-bar').hide();
});

$("#predict-button").click(async function ()`
```

**Comment by Fawcett-cpu** [comment] 2021-03-24 09:12
Ive been able to load my model, however the model is not working to make predictions or detections

**Comment by jinjingforever** [comment] 2021-03-31 20:51
Looks like certain tensor was incorrectly disposed somewhere in the graph.. I haven't fully investigated the root cause yet. Will take a closer look when I have more time. Thanks!

**Comment by jinjingforever** [comment] 2021-04-01 17:48
My colleague pushed a fix https://github.com/tensorflow/tfjs/pull/4894 which should fix this issue. I tried it and your model seems to run without throwing errors (but it took several minutes to finish). Please give it a try! Thanks!

**Closed by jinjingforever** 2021-04-01 17:48 UTC
Labels: stalled, stat:awaiting response, type:others
