### ISSUE TITLE
LSTM layer is slow and freezes browser

### ISSUE THREAD

**Issue by EliotAndres** [tensorflow/tfjs#270] opened 2018-05-07 16:02 UTC
#### Describe the problem or feature request
**Problem**: LSTM model loading is slow and freezes browser

Based on the sentiment example, I tried to build a startup name generator: [demo](http://ndres.me/char-rnn-tensorflow-js/) & [code](https://github.com/EliotAndres/char-rnn-tensorflow-js)

But it freezes the browser for ~30 seconds when loading the model. On Chrome, only one tab freezes. On Firefox, one tab freezes and other tabs can't load new pages.

(Freezing = can't click anywhere, can't open console, etc ...)

**Questions**:
- Is this an expected behavior ?
- There seem to be an issue with LSTM (see [here, "bug b/74429960"](https://github.com/tensorflow/tfjs-examples/blob/master/sentiment/python/imdb.py#L128)). Any more info on that ?
- Is it linked to [this issue](https://github.com/tensorflow/tfjs/issues/245) ?

#### Code to reproduce the bug / link to feature request
See above

**Comment by caisq** [comment] 2018-05-07 16:09
This issue is a duplicate of https://github.com/tensorflow/tfjs/issues/245. 
We are in the process of improving the speed of RNN by replacing the QR decomposition with Gram-Schmmidt orthogonalization. Please see that issue for progress and status.

**Closed by caisq** 2018-05-07 16:09 UTC
Labels: duplicate
