### ISSUE TITLE
Packing / unpacking shaders should input / output 3D tensors for readability and performance

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#893] opened 2018-11-08 19:59 UTC
This is in line with our general practice of reshaping inputs in order to simplify shaders and reduce GLSL arithmetic.

**Comment by xianrenb** [comment] 2019-09-18 13:43
The original 2x2 grid packing method makes all related code hard to read.
3D tensor should have [batch, row, col] indices.
I would suggest packing every 4 rows into one instead.
It should be easy to write glsl function mapping tensor indices to texture coordinates and channels, and vice versa.
For most tensor operations, every row should do the same job, so it should be easy to write packed tensor operations without losing performance.

**Comment by gaikwadrahul8** [comment] 2023-10-11 13:56
Hi, @annxingyuan

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:37
Hi, @annxingyuan 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:37 UTC
Labels: comp:core, type:performance, stat:awaiting response
