### ISSUE TITLE
The qna model demo on your Github page does not return any answer results

### ISSUE THREAD

**Issue by torressam333** [tensorflow/tfjs#5838] opened 2021-11-12 12:16 UTC
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 20.04
- Browser version: Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Describe the current behavior**
When trying to run the qna model demo for TensorFlow.js I found that the answers always return an empty array. I did not alter any code I simply ran the out-of-the-box demo direct from the qna Github page. I left the default information about Nikola Tesla in place and asked the question `Who is Nikola Tesla`. In the Chrome console, I saw an Array with 0 results returned.

**Describe the expected behavior**
I expect answers to be returned by the model and output to the browser or printed in the Chrome console.

**Standalone code to reproduce the issue**
The reproducible example exists at the qna demo link provided by Github.

https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html

Other info/logs 
None to post

Thank you.

**Comment by xblack0** [comment] 2021-11-24 09:03
I believe this library is broken and no update about it, I have the same issue.

**Comment by torressam333** [comment] 2021-11-24 12:09
@xblack0 maybe we can fork it and try to identify the issue? I'm not a tfjs pro by any means but with some time and effort we can find the bug. Thoughts?

**Comment by xblack0** [comment] 2021-11-24 14:10
> @xblack0 maybe we can fork it and try to identify the issue? I'm not a tfjs pro by any means but with some time and effort, we can find the bug. Thoughts?

to be honest, I am working on a big project have no time to trace out this bug :(, hope someone will help here.

**Comment by rthadur** [comment] 2021-12-02 00:01
yes the demo is broken , @mattsoulanille could you please help with this issue ?

**Comment by mattsoulanille** [comment] 2021-12-02 17:42
I think the demo is confused about the large parenthetical that provides pronunciation information, alternative spellings, and other info after the name "Nikola Tesla"

> Nikola Tesla (/ˈtɛslə/;[2] Serbo-Croatian: [nǐkola têsla]; Serbian Cyrillic: Никола Тесла;[a] 10
      July 1856 – 7 January 1943) was a Serbian-American[4][5][6] inventor, electrical engineer, mechanical engineer,
      and futurist who is best known for his contributions to the design of the modern alternating current (AC)
      electricity supply system.[7] <br>

This might be a limitation of the model (although I'm not familiar with it myself). I tried a few other queries and they worked:

"Where was Tesla born"
> Austrian Empire (score =17.900294303894043)

"When was Tesla born"
> 10 July 1856 (score =11.94551420211792)

"Where did Tesla work"
> Edison Machine Works (score =18.823317527770996)

"What did Tesla do after Wardenclyffe"
> experimented with a series of inventions (score =12.450957298278809)

Removing the parenthetical so that the first paragraph looks like this
>Nikola Tesla was a Serbian-American[4][5][6] inventor, electrical engineer, mechanical engineer,
      and futurist who is best known for his contributions to the design of the modern alternating current (AC)
      electricity supply system.[7] <br>

... makes the first query work:
"Who is Nikola Tesla"
>inventor (score =4.993876487016678)

**Comment by rthadur** [comment] 2021-12-23 18:25
Thank you Matt , will close this issue as this is working as intended.

**Closed by rthadur** 2021-12-23 18:25 UTC
Labels: type:bug, stat:awaiting response, stalled
