### ISSUE TITLE
Error training handwriting recognition model via HTML5 canvas

### ISSUE THREAD

**Issue by bibhuticoder** [tensorflow/tfjs#1685] opened 2019-06-23 01:26 UTC
#### Problem
I am trying to train a handwriting recognition CNN model using 1 training data. According to the model i have prepared training data and label. While running `model.fit` method it gives `Uncaught (in promise) TypeError: Cannot read property 'toString' of null` error.

#### Code to reproduce the bug
```javascript
    async function doTrain(digit){
      let tensor = tf.browser.fromPixels(canvasTrain)
        .resizeNearestNeighbor([28, 28])
        .mean(2)
        .expandDims(2)
        .expandDims()
        .toFloat().div(255.0);

      let labels = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
      labels[digit] = 1;
      let label = tf.tensor2d(labels, [1, 10]);
      await model.fit(tensor, label, {batchSize: 1, epochs: 1});
    }
```

Actually it's my first time using tensorflowjs. So am I missing something here ?

**Comment by caisq** [comment] 2019-06-24 13:47
This is a duplicate of https://github.com/tensorflow/tfjs/issues/1687 (Or that bug is a duplicate of this rather). The root cause is a bug in tf.layers.dropout() under training mode. The bug is present in the latest release. We are working to fix it.

**Closed** 2019-06-24 14:54 UTC
Labels: comp:core, type:bug
