### ISSUE TITLE
error when running "yarn watch" Uncaught (in promise) TypeError: Cannot read property 'drawImage' of null

### ISSUE THREAD

**Issue by thebeancounter** [tensorflow/tfjs#349] opened 2018-05-27 17:18 UTC
I am using the code as explained [here](https://js.tensorflow.org/tutorials/webcam-transfer-learning.html): 
and getting the following error on the init method 

> Uncaught (in promise) TypeError: Cannot read property 'drawImage' of null
>     at MathBackendWebGL.fromPixels (backend_webgl.js:134)
>     at Engine.fromPixels (engine.js:293)
>     at ArrayOps.fromPixels (array_ops.js:280)
>     at operation.js:9
>     at Tracking.tidy (tracking.js:34)
>     at Object.descriptor.value (operation.js:9)
>     at webcam.js:37
>     at Object.Tracking.tidy (tracking.js:34)
>     at Webcam.capture (webcam.js:35)
>     at index.js:163

When I am running the demo from the link in the tutorial it works fine. maybe a new version?

**Comment by timotheebernard** [comment] 2018-05-28 22:36
Hi,

I started investigating the issue and I can confirm I am able to reproduce the issue.
To be more specific, I tried different tfjs versions and the issue appeared when upgrading from tfjs 0.10.3 to 0.11.0.
This is the problematic line: https://github.com/tensorflow/tfjs-core/blob/fd49f546e8eb80faf662ef6bab66176b03041cd7/src/kernels/backend_webgl.ts#L138, since 0.11.0, `getContext('2d')` returns `null`.

@thebeancounter While waiting for a fix, what I temporary suggest: remove your node_modules folder, change tfjs version to 0.10.3 in your package.json, it will work. @ymkz you should try the same thing, I can't guarantee it will work, I did not try with the posenet example.

**Comment by hpssjellis** [comment] 2018-05-30 01:27
v10.3 works. I can't get v11.2 to work

**Comment by kucukkanat** [comment] 2018-05-31 09:44
@hpssjellis Downgrading to v0.10.3 worked for me as well thank you very much!

**Comment by leotm** [comment] 2018-05-31 10:47
Same, I stuck to v0.10.3 since its the version they use in the posenet working camera and coco demos.

**Comment by ymkz** [comment] 2018-06-01 17:42
@timotheebernard thank you for investigating. I tried to downgrade tfjs 0.10.3 and it was worked well, thanks!

**Comment by dsmilkov** [comment] 2018-06-02 17:53
I updated all the tfjs-examples to use `0.11.4` where that error should be fixed (it was fixed in tensorflow/tfjs-core#1064). Will close this issue, but feel free to reopen if you again run into the issue. Make sure to use `tfjs >= 0.11.4`

**Closed** 2018-06-02 17:54 UTC

**Comment by zakobyte** [comment] 2018-06-03 07:30
10.3 worked with rebuild but 11.4 needs extra dependencies

**Comment by dsmilkov** [comment] 2018-06-04 21:54
@zakobyte, can you elaborate on that a bit? I'm assuming you pulled from `master` and re-run `yarn` to install the extra dep. Did it not work after that?
