### ISSUE TITLE
Breaking Change v3.8.0 => v3.9.0

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#5584] opened 2021-09-05 05:19 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.9.0

**Describe the current behavior**

Upgraded from 3.8.0 to 3.9.0, and typescript throws an error:

> Error: node_modules/@tensorflow/tfjs-core/dist/hash_util.d.ts:2:49 - error TS2304: Cannot find name 'Long'.

![image](https://user-images.githubusercontent.com/5757359/132116104-1a06c0df-e90b-48d9-9cc2-db62244a6b10.png)

Using `typescript` 4.3.5.

Perhaps missing `import Long from 'long';` in 
![image](https://user-images.githubusercontent.com/5757359/132116245-cf1c1688-fbf8-48ab-91d8-84c0be4702c6.png)

**Describe the expected behavior**

No breaking change

**Comment by davayd** [comment] 2021-09-07 18:35
Same issue

**Comment by mattsoulanille** [comment] 2021-09-08 16:59
Looks like `hash_util.d.ts` somehow lost its reference types triple slash. Here it is at 3.8.0:

```
/// <reference types="long" />
export declare function hexToLong(hex: string): Long;
export declare function fingerPrint64(s: Uint8Array, len?: number): Long;
```

It [should have been automatically added by tsc](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-), and I'm not yet sure why `tsc` isn't including it in our Bazel compile.

**Comment by mattsoulanille** [comment] 2021-09-08 18:06
I've tried to reproduce this locally by compiling the following:
```
import {hexToLong} from '@tensorflow/tfjs-core/dist/hash_util';

console.log(hexToLong('0xABCDEF'));
```
tsc successfully compiled the above. Could you please send me a reproduction of this issue? Thanks!

**Comment by mattsoulanille** [comment] 2021-09-10 20:04
I am going to remove the release blocker tag from this issue since I have been unable to reproduce it. [Here's my attempt](https://github.com/mattsoulanille/tfjs-issue-5584-test).

**Comment by rthadur** [comment] 2021-09-23 13:57
I was not able to reproduce the same error, will be closing this request , please @mention to reopen. Thank you

**Comment by Playfrog4u** [comment] 2021-11-22 19:48
I am also having the same issue on a fresh Angular 12 install...
Version is 3.11.0

When I manually add 
`/// <reference types="long" />`
to  the `hash_util.d.ts` it works as expected.

Before
```
/// <amd-module name="@tensorflow/tfjs-core/dist/hash_util" />
export declare function hexToLong(hex: string): Long;
export declare function fingerPrint64(s: Uint8Array, len?: number): Long;
```
After
```
/// <amd-module name="@tensorflow/tfjs-core/dist/hash_util" />
/// <reference types="long" />
export declare function hexToLong(hex: string): Long;
export declare function fingerPrint64(s: Uint8Array, len?: number): Long;
```

**Comment by AmitMY** [comment] 2021-11-29 19:17
This is still an issue for me.

I have tried:
1. `npm I -D @types/long`
2. add `"types": ["long"]` to `compilerOptions`

But that did not help.

**Comment by AmitMY** [comment] 2021-12-10 15:32
v3.12.0

Added `@types/long` to my `compilerOptions.types` worked.

**Comment by chandan7piet** [comment] 2021-12-21 08:00
Step 1. npm I -D @types/long
Step 2.  go to tsconfig.app.json
Step 3.  add   "types": ["@types/long"]

----->tsconfig.app.json this file will looks like

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
   ###  _**"types": ["@types/long"]**_
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
-------> it worked for me, hope will work for you as well.

**Comment by huan** [comment] 2022-01-06 06:19
@mattsoulanille I can reproduce this problem with my repo, by following steps in this issue:

- https://github.com/huan/ng-plus-wechaty/issues/2

**Comment by shmishra99** [comment] 2023-05-04 11:23
Hi @AmitMY ,
Apology for the late response. Could you please let us know if your issue has been resolved or you are still looking for the solution? Some alternatives solution you could try to resolve your issue.
1. Install latest version of `npm i @tensorflow/tfjs-core@latest`
2. `@type/long` dependency is already present inside `node_modules/@tensorflow/tfjs-core/node_modules`.
3.   Set your` tfconfig.app.json` or `tfconfig.json` compilerOptions.
```
"compilerOptions": {
    "types": ["@tensorflow/tfjs-core"]
  }
```
Let me know if have I missed something here. Thank You !!

**Comment by yojeek** [comment] 2023-05-16 05:03
> 1. Install latest version of `npm i @tensorflow/tfjs-core@latest`
> 2. `@type/long` dependency is already present inside `node_modules/@tensorflow/tfjs-core/node_modules`.
> 3. Set your` tfconfig.app.json` or `tfconfig.json` compilerOptions.
> 
> ```
> "compilerOptions": {
>     "types": ["@tensorflow/tfjs-core"]
>   }
> ```
> 
> Let me know if have I missed something here. Thank You !!

Didn't worked for TypeScript 5.0.4, TFJS 4.5.0. The definition is there in `@tensorflow/tfjs-core/node_modules/@types` but compiler doesn't pick it up.

Only  "workaround" that helped me was set `compilerOptions.skipLibCheck` to `true`, as it, disappointingly, suggested in official tfjs documentation for TypeScript projects.

**Closed** 2023-05-23 05:42 UTC
Labels: type:bug, stat:awaiting response, stalled
