### ISSUE TITLE
Explore keeping quantized weights in memory as int8s.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1492] opened 2019-04-04 04:46 UTC
Currently when we quantize weights over the wire we immediately dequantized. Another idea is to keep the weights in memory as int8s and dequantize lazily when a shader program is executed (doing this at the shader compiler level means no change to shader code since the sampler can do the work of dequantizing).

This will give us a 4x memory reduction for weights and possibly better utilization of caching of weights sampling.

We should do an investigation around this.

Code pointer to where dequantization happens (this would happen in a sampler instead): https://github.com/tensorflow/tfjs-core/blob/master/src/io/io_utils.ts#L102

cc @annxingyuan in case you're interested, otherwise I might do this investigation when I get cycles

**Comment by nsthorat** [comment] 2019-04-04 05:04
Also, the weights don't have to come from a quantized source. We can compute min / max on the fly as an internal detail of the WebGL backend so we don't have to introduce a qint8 dtype (it can be an internal WebGL-specific implementation detail of how weights are stored).

**Comment by gaikwadrahul8** [comment] 2023-10-11 12:47
Hi, @nsthorat 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:28
Hi, @nsthorat

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:28 UTC
Labels: type:performance, stat:awaiting response, comp:backend-webgl
