### ISSUE TITLE
Memory Overallocation from tfjs version 0.12.4

### ISSUE THREAD

**Issue by MoonsuCha** [tensorflow/tfjs#672] opened 2018-09-04 12:36 UTC
#### TensorFlow.js version
0.12.4 ~ 0.12.6

#### Browser version
Chrome 68.0.3440.106 , Firefox 61.0.2

#### Describe the problem or feature request
From tensorflow.js 0.12.4, when running a model with large input, RAM memory is abnormally allocated to the extent that it can't handle the data. 

#### Code to reproduce the bug / link to feature request
With tfjs posenet demo official repository, the bug can be reproduced.

##### To see working situation in 0.12.3

1. clone the posenet demo repository, 
   [link](https://github.com/tensorflow/tfjs-models/tree/master/posenet)
2. version up the tfjs version to `0.12.3` by editing package.json
   (before editing the version is `0.11.4` in master branch)
3. start the demo server: `npm i && npm run watch`
4. change the input setting, and we can see the memory is in normal situation.
![image](https://user-images.githubusercontent.com/8610430/45030876-3a99d100-b088-11e8-8f68-4cb6e272b8fa.png)

##### To see memory bug situation in 0.12.4 ~ 0.12.6

1. clone the posenet demo repository, 
   [link](https://github.com/tensorflow/tfjs-models/tree/master/posenet)
2. version up the tfjs version to `0.12.4` by editing package.json
   (before editing the version is `0.11.4` in master branch)
3. start the demo server: `npm i && npm run watch`
4. With the same input setting, we can see the memory overallocation with the demo application failing to work
![image](https://user-images.githubusercontent.com/8610430/45031035-b136ce80-b088-11e8-93d6-4b754361848d.png)

**Comment by brannondorsey** [comment] 2018-09-04 14:15
Does this occur only when using the webgl backend? I wonder if this is at all related to the memory issues I am experiencing with `model.fit()` with webgl as well https://github.com/tensorflow/tfjs/issues/664?

**Comment by tafsiri** [comment] 2018-09-04 15:28
@MoonsuCha Thanks for the detailed report. Could you let us know which operating system and browser you are using? Also if you post a screenshot of what you see when you visit https://js.tensorflow.org/debug/ that would be helpful.

I couldn't completely replicate this on my system, I did get higher memory usage in 0.12.4 by about 10-15MB so we can look into that, but it didn't cause the program to stop working.

**Comment by MoonsuCha** [comment] 2018-09-05 04:44
@tafsiri Thanks for reply. It is my operating system and browser. My hardware uses the GTX 1070 graphic card for webgl. 
- Chrome ![20180905_133331_1](https://user-images.githubusercontent.com/8610430/45071315-9019c080-b110-11e8-8b30-24b7551de002.png)
- Firefox ![20180905_134201_2](https://user-images.githubusercontent.com/8610430/45071499-86448d00-b111-11e8-81a7-442bbd6554d7.png)

**Comment by tafsiri** [comment] 2018-09-05 15:12
Thanks, I still can't reproduce and since I can't fully understand the memory allocation results in the screenshot you posted. I have another suggestion to help determine if there is a memory leak or something else is going on. It involves adding two lines of code to `camera.js` and then re-running the demo.

Below line 17 (`import * as posenet from '@tensorflow-models/posenet';`) add:

```
import * as tf from '@tensorflow/tfjs';
```

And below line 280 (`stats.end();`) add:

```
console.log(performance.now(), tf.memory());
```

When you run the demo it should log how many tensors are present and how much memory they are using. Adjust the settings to the case where you see the issue and post some of that output here, or if it crashes completely let us know. On my computer it did take much longer for each frame, but the memory usage was unchanged. On my end it looks like this

<img width="934" alt="screen shot 2018-09-05 at 11 12 06 am" src="https://user-images.githubusercontent.com/26408/45102865-969e3d00-b0fc-11e8-9594-ba61ed34c611.png">

**Comment by MoonsuCha** [comment] 2018-09-06 02:58
@tafsiri I tried to your suggestions on 0.12.3 and 0.12.4. It was not occurred the memory overallocation on tf.memory() function ouput, but my system memory reached the full memory. The difference between 0.12.3 and 0.12.4 is gpu numbytes. 0.12.4 version suddenly decreased 0 numbytes on gpu. Is there on association of nvidia-driver or hardware?? 

0. nvidia spec
![20180906_115713_3](https://user-images.githubusercontent.com/8610430/45132467-0e876880-b1cc-11e8-9184-e72af7b08b40.png)


1. 0.12.3
![20180906_113440_2](https://user-images.githubusercontent.com/8610430/45131677-05e16300-b1c9-11e8-9be3-2735f2bc5b9c.png)

2. 0.12.4
![20180906_113020_1](https://user-images.githubusercontent.com/8610430/45131544-5a381300-b1c8-11e8-980a-5313cce630c2.png)

**Comment by tafsiri** [comment] 2018-09-06 15:04
@MoonsuCha Thanks this gives us an idea of what could be the cause (paging). Could you add the following lines to camera.js at around line 24 (after the imports): 

```js
console.log(tf.getBackend());
console.log(
    'Window Info',
    window.screen.height * window.screen.width * window.devicePixelRatio);
console.log('Paging Threshold', tf.ENV.backend.NUM_BYTES_BEFORE_PAGING);
```

Could you paste the output you get from that here? It should be at the top of the console

If that paging threshold is too low for an activation it could cause the problem you are seeing (and provide some data for us to fix it). 

A workaround you could try is adding the following line after those console logs (near the top of the file).

```js
tf.ENV.backend.NUM_BYTES_BEFORE_PAGING = Infinity;
```

this should turn of paging and possibly solve the problem (if its what I think it is).

**Comment by tehsenaus** [comment] 2018-09-07 10:56
I encountered the same issue when running a model on mobile devices. It turns out it's easy to reproduce on a PC if you use a small screen width, which triggers paging.

**Comment by MoonsuCha** [comment] 2018-09-09 03:39
@tafsiri Your solution fix the problem. It currently works well on latest version (0.12.4 ~ latest).  I thinks that this problem related to the line 117 "const BEFORE_PAGING_CONSTANT = 300;" from "backend_webgl.ts"@tfjs-core. Depending on the gpu device, this heuristic variable value should be changed.  Thank you so much.

**Comment by tafsiri** [comment] 2018-09-13 16:12
@MoonsuCha Made another issue to track the fix. Thanks for reporting this!

**Comment by rthadur** [comment] 2018-11-14 22:15
Closing this  as the original raised  issue was addressed and new issue has been opened [here](https://github.com/tensorflow/tfjs/issues/699)

**Closed by rthadur** 2018-11-14 22:15 UTC
Labels: type:bug
