### ISSUE TITLE
posenet camera open problem 

### ISSUE THREAD

**Issue by jesh09** [tensorflow/tfjs#1647] opened 2019-06-02 13:39 UTC
Error: got multiplier type of object when it should be a number in posenet.
utils.ts line 106 compilation error in browser.

**Comment by tafsiri** [comment] 2019-06-03 16:01
Try the instructions here https://www.npmjs.com/package/@tensorflow-models/posenet see [this note](https://github.com/tensorflow/tfjs-models/tree/master/posenet#documentation-note) for context.

**Comment by rthadur** [comment] 2019-06-06 00:30
Hope the issue is resolved , closing this issue .

**Closed by rthadur** 2019-06-06 00:30 UTC
