### ISSUE TITLE
Arbitrary style transfer is slower in tfjs v1

### ISSUE THREAD

**Issue by reiinakano** [tensorflow/tfjs#1528] opened 2019-04-18 17:19 UTC
#### TensorFlow.js version
tfjs 1.0.4

#### Browser version
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

#### Describe the problem or feature request
I decided to try updating my arbitrary style transfer demo to tfjs v1.0.4 from v0.14.1.
Unfortunately, it seemed much slower + more memory-hungry. I haven't had the time to do more detailed benchmarks yet but this is a PR with the update to tfv1 if you want to try things out locally or check for errors in my migration. https://github.com/reiinakano/arbitrary-image-stylization-tfjs/pull/23. I haven't touched the original demo with v0.14.1 yet and it's still at https://reiinakano.github.io/arbitrary-image-stylization-tfjs/.

**Comment by jessetrana** [comment] 2019-04-23 03:46
I wonder if it is related to the performance drop I saw too in #1530 ? Still ongoing investigation but it appears forcing WEBGL_PACK to false may be a suitable workaround.

**Comment by reiinakano** [comment] 2019-04-23 03:49
@jessetrana Thanks for the heads up! I will try it and report back.

**Comment by reiinakano** [comment] 2019-04-23 13:51
It works! I can confirm it's back to normal (maybe even a tiny bit faster)

**Comment by jessetrana** [comment] 2019-04-24 03:41
Excellent! If the team feels there is a singular root cause, would it be appropriate to close either this one or #1530 as a duplicate?

**Comment by tafsiri** [comment] 2019-04-24 15:44
I think leaving this one open might be helpful for now, as it gives us more examples to look at for the impact of WEBGL_PACK.

cc @annxingyuan

**Comment by tafsiri** [comment] 2019-04-24 16:55
And to clarify i meant leaving both of them open for now.

**Comment by rthadur** [comment] 2021-09-10 00:33
Closing this issue as this has been fixed based on the comment here https://github.com/tensorflow/tfjs/issues/1530#issuecomment-575655744 , thank you

**Closed by rthadur** 2021-09-10 00:33 UTC
Labels: comp:core, type:performance, type:support
