### ISSUE TITLE
Different results on linux and windows when running non-Keras model.

### ISSUE THREAD

**Issue by thies1006** [tensorflow/tfjs#434] opened 2018-06-15 15:45 UTC
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.11.6
#### Browser version
Chrome 67.0.3396.79 (Official Build) (64-bit)
#### Describe the problem or feature request
Hi everyone,

we are trying to run a custom yolo model. the model is trained with tensorflow-1.6 and we convert it into a frozen model. this is model is loaded using loadFrozenModel as in the examples. we think that the model runs fine on windows10 pcs and also Mac, however it doesn't detect anything on ubuntu 16/17 (tried several different setups). we made sure that the input data is constant and cross checked the output of each layer. we saw that the outputs after the first few cnn layers is identical, however after the fifth layer we get completely different results. it seems that this happens after applying tf.conv2d operator, however only in this particular layer. i am not sure if this the same problem as in #345. in our case i think the differences are much bigger (which might be also due to different setups of course).

windows10:
![image](https://user-images.githubusercontent.com/32954413/41473238-fbad20b4-70b8-11e8-8d23-2b897ab6eacd.png)

ubuntu16:
![image](https://user-images.githubusercontent.com/32954413/41473300-27c1e0f4-70b9-11e8-8d30-ceb335b1aee1.png)

for completeness: we also loaded another yolo model, however trained with keras which worked fine everywhere. however this model also had a different topology (yolo tiny).

#### Code to reproduce the bug / link to feature request
just checkout:
https://github.com/thies1006/yolo-js

**Comment by thies1006** [comment] 2018-10-03 15:37
Apparently the behavior remains the same in 0.13.1. is there any explanation / solutions for this?
thanks

**Comment by yohacai** [comment] 2018-12-05 11:42
Like 0.1 + 0.2 = 0.300000000000004?

**Comment by dsmilkov** [comment] 2019-03-25 21:25
Marking as duplicate of https://github.com/tensorflow/tfjs/issues/345

**Closed by dsmilkov** 2019-03-25 21:25 UTC
Labels: P1, comp:core

**Comment by thies1006** [comment] 2019-03-26 09:53
checked with 1.0.2. after setting the tensors explicitly to dtype float32 (original code had thrown an error now) i get now identical results on windows and linux ubuntu 16 (chrome browser). the numbers are 99.999% identical to the 'windows10' numbers i posted above, however not identical.
![image](https://user-images.githubusercontent.com/32954413/54987675-43ff7200-4fb5-11e9-924c-32bb3bf4b971.png)

**Comment by dsmilkov** [comment] 2019-03-26 17:03
Great! This is what I've been seeing on the Lenovo Yoga X1 machine too.
