### ISSUE TITLE
PoseNet demos on Safari IOS - no poses estimated as a result of all output tensors having NaN values

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#775] opened 2018-10-10 01:32 UTC
When doing the PoseNet demos on safari IOS, (both the camera and image demo), no poses are ever estimated.  Upon opening the safari debugger and connecting it to the IPhone, all of the output tensors are full of NaN values.

**Comment by yuki-sato** [comment] 2018-10-20 09:16
I'm facing the same.
I think this is happen only with iOS12. Maybe related to #727

**Comment by dsmilkov** [comment] 2018-10-24 12:59
Duplicate of #727

**Closed by dsmilkov** 2018-10-24 12:59 UTC
