### ISSUE TITLE
loadModel from url doesn't work in Node

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#410] opened 2018-06-08 20:33 UTC
(Reported by another user (which is why I don't have the stack trace))

loadModel with a url path doesn't work in Node. This is most likely related to `fetch` missing in node. We should detect the environment and use node's built-in HTTP, or conditionally import [node-fetch](https://www.npmjs.com/package/node-fetch) when we are not in the browser.

cc @nsthorat, @tafsiri for ideas on node <--> browser interop.

**Comment by dsmilkov** [comment] 2018-06-08 20:41
I think the best solution is to import `node-fetch` conditionally, and add 'ignore' flag to rollup to ignore this import when making a browser bundle, just like we do for `crypto` ([rollup config](https://github.com/tensorflow/tfjs/blob/master/rollup.config.js#L31)) which came from our `seedrandom` dependency (see seedrandom's conditional import [here](https://github.com/davidbau/seedrandom/blob/released/seedrandom.js#L237))

**Comment by nsthorat** [comment] 2018-06-10 19:04
That's one solution. Another solution is to basically extend the backend, or create a "platform" which would be node vs browser which has a few methods that we override (fromPixels, fetch, etc). This seems a little cleaner than sprinkling conditional imports.

**Comment by caisq** [comment] 2018-06-10 21:37
@dsmilkov @nsthorat The IOHandlerRegistry are exactly designed to accommodate this kind of environment-dependent handling of URL schemes. In particular, the `http://` URL scheme will be "rounted" to different IOHandler implementations depending on whether the environment is browser or Node.js. This issue can be regarded as a duplicate of https://github.com/tensorflow/tfjs/issues/343, which  is underway. The status is that the file:// handler has been implemented for Node.js and the http:// or https:// handler will happen soon.
So I will close this issue now.

**Comment by dsmilkov** [comment] 2018-06-11 01:51
Sounds good! Would be great if browser specific handlers only get registered in the browser . This way in node it would say "no io handler registered for http" as opposed to using the browser specific one

**Comment by tafsiri** [comment] 2018-06-11 15:30
I think i am in favour of providing someway to pass a function that can things like override fetch. This issue intersects with ones like https://github.com/tensorflow/tfjs/issues/272 where on platforms like Ionic or React Native (hybrid web/native platforms) the developer may want to load from some local store that we can't apriori know how to load from (and where fetch isn't implemented). Allowing for callbacks that enable a user to pull the necessary paths from whatever platform they get tfjs could be quite useful.

@caisq what do you think of this case, is there another way to handle it?

**Comment by caisq** [comment] 2018-06-12 14:44
Thanks, @tafsiri for the comment. How about an API like the following:

1. If the user doesn't need to override `fetch` for environments like React Native, then the `fetch` method will be selected under the hood, automatically, based on whether the environment is browser or node.js. In either case, the following code will work:
```js
const model = await tf.loadModel('http://foo/path/to/model.json');
```

2. If the user needs to override `fetch`, the following API can be used:
```js
const model = await tf.loadModel(tf.io.httpRequest('http://foo/path/to-model.json', {fetch: myCustomFetch}));
```

**Comment by tafsiri** [comment] 2018-06-12 18:22
@caisq In the example above does getting the initial json file also use myCustomFetch? It looks like it will do a regular http request which may throw a user off if they know they can't do a 'local' http request. If the first param doesn't have 'http' in it will it work?

Is this the point where a user need to implement their IOHandler? Is there a way to implement this minimally in a way that controls how each type of resource is loaded, while delegating as much as possible to our existing code.

Something like

```js
const model = await tf.loadModel('path/to/manifest.json', {
	load: myCustomLoadFunc, // what is the required signature for myCustomLoadFunc?
});
```

I imagine myCustomLoadFunc being responsible for either getting a json string or a binary blob to our loadModel code.

or 

```js
const model = await tf.loadModel(tf.io.customIO('path/to/manifest.json', load: loadFunc));
```

Though IMO this is less concise.

**Comment by gabrielfreire** [comment] 2018-06-15 16:45
Hi guys, i don't even remember how i got here in this issue, but as a tfjs user and nodeJs lover i would love to be able to do a simple
```javascript
const model = await tf.loadModel('path/to/model.json');
// or
const model = await tf.loadModel('https://www.path.com/to?my=model.json');
// or
const model = await tf.loadModel('file://path/to/model.json');
```
and let the library do the guessing, sorry for my ignorance, i'm not familiar with the tfjs code for this method, but couldn't you just have something like
```javascript
async loadModel(url: string): Promise<SomeModelClass> {
   if(typeof document === 'undefined'){ // or something else to figure out if there is a browser
       // NodeJS land
       // maybe use some package to extrack url metadata ?
       if(url.match(/\.json$/) == -1) throw 'some error';
       if(url.match(/file(?=\:)/) > -1) console.log(`It\'s a file protocol request, maybe use the node fs module?`);
       else if(url.match(/http(?=\:)/) > -1) console.log(`It\'s a http request, probably use Request module or some cool library`);
       else console.log('It\'s a local request, fs module?');
       return someModelClassInstance;
   }
}
```
?

Sorry again

**Comment by caisq** [comment] 2018-06-15 16:48
Currently (v0.11.6), only the `file://` URL scheme following works in tfjs-node.

Absolute path example:
```js
const model = await tf.loadModel('file:///tmp/path/to/model.json');
// Notice the three slashes after the file:. The first two belong to the scheme. The last one belongs
// to the absolute file path.
```

Relatve path example:
```js
const model = await tf.loadModel('file://./path/to/model.json');
``

We are working on the http:// and no-scheme on in node.js.

**Comment by hyun-yang** [comment] 2018-06-15 21:07
@caisq @tafsiri 
Hi guys,

Actually, I raised the issue [tf.loadModel not working in ionic #272](https://github.com/tensorflow/tfjs/issues/272).

I tested it using tf.loadModel('file://./path/to/model.json') and tf.loadModel('file:///tmp/path/to/model.json'); 

Both of them, got the same error message "TypeError : Failed to fetch", I already uploaded sample ionic project [Tensorflow Pre-Trained Model Import in Ionic Demo](https://github.com/hyun-yang/tfjsionicdemo)

Essentially, hybrid app developer want to load pretrained model from local path.

**Comment by caisq** [comment] 2018-06-16 02:52
@hyun-yang I'm pretty sure saving and loading models with `file://` is working with the latest versions of @tensorflow/tfjs and @tensorflow/tfjs-node. I wrote a simple example at:
https://github.com/caisq/tfjs-dump/tree/master/tfjs-node-doodle

**Comment by hyun-yang** [comment] 2018-06-18 01:01
@caisq I'm not sure, if we are on the same page.

As I mentioned in "tf.loadModel not working in ionic #272"

"What I really want to do is, I want to load this model from local folder( In this case from assets/model/ ) not using http server.

In ionic( I think lots of hybrid app platform has a same build process), when developer builds a native app for Android, iOS and Windows. Developer might want to load model from the local folder which is already packaged inside output file ( apk, ipa ) not using http server.

It'd be great if we have an API like a tf.loadModelFromLocal.

Thanks." 

So, I don't think I need to install  @tensorflow/tfjs-node as well.

I hope this makes sense to you.

Ps.
I tested it your example with node main.js and it shows the result, however that's not what I'm talking about.
Tensor
    [[0.2704779, 0.2301091, 0.21263, 0.2867831],
     [0.2704779, 0.2301091, 0.21263, 0.2867831]]

**Comment by caisq** [comment] 2018-06-18 02:38
@hyun-yang Thanks for the clarification. You are right. I overlooked the fact that you are not in Node.js, but in ionic. Loading in ionic is currently not directly supported. We plan to support it through the custom `fetch` configuration to tf.io.httpRequest as I wrote above. Currently, you may need to write a custom IOHandler implementation. If you need an example, you can look at this code in tfjs-node:
https://github.com/tensorflow/tfjs-node/blob/master/src/io/file_system.ts#L26

**Comment by hyun-yang** [comment] 2018-06-18 06:35
@caisq 
> We plan to support it through the custom fetch configuration to tf.io.httpRequest as I wrote above
Sounds good and I'll have a look tfjs-node code you mentioned.

Thanks.

**Comment by soaxelbrooke** [comment] 2018-09-16 18:52
I found that my problem was `@tensorflow/tfjs-node@0.1.17` - I downgraded to `0.1.7` and things worked.

It appears tfjs was never resolving via the local file system, and constantly wanted to use fetch to get model assets.

**Comment by limscoder** [comment] 2018-09-26 22:33
I get the error even when using a local file running tfjs 13.1 and node 8.1.

```javascript
model = await tf.loadModel('file:///absolute/path/to/model.json');
```

```bash
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
```

**Comment by schipiga** [comment] 2018-10-01 13:12
@limscoder looks like `@tensorflow/tfjs-node@0.1.17` isn't ok. For me it works with previous `v0.1.16`.

```
├─┬ @tensorflow/tfjs@0.13.1
│ ├─┬ @tensorflow/tfjs-converter@0.6.1
│ ├─┬ @tensorflow/tfjs-core@0.13.2
│ └── @tensorflow/tfjs-layers@0.8.1
├─┬ @tensorflow/tfjs-node@0.1.16
```

**Comment by 98mprice** [comment] 2018-11-30 20:15
Almost December and I'm still having this issue. 😕

**Closed** 2018-12-13 21:41 UTC
Labels: comp:core, duplicate

**Comment by hpssjellis** [comment] 2019-03-26 19:03
Just thought I should add this as an alternative if the above solutions are not working for you. Found it on Stackoverflow to do with loading local files for use with Ionic may also work for Phonegap.

https://stackoverflow.com/questions/50224003/tensorflowjs-in-ionic/55306342#55306342

Use a polyfill (https://github.com/github/fetch) and replace the fetch.

`window.fetch = fetchPolyfill;`

Now, it's possible to load local files (file:///) like:

```
const modelUrl = './model.json'

const model = await tf.loadGraphModel(modelUrl);
```

**Comment by nsthorat** [comment] 2019-03-26 19:06
We're working on a fix that should fix this across the board without a fetch polyfill in node: https://github.com/tensorflow/tfjs-core/pull/1648

**Comment by caisq** [comment] 2019-03-26 19:15
FYI, if you use tfjs-node or tfjs-node-gpu, loading a tf.LayersModel (i.e., a model converted from Keras or constructed from TF.js itself) should be working with the latest release.

Code sample:

package.json looks like:
```json
{
    "devDependencies": {
        "@tensorflow/tfjs-node": "^1.0.2"
    }
}
```

Node.js code looks like:
```javascript
const tf = require('@tensorflow/tfjs-node');

(async function() {
    const modelURL = `https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json`;
    const model = await tf.loadLayersModel(modelURL);
    model.summary();
})();
```

**Comment by AlberErre** [comment] 2019-07-24 22:00
> FYI, if you use tfjs-node or tfjs-node-gpu, loading a tf.LayersModel (i.e., a model converted from Keras or constructed from TF.js itself) should be working with the latest release.
> 
> Code sample:
> 
> package.json looks like:
> 
> ```json
> {
>     "devDependencies": {
>         "@tensorflow/tfjs-node": "^1.0.2"
>     }
> }
> ```
> 
> Node.js code looks like:
> 
> ```js
> const tf = require('@tensorflow/tfjs-node');
> 
> (async function() {
>     const modelURL = `https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json`;
>     const model = await tf.loadLayersModel(modelURL);
>     model.summary();
> })();
> ```

Same behaviour here, updating from `^0.1.21` to `^1.0.2` has solved the issue for me ^^

**Comment by aminBenSlimen** [comment] 2020-08-28 14:13
[ Workaround i guess ] hello everyone ... so i'm facing a problem when trying to load my model in ionic 5 it work on browser but wont in android ( i'm using ml5.js but its the same thing since it based on tensorflow.js ) my solution is simply moving all my loading code into the index.html . hope someone find this useful .

**Comment by hpssjellis** [comment] 2020-08-28 19:29
Here is how I convert from tfjs to android c header files.


[https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/tree/master/m09-Tensoflow/tfjs-convert-to-arduino-header](https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/tree/master/m09-Tensoflow/tfjs-convert-to-arduino-header)

**Comment by fernando12170209** [comment] 2020-11-24 05:56
> Just thought I should add this as an alternative if the above solutions are not working for you. Found it on Stackoverflow to do with loading local files for use with Ionic may also work for Phonegap.
> 
> https://stackoverflow.com/questions/50224003/tensorflowjs-in-ionic/55306342#55306342
> 
> Use a polyfill (https://github.com/github/fetch) and replace the fetch.
> 
> `window.fetch = fetchPolyfill;`
> 
> Now, it's possible to load local files (file:///) like:
> 
> ```
> const modelUrl = './model.json'
> 
> const model = await tf.loadGraphModel(modelUrl);
> ```
Help!!

When code the same appear this in the browser:
 Not allowed to load local resource
![image](https://user-images.githubusercontent.com/18425456/100054216-a692bc00-2def-11eb-9741-3759676b271d.png)

this is the message in console
![image](https://user-images.githubusercontent.com/18425456/100054276-c3c78a80-2def-11eb-9fed-1d4f1db01e68.png)
