### ISSUE TITLE
Getting cors error while calling faceLandmarksDetection.createDetector

### ISSUE THREAD

**Issue by Arijitofficial** [tensorflow/tfjs#8188] opened 2024-02-28 10:26 UTC
<em>I could not find the issue section in tfjs-models, so I am posting my issue here:-</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Packages added through `yarn add`
- packages used - (`@tensorflow-models/face-landmarks-detection`, `@tensorflow/tfjs-core`, `@tensorflow/tfjs-backend-webgl`, `@mediapipe/face_mesh`)
- CUDA/cuDNN version: No gpu
- package related to issue: `tfjs-models/faceLandmarksDetection`

**Imports in my react code:**
```import * as faceLandmarksDetection from "@tensorflow-models/face-landmarks-detection";
import "@tensorflow/tfjs-core";
import "@tensorflow/tfjs-backend-webgl";
import "@mediapipe/face_mesh";
```

**Model loading part**
```
const faceapi_model =
      faceLandmarksDetection.SupportedModels.MediaPipeFaceMesh;
    const detectorConfig = {
      runtime: "tfjs"
    };
    const model_setter = async () => {
      const detector = await faceLandmarksDetection.createDetector(
        faceapi_model,
        detectorConfig
      );
      setModel(detector);
    };
```

**Error**
> Access to fetch at "https://tfhub.dev/mediapipe/tfjs-model/facemesh/1/default/1/model.json?tfjs-format=file" from origin "https://mydomain" has been blocked by CORS policy: the 'access-control-allow-origin' header has a value 'https://my-another-domain' which is not equal to the supplied value

**My intuition**

The API call is from https to https, so, I don't know why the error is coming.

What I found about the `tfhub` link is that it may be internally called by `faceLandmarksDetection.createDetector()`:

```
export async function load(modelConfig: MediaPipeFaceDetectorTfjsModelConfig) {
  const config = validateModelConfig(modelConfig);

  const detectorFromTFHub = typeof config.detectorModelUrl === 'string' &&
      (config.detectorModelUrl.indexOf('https://tfhub.dev') > -1);

  const detectorModel = await tfconv.loadGraphModel(
      config.detectorModelUrl, {fromTFHub: detectorFromTFHub});

  return new MediaPipeFaceDetectorTfjs(
      config.modelType, detectorModel, config.maxFaces);
}
```

This `load` function is being used by the `createDetector` function.

**What I have tried:**
- I have tried mediapipe runtime as it has a different load function, though I am facing different error while using that ( I have given the solutionPath in config)
- I have tried to add the origins in my access-control headers in the server

It would be best if there is a way with which I can simply load the model in a local folder in my frontend, then, load the model and serve it.

**Comment by himi1203** [comment] 2024-02-29 05:31
Hi @gaikwadrahul8 facing the same issue, this issue is very frequent and why is it so?

**Comment by Johnrobmiller** [comment] 2024-04-08 23:55
bump, ran into the same bug. Need a solution urgently.

**Comment by Johnrobmiller** [comment] 2024-04-09 00:46
Noticing something here in this error message, it's probably nothing but I don't know.
Error message: 
```
Access to fetch at 'https://www.kaggle.com/models/mediapipe/face-landmarks-detection/frameworks/tfJs/variations/face-mesh/versions/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/mediapipe/tfjs-model/face_landmarks_detection/face_mesh/1/model.json?tfjs-format=file') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Could it be that the CORS error is coming from the domain that is redirecting? If so, then there is very little we can do on our ends to fix this, so I hope this isn't the case.

**Comment by moorjani-ajay** [comment] 2024-04-09 11:53
Anyone found a solution to this?

**Comment by Elintondm** [comment] 2024-04-09 15:17
Any news? We have the same error here.

**Comment by christopherdec** [comment] 2024-04-09 15:31
We changed the runtime from `tfjs` to `mediapipe` and this has solved the CORS problem.

Just follow the instructions from the README here: https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/src/mediapipe

**Comment by Johnrobmiller** [comment] 2024-04-09 16:19
> We changed the runtime from `tfjs` to `mediapipe` and this has solved the CORS problem.
> 
> Just follow the instructions from the README here: https://github.com/tensorflow/tfjs-models/tree/master/face-landmarks-detection/src/mediapipe

Sadly, I was not able to get more than 10 FPS with the mediapipe version, but I could with the tfjs version (after disabling cors), so switching to mediapipe will worrk for some people, but not for all.

**Comment by Johnrobmiller** [comment] 2024-04-09 17:58
This demo was working last Friday when I initially set this up, and now it too is having the exact same CORS error:
https://magdazelena.github.io/face-landmark-detection/

I doubt the demo upgraded any of its packages/dependencies, so whatever changed that is causing the CORS error is external to this tensorflow model.

**Comment by guaxez** [comment] 2024-04-09 18:56
Same problem here. Is there a way to download the model and use from other source?

**Comment by gaikwadrahul8** [comment] 2024-04-16 21:19
Hi, Everyone

We sincerely apologize for the delay in our response and thank you for bringing this issue to our attention, I tried this demo https://magdazelena.github.io/face-landmark-detection/ and it seems like working as expected even I tested the changes by modifying the `index.html` file and everything appears to be functioning as intended on my end. To confirm if the issue is resolved for you as well, could you please verify if you're still encountering the problem?

If you are still experiencing difficulties, it would be very helpful if you could share a minimal reproducible example through a GitHub repository or CodePen. This will allow us to more accurately replicate the behavior you're encountering and assist you in resolving it.

If I have missed something here please let me know. Thank you for your cooperation and patience.

**index.html** file :

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TensorFlow.js face-landmarks-detection model testing</title>
  </head>
  <body>
    <!-- Require the peer dependencies of pose-detection. -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter"></script>
    <!-- You must explicitly require a TF.js backend if you're not using the TF.js union bundle. -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
    <!-- Alternatively you can use the WASM backend: <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/face-landmarks-detection@1.0.5/dist/face-landmarks-detection.min.js"></script>

    <script>
      async function main() {
        await tf.setBackend("webgl");
        await tf.ready();
        const model = faceLandmarksDetection.SupportedModels.MediaPipeFaceMesh;
        const detectorConfig = {
          runtime: "tfjs",
          solutionPath: "https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh",
        };
        const detector = await faceLandmarksDetection.createDetector(
          model,
          detectorConfig
        );
        console.log(detector);
      }

      main();
    </script>
  </body>
</html>
```
**Output of index.html file :**

![image](https://github.com/tensorflow/tfjs/assets/115997457/d7645092-4190-4f3a-8a2c-976a6ccebe2a)

**Comment by gaikwadrahul8** [comment] 2024-04-24 13:44
Hi, @christopherdec Thank you for the confirmation

Hi, @Arijitofficial, @Johnrobmiller, @himi1203, @moorjani-ajay, @Elintondm, @guaxez 

I'd appreciate it if you could verify on your end that everything is functioning as intended. If so, please feel free to close this issue now.

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment] 2024-04-27 11:00
Hi, @christopherdec, @guaxez

Thank you for confirming that the reported issue seems to be resolved. We appreciate your cooperation in troubleshooting and providing feedback.

To ensure a smooth resolution process for any future occurrences, if you encounter the issue again, please provide a detailed comment outlining the encountered error message. This information will allow us to proactively address the problem and offer the most effective assistance.

In the absence of further reports, I will proceed to close this issue now. However, if the issue reappears, please feel free to post your comments and we'll be happy to assist you further.

Thank you for your cooperation and patience.

**Closed** 2024-04-27 11:01 UTC
Labels: comp:models, type:others

**Comment by coolcorexix** [comment] 2024-07-04 01:45
I am having it today again, can you please check :(

**Comment by ThatXliner** [comment] 2024-09-20 00:13
I'm also getting CORS errors, but this time it is with the pose models

**Comment by ghaschel** [comment] 2025-01-20 16:51
This CORS issue is happening again.
