### ISSUE TITLE
Breaking change: #7951 (tfjs-v4.11.0)

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#7974] opened 2023-09-24 12:42 UTC
- TensorFlow.js version (use command below): tfjs-v4.11.0

**Describe the current behavior**
Old models fail now that #7951 is merged. Error: 
> ERROR Error: Uncaught (in promise): Error: {this.name} outputs 1 tensors but only one mask
Error: {this.name} outputs 1 tensors but only one mask

(This is not the case with v4.10.0)

**Describe the expected behavior**
Minor updates should not break functionality

**Standalone code to reproduce the issue**
Same as https://github.com/tensorflow/tfjs/issues/6699

**Comment by AmitMY** [comment] 2023-09-26 08:22
I'm getting the same issue now.

Here, I wrote a minimal reproduction:
What I learned, is that the problem goes away if I don't `resetDropout` (I don't want dropout in inference)

(Here's a directory with a new model, and an HTML file. to reproduce, I ran `http-server .`)
https://drive.google.com/file/d/1Y8OIdTetbDn0mcppE_sRL8bRP-vh_1tP/view?usp=drive_link

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8" />
    <title>TensorFlow.js browser example</title>

    <!-- Load TensorFlow.js from a script tag -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest/dist/tf.min.js"></script>
</head>
<body>
<h1>TensorFlow.js example</h1>
<h2>Open the console to see the results.</h2>
<script>
    function resetDropout(layers) {
        for (const layer of layers) {
            // For Sequential models, the layers are in the layers property
            if (layer.layers) {
                resetDropout(layer.layers);
            }

            // For TimeDistributed models, the layer is in the layer property
            if (layer.layer) {
                resetDropout([layer.layer]);
            }

            // If the layer is a dropout layer, reset the rate
            if (layer.rate) {
                layer.rate = 0;
            }
        }
    }

    async function main() {
        const model = await tf.loadLayersModel('model_new.json');
        resetDropout(model.layers);

        const tensor = tf.zeros([1, 1, 256, 256, 3]).toFloat();
        tensor.print();

        // Must apply model in training=True mode to avoid using aggregated norm statistics
        model.apply(tensor, {training: true}).print();
    }

    main();
</script>
</body>
</html>
```

**Comment by gaikwadrahul8** [comment] 2023-09-27 09:38
Hi, @AmitMY 

Thank you for providing the minimal code example to replicate the same issue from my end and I'm getting below error message so to confirm, Are you also getting the same error message or different error message if possible could you please share your error log or screenshot which will help us to investigate this issue further.  Thank you!

For reference I have added screenshot below :

![image](https://github.com/tensorflow/tfjs/assets/115997457/ae6be7df-6275-4a3f-953d-d64a88535cfb)

**Comment by gaikwadrahul8** [comment] 2023-09-29 05:12
Hi, @AmitMY 

Thank you for the confirmation, I really appreciate your findings and observations which will help us to investigate this issue further. We will have to dig more into this issue and will update you soon. Thank you!

**Comment by Linchenn** [comment] 2023-09-29 17:48
Hi @haoyunfeix , I saw you fixed https://github.com/tensorflow/tfjs/issues/6699 before, could you help check this again?

**Comment by gyagp** [comment] 2023-09-30 01:53
Yunfei already left Intel, so he may not double check this. We will take a look once we get back to office after holidays (Oct 7).

**Comment by Linchenn** [comment] 2023-09-30 05:49
Thank you Yang and take your time.

**Comment by mattsoulanille** [comment] 2023-10-03 20:43
This is likely a bug in https://github.com/tensorflow/tfjs/pull/7951. I'm trying to reproduce it, but I'm running into a different error than expected:
```
Uncaught (in promise) Error: Identity matrix initializer can only be used for 2D square matrices.
    at initializers.js:241:15
    at engine.js:469:20
    at e.value (engine.js:480:19)
    at e.value (engine.js:467:17)
    at e8 (globals.js:192:17)
    at n.value (initializers.js:239:12)
    at n.value (topology.js:1288:35)
    at n.value (recurrent.js:1703:24)
    at n.value (recurrent.js:516:17)
    at topology.js:981:14
```
    
Did the model file shared at that drive link change? Additionally, I'd be interested to know if this only fails with WebGPU, since if it's a bu in #7951, it's probably going to affect all backends.

**Comment by AmitMY** [comment] 2023-10-04 12:30
I redownloaded the zip file and can confirm the same hash:
```
shasum -a 256 web_model.zip
ab24c0af3c44d6268b8914a346bd8917b17984245e9ffd6b0ee5d751cefd7167
```

However, the error I am seeing is still
> Uncaught (in promise) Error: {this.name} outputs 1 tensors but only one mask


Furthermore, this repro is not using WebGPU, but WebGL:
<img width="128" alt="image" src="https://github.com/tensorflow/tfjs/assets/5757359/b326dd0c-82a4-4713-975b-c357f762a041">

**Comment by axinging** [comment] 2023-10-07 05:51
I tried webgpu, webgl, cpu, all complain same errors:
```
topology.js:1409 Uncaught (in promise) Error: {this.name} outputs 1 tensors but only one mask
    at n.value (topology.js:1409:13)
    at topology.js:1013:16
    at nue (common.js:48:20)
    at n.value (topology.js:967:12)
    at xce (executor.js:341:25)
    at container.js:746:14
    at engine.js:469:20
    at e.value (engine.js:480:19)
    at e.value (engine.js:467:17)
    at e8 (globals.js:192:17)
```

Revert this change (https://github.com/tensorflow/tfjs/pull/7951) works well on webgpu, webgl, cpu.

Below code is required to change backend before predict:
```
        await tf.setBackend('webgl'); //webgpu, cpu
        console.log(tf.getBackend());
        await tf.ready();
```

**Comment by gaikwadrahul8** [comment] 2023-10-18 12:44
Hi, @AmitMY 

I apologize for the delayed response. I see that PR  https://github.com/tensorflow/tfjs/pull/7993 has been merged and I have tested the same [code snippet](https://github.com/tensorflow/tfjs/issues/7974#issuecomment-1735060726), which is now working as expected. could you please confirm this from your end once ? if so, please feel free to close this issue ? Thank you!

**Comment by AmitMY** [comment] 2023-10-18 14:01
i can confirm that i am using 4.12.0
![image](https://github.com/tensorflow/tfjs/assets/5757359/1322eaef-77dc-4412-8d21-d5b858938125)

but that the bug remains
![image](https://github.com/tensorflow/tfjs/assets/5757359/3c5ba3ac-034a-43cc-a48b-003f672080dc)

My reproduction still reproduces the issue in 4.12.0
https://github.com/tensorflow/tfjs/issues/7974#issuecomment-1735060726

**Comment by axinging** [comment] 2023-10-19 01:54
@AmitMY, it seems 4.12.0 doesn't include change https://github.com/tensorflow/tfjs/pull/7993.
You can see 4.12.0 commits history here: 
https://github.com/tensorflow/tfjs/commits/cb5cd829909a07cdbd14975f2169a78e9213bf4a
Also, you can view it here: https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.12.0

So @gaikwadrahul8 @Linchenn,  Could you help why https://github.com/tensorflow/tfjs/pull/7993 is not included in v4.12.0?

BTW, @AmitMY, if you want to try this feature on the latest code,  You can download TFJS code and build, then put below file under fold tfjs\e2e\benchmarks\local-benchmark:
```
<html>

<head>
  <title>TensorFlow.js Op demo</title>
</head>

<body>
  <h2>TensorflowJS Model demo</h2>
  <script src="loader.js"></script>
  <!-- <script src="weakmap.js"></script>-->
  <br>
  <button id="mainTest">Main Test</button>
  <br><br>
  <script>
    'use strict';

    function resetDropout(layers) {
      for (const layer of layers) {
        // For Sequential models, the layers are in the layers property
        if (layer.layers) {
          resetDropout(layer.layers);
        }

        // For TimeDistributed models, the layer is in the layer property
        if (layer.layer) {
          resetDropout([layer.layer]);
        }

        // If the layer is a dropout layer, reset the rate
        if (layer.rate) {
          layer.rate = 0;
        }
      }
    }

    async function main() {
      await tf.setBackend('webgpu');
      console.log(tf.getBackend());
      await tf.ready();
      const model = await tf.loadLayersModel('model.json');
      resetDropout(model.layers);

      const tensor = tf.zeros([1, 1, 256, 256, 3]);//.toFloat();
      tensor.print();

      // Must apply model in training=True mode to avoid using aggregated norm statistics
      model.apply(tensor, { training: true }).print();
      console.log("end");
    }

    (async function () {
      let localBuild = ['core', 'cpu', 'webgl', 'webgpu', 'tfjs-converter', 'layers'];
      // let localBuild = [];
      await loadTFJS(localBuild);
      await tf.setBackend('cpu');
      await tf.ready();
      tf.env().set('WEBGPU_CPU_FORWARD', false);
      console.log(tf.getBackend());
      main();


    })();
  </script>
</body>

</html>

```

**Comment by AmitMY** [comment] 2023-10-23 10:12
since @gaikwadrahul8 says it works, i'll just wait for it to be released. Do you know why it was not released, and if it would be in 4.13.0?

**Comment by mattsoulanille** [comment] 2023-10-23 22:06
Sorry, we're working on a new RC based release structure, and our branch cut for 4.12.0 was before the fix was merged. This will be included in 4.13.0 next week.

**Comment by peacefulotter** [comment] 2023-11-06 12:19
Any news on this? 4.13.0 seems to not be released yet and it's been more than a week. Thanks!

**Closed** 2023-11-08 14:25 UTC
Labels: type:bug, comp:webgpu
