### ISSUE TITLE
Explicitly set WebGL capabilities by checking valid extensions.

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1731] opened 2019-07-10 16:30 UTC
To help with React Native and Headless WebGL - we should re-rework WebGL capability by testing features and extensions.

This can get complicated with the various versions and reporting of GL extensions about f16/f32 extension checking.

For example:
The presence of `EXT_color_buffer_float` or `EXT_color_buffer_half_float` indicate a more recent and most likely WebGL2 rendering-like context.

The presence of `OES_texture_float` or `OES_texture_half_float` should signal an older GL runtime - most likely WebGL1.

It would also be great to fix a few other feature flags:
- `WEBGL_MAX_TEXTURE_SIZE` - just ask the gl runtime: `gl.getParameter(gl.MAX_TEXTURE_SIZE)` (project from querying the DOM in tfjs-core).
- `WEBGL_FENCE_API_ENABLED` - this is trickier and requires asking for a few extensions as well. ([EXT_disjoint_timer_query](https://developer.mozilla.org/en-US/docs/Web/API/EXT_disjoint_timer_query), etc).

**Comment by gaikwadrahul8** [comment] 2023-10-11 12:30
Hi, @nkreeger 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:23
Hi, @nkreeger 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:23 UTC
Labels: type:others, stat:awaiting response, comp:backend-webgl
