### ISSUE TITLE
Support for AutoML Vision Edge models with sharded weights in React Native

### ISSUE THREAD

**Issue by nicholas** [tensorflow/tfjs#3197] opened 2020-05-01 17:38 UTC
#### TensorFlow.js version

@tensorflow/tfjs : 1.7.3
@tensorflow/tfjs-react-native : 0.2.3

#### Browser version

expo : 37.0.8

#### Describe the problem or feature request

Since you: 
- Can't load sharded weights using the [bundleResourceIO](https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/src/bundle_resource_io.ts#L32) function provided in tfjs-react-native.
- [Can't run your own tensorflowjs conversion](https://github.com/tensorflow/tfjs/issues/1513#issuecomment-546449981) to change the `weight_shard_size_bytes` on a TF Saved Model [exported from AutoML](https://cloud.google.com/vision/automl/docs/export-edge#container).

You get caught at an impasse when trying to use an AutoML Vision Edge model through the React Native APIs. It seems to me the options for someone with this issue are:
- Attain the ability to turn weight sharding off within AutoML's Cloud UI.
- Attain a way to reproduce the exact `tensorflowjs_converter` command that AutoML runs on their end. Or however they make that conversion.
- Attain a way to load multiple shards within the tfjs-react-native `bundleResourceIO`.
- Attain a way to rejoin shards. I'm out of my depth, would that even be possible? I've experimented with taking non-sharded weights from my own conversion runs and splicing them into the model.json produced by AutoML with no luck.

#### Code to reproduce the bug / link to feature request

There's not too much relevant code to show since it's explicitly unsupported in tfjs-react-native. However, fwiw, here's the conversion code I attempted to use when I realized direct support for the artifacts produced by AutoML tfjs export were not usable.

```bash
# This produces significantly different results than what is produced through the AutoML tfjs export.
tensorflowjs_converter \
  --input_format=tf_saved_model \
  --output_format=tfjs_graph_model \
  --weight_shard_size_bytes=10485760 \
  --skip_op_check \
  00000123 \
  test
```

**Comment by AbdulRashidReshamwala** [comment] 2020-05-01 18:04
You can load shared model via https I'm facing the same issue using bundleResourse

**Comment by tafsiri** [comment] 2020-05-04 14:29
Hi. I think the path you want is your second point, converting the model to use a single shard. Sharding is primarily advantageous for web browsers and caching, when the model is local we generally want to fetch that in one request/read. `weight_shard_size_bytes` should the path you want. 

Could you elaborate on your last point about the model having different results when you run it through the tfjs converter? Would you be able to post some sample code somewhere with your converted model to reproduce?

cc @pyu10055 @dsmilkov.

**Comment by nicholas** [comment] 2020-05-04 19:06
Yea, I agree that path makes the most sense.

As for the different results, I'm referring to the model.json that's created and the ability to get a functioning result back. In the process of setting up a sample to share I managed to sidestep some of the issues I'd seen previously -- specifically around the input signature, I had to sleuth around to find the magic `ToFloat` key -- but the differences are still present. I'm only assuming that this is what's responsible for the malfunction.

See https://github.com/nicholas/tfjs_issue_3197

Notice the differences between https://github.com/nicholas/tfjs_issue_3197/blob/master/assets/exported_tfjs/model.json & https://github.com/nicholas/tfjs_issue_3197/blob/master/assets/converted_tfjs/model.json

I've added some commentary about the errors I'm seeing here: https://github.com/nicholas/tfjs_issue_3197/blob/master/App.js#L54

Note that this same model, the weight sharded, direct AutoML tfjs export, functions as expected using the the instructions laid out in [tfjs-automl](https://github.com/tensorflow/tfjs/tree/master/tfjs-automl).

Side note, over the weekend I played around with the [sample integration](https://github.com/tensorflow/tfjs/tree/master/tfjs-react-native/integration_rn59). I had issues getting that work so I spun up a brand new React Native 62 project and ported everything over with success -- with some minor issues pending. Is that something you'd be interested in a PR for?

**Comment by tafsiri** [comment] 2020-05-04 20:48
For the conversion step have you tried converting the auto-ml tfjs export from a sharded model to a non sharded model directly (no savedmodel). 

The converter can take tfjs models as inputs as well, see https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#javascript-to-javascript.

**Comment by tafsiri** [comment] 2020-05-04 20:49
In this case both the input and output type would be tfjs_graph_model.

**Comment by nicholas** [comment] 2020-05-04 21:09
Hey, thanks for taking a look. That does look promising, I'll run some more experiments and report my findings back here.

**Comment by nicholas** [comment] 2020-05-04 21:21
Unfortunately, tfjs_graph_model to tfjs_graph_model conversion does not appear to be a supported feature.

```
tensorflowjs_converter \
  --input_format=tfjs_graph_model \
  --output_format=tfjs_graph_model \
  --weight_shard_size_bytes=10485760 \
  --skip_op_check \
  assets/exported_tfjs/model.json \
  assets/converted_tfjs

...
TensorFlow.js model converters.: error: argument --input_format: invalid choice: 'tfjs_graph_model' (choose from 'tf_hub', 'keras_saved_model', 'keras', 'tf_frozen_model', 'tf_saved_model', 'tfjs_layers_model')
```

And after some review, I don't see that option in what I think is the [main entry point for conversion](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/python/tensorflowjs/converters/converter.py#L587).

**Comment by tafsiri** [comment] 2020-05-04 21:33
@pyu10055 Could we support a configuration in the converter like the one above to support unsharding a sharded tfjs_graph_model? Or is there another option for unsharding.

**Comment by pyu10055** [comment] 2020-05-18 16:53
@tafsiri @nicholas Unsharding a tfjs_graph_model is possible, but I don't think we should provide it as converter option, since allowing tfjs_graph_model as a input format and supporting all options are beyond the need for fixing this issue. we can create an js util class to perform the unsharding.

**Comment by tafsiri** [comment] 2020-05-19 19:02
What if it were just a specific unsharding command in the converter so they do not have to get a separate tool (but it doesn't otherwise allow full conversion of graph models)?

**Comment by pyu10055** [comment] 2020-05-19 23:18
@tafsiri after thinking about this more, it might make sense to provide graph_model to graph_model conversion, the allowed features could include sharding and quantization.
I will look into that.

**Comment by tafsiri** [comment] 2020-11-17 17:23
Closing, sharded models are now supported in tfjs-react-native https://github.com/tensorflow/tfjs/pull/4113

We also updates the instructions on the [automl README](https://github.com/tensorflow/tfjs/tree/master/tfjs-automl#loading-the-model-1) to describe how to load a model with a custom IOHandler (i.e. something other than a string).

**Closed by tafsiri** 2020-11-17 17:23 UTC
Labels: comp:autoML, comp:converter, comp:react-native
