### ISSUE TITLE
Explore using fewer buckets for WebGL texture manager to improve texture reuse.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1074] opened 2019-01-09 15:53 UTC
Relax the condition for reusing a texture to just require that it be large enough to accommodate tensor.

Also try using nearest POT textures.

This would help the Universal Sentence Encoder lite deal with inputs of different lengths.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:36
Hi, @annxingyuan 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:36 UTC
Labels: type:performance, stat:awaiting response, comp:backend-webgl
