### ISSUE TITLE
Provide rate limiting transform.

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1030] opened 2018-08-31 17:32 UTC
This basically sleeps each promise so that they don't resolve faster than n/sec.

Because we are pulling promises, not the actual data elements, it's easy to e.g. request frames from the webcam at 10 khz instead of 60hz, which quickly crashes the browser.

Sometimes the source is intrinsically rate-limited; sometimes the consumer is a bottleneck (e.g., training time), but sometimes it's neither.

Currently we avoid the problem because resolveFully() (and hence forEach()) awaits each promise before requesting the next one.

Also, you may not always want to do work as fast as possible. Maybe predicting 1 frame/sec from the webcam is good enough for your application, so this lets you not waste resources.

**Comment by davidsoergel** [comment] 2019-03-05 02:55
We decided to expect the user to pull from a webcam stream using next() at whatever rate they choose-- i.e. rate limiting will be their responsibility, not something that we provide in the framework.

I believe there will still be legitimate use cases for this, but it's deprioritized for now.

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:20
Hi, @davidsoergel 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:43
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:43 UTC
Labels: type:feature, stat:awaiting response, comp:data
