### ISSUE TITLE
Problem Converting tensorflow garden model in format of Tensorflow Saved Model to a Web Model with tensorflowjs

### ISSUE THREAD

**Issue by FOLZi-4G** [tensorflow/tfjs#8304] opened 2024-06-15 04:05 UTC
**System information**
- For the training and building the model i used the same code as the guide in https://www.tensorflow.org/tfmodels/vision/object_detection
- Python version: 3.10.12
- Tensorflow version: 2.16.0
- TensorFlow.js version: 4.20.0
- Code ran with Google Colab.

**Describe the current behavior**
I tried to convert the model i trained with my own custom dataset, but when the conversion of the saved model hapened, it first output this repeated error.
```2024-06-15 03:21:26.894598: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-06-15 03:25:44.975342: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:961] remapper failed: INVALID_ARGUMENT: MutableGraphView::MutableGraphView error: node 'StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/activation_3/Relu' has missing fanin 'StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/BiasAdd'.
2024-06-15 03:25:45.312683: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 0, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/activation_3/Relu
2024-06-15 03:25:45.371166: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 1, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
2024-06-15 03:25:45.745130: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 0, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
2024-06-15 03:25:45.775964: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 1, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
```
**Describe the expected behavior**
I would expect that my model would be converted normally in the same way i converted my model into tflite, just as in my notebook.

**To reproduce the issue**
https://colab.research.google.com/drive/1lLfgEeOr-pYmBqIlI3tridwXoZVUqkQy?usp=sharing

**Full logs**
```2024-06-15 03:21:26.894598: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-06-15 03:25:44.975342: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:961] remapper failed: INVALID_ARGUMENT: MutableGraphView::MutableGraphView error: node 'StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/activation_3/Relu' has missing fanin 'StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/BiasAdd'.
2024-06-15 03:25:45.312683: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 0, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/activation_3/Relu
2024-06-15 03:25:45.371166: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 1, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
2024-06-15 03:25:45.745130: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 0, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
2024-06-15 03:25:45.775964: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:772] Iteration = 1, topological sort failed with message: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 959, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 963, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 949, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 655, in _dispatch_converter
    tf_saved_model_conversion_v2.convert_tf_saved_model(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 982, in convert_tf_saved_model
    _convert_tf_saved_model(output_dir, saved_model_dir=saved_model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 857, in _convert_tf_saved_model
    optimized_graph = optimize_graph(frozen_graph, signature,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 188, in optimize_graph
    optimized_graph = _run_grappler(config, optimized_graph, graph, signature_def)
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 129, in _run_grappler
    return tf_optimizer.OptimizeGraph(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/grappler/tf_optimizer.py", line 61, in OptimizeGraph
    out_graph = optimize_method(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Non-existent input StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/post_hoc_5/BiasAdd in node StatefulPartitionedCall/StatefulPartitionedCall/fpn_1/coarser_6/Conv2D
```

**Comment by gaikwadrahul8** [comment] 2024-06-18 07:33
Hi, @FOLZi-4G 

I apologize for the delayed response and I was trying to replicate the same behavior from my end and I'm also getting the same error message `ValueError: Unsupported Ops in the model before optimization Assert` here is [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/cca2bb92d72714ca5c9a00d548155e54/issue-8304.ipynb) for reference, it seems like there are some Unsupported Ops in the model and currently TensorFlow.js only supports a limited set of TensorFlow Ops. See the [full list](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/docs/supported_ops.md). If your model uses unsupported ops, the `tensorflowjs_converter` script will fail

Thank you for your understanding and patience.

**Comment by FOLZi-4G** [comment] 2024-06-18 12:04
Thanks for the response, @gaikwadrahul8.
You are right about the unsupported Ops. After I looked through the tfjs github, I decided to use the convert_tf_saved_model() function from the tf_saved_model_conversion_v2.py instead of my first attempt, and it gave the same error as yours. Now that I know the problem, you can close this issue.

**Comment by gaikwadrahul8** [comment] 2024-06-19 18:12
Hi, @FOLZi-4G 

Thank you for the update, I appreciate you revisiting the issue and trying out the `convert_tf_saved_model()` function. It's unfortunate that you encountered the same error. Your decision to use the supported Ops aligns with our recommendations for compatibility.

Since you've identified the root cause and have found it to be related to unsupported Ops, I'll proceed to close this issue. Feel free to reach out if you have any further questions or encounter any other issues in the future.

Thank you for your cooperation and patience.

**Closed by gaikwadrahul8** 2024-06-19 18:12 UTC
Labels: type:bug, comp:converter

**Comment by RayanMoarkech** [comment] 2024-10-18 20:58
@FOLZi-4G May you please share the solution you implemented? Did you used a different model to make it work with tfjs conversion?
