### ISSUE TITLE
Augment Dataset.size with Dataset.maxSize and Dataset.minSize

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1244] opened 2019-02-14 19:16 UTC
If I have a dataset `ds` of unknown size, then `ds.take(100)` currently produces another dataset of unknown size-- but we could usefully track that the size is now *at most* 100 (and similarly throughout the size-propagation code).

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:33
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:33 UTC
Labels: type:feature, P3, stat:awaiting response, comp:data
