### ISSUE TITLE
Difference between the results obtained from the model on windows and linux

### ISSUE THREAD

**Issue by SkalskiP** [tensorflow/tfjs#345] opened 2018-05-25 20:03 UTC
#### TensorFlow.js version
"@tensorflow/tfjs": "^0.10.3"

#### Browser version
Last test on:
Google Chrome | 64.0.3282.140 / Linux Mint Sylvia  / GeForce 840M
![test2](https://user-images.githubusercontent.com/26109316/40621029-77cfb304-629b-11e8-9903-dd4bcd280309.png)

Google Chrome | 66.0.3359.181 / Windows 10 / Intel(R) HD Graphics 4000
![test](https://user-images.githubusercontent.com/26109316/40621046-8c1a481a-629b-11e8-8733-5700be5e24cc.png)

Google Chrome | 66.0.3359.181 / Windows 10 Pro / Intel(R) HD Graphics 4000
![test](https://user-images.githubusercontent.com/26109316/40605314-3f9be0cc-6262-11e8-8a59-eb3935b33813.PNG)

Google Chrome | 66.0.3359.181 / MacOS 10.13.4 (Macbook Pro 13 2015) / Intel Iris 6100
![test2](https://user-images.githubusercontent.com/26109316/40620922-f7c0f09c-629a-11e8-9ff0-3d5923f62b16.png)

#### Describe the problem or feature request
The Tiny Yolo model in TensorFlow.js returns different predictions for the same image on different computers. My tests show that the results may depend on the operating system. The predictions were the same on all Linux computers I checked but different on Windows. The model detected the same classes of objects but differences in probabilities reached several dozen percent.

#### Code to reproduce the bug / link to feature request
According to a Twitter conversation with Nikhil Throat, the code can be found here on GitHub: https://github.com/SkalskiP/ILearnMachineLearning.js Working demo with "tf.ENV" logged: http://i-learn-machine-learning.science.

**Comment by juanmirod** [comment] 2018-06-06 07:08
Hi @SkalskiP have you found the reason for this difference? we are having a similar problem with YOLO, a model finds objects running under Windows, but nothing if the page is under Linux, same code and model, same Chrome version, same image, but different results.

**Comment by SkalskiP** [comment] 2018-06-09 19:44
@juanmirod no unfortunately I have not been able to explain this phoneme for now.  If you find any explanation let me know. Please.

**Comment by nsthorat** [comment] 2018-10-26 15:07
Hi guys, do you still see this problem on 0.13.3?

**Comment by thies1006** [comment] 2018-10-26 15:51
Hi! i did a quick check and for me with this version the numbers stay exactly the same.

**Comment by SkalskiP** [comment] 2018-10-26 22:39
I will need some time to reproduce my test on all devices. I will come back to you with the information as soon as possible.

**Comment by dsmilkov** [comment] 2019-03-25 21:27
Hi,

We just got a windows machine with Intel GPU where we can do more testing. Does the problem still persist on tfjs@1.0.2? If yes, if you can send us the up-to-date reproduction, that would be very helpful! Thank you!

**Comment by dsmilkov** [comment] 2019-04-10 17:36
Closing this issue. Let me know if someone can still reproduce this problem using the latest tfjs library.

**Closed by dsmilkov** 2019-04-10 17:36 UTC
Labels: P1, Windows, comp:core, type:bug
