### ISSUE TITLE
tf.log gives different results than Math.log

### ISSUE THREAD

**Issue by HarshalRohit** [tensorflow/tfjs#4361] opened 2020-12-06 18:41 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Pop_OS 20.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 2.6
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**
tf.log() returns 
0.9999999403953552 for Math.E
0.6931471824645996 for 2

**Describe the expected behavior**
should return
1 for Math.E
0.6931471805599453 for 2

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The difference in decimal places is creating issues in my project.

**Comment by rthadur** [comment] 2020-12-07 19:50
@HarshalRohit please give a reproduction code or codepen example ?

**Comment by HarshalRohit** [comment] 2020-12-09 06:48
Hi, Please guide me on creating a reproducible code.
I am currently working on tfjs and react-native, and dont have any idea on creating reproducible code for react-native.

**Comment by tafsiri** [comment] 2020-12-09 16:31
Hi thanks for reporting. I am able to reproduce the behavior and can explain where it is coming from. This behavior is coming from imprecision in float32 representations for numbers (which are used throughout tfjs). You can reproduce this in pure javascript with the following line `Math.log(new Float32Array([Math.E])[0])`. Putting Math.E in a Float32Array will change the representation of the number and add some imprecision. This isn't something we can avoid.

What problems is this causing in you application/project? 

Because of this imprecision, if you are using float32 tensors and want to do comparisons you shouldn't use exact comparison, you should instead check that the numbers are close to each other within some range of tolerance (we often use `1e-7` for float 32 comparisons).

**Comment by HarshalRohit** [comment] 2020-12-10 06:26
Hi Thanks for the explanation. I suspected the issue but wanted to have clarification on it.

My project involves writing a js implementation of converting .wav audio files to spectrogram representation using tfjs ops. I am using [this](https://towardsdatascience.com/understanding-audio-data-fourier-transform-fft-spectrogram-and-speech-recognition-a4072d228520) as the reference implementation and also for comparison purposes. To compare them I calculating _sum of squared differences_, which ranges between 10^-1 to 10^-4. This range isn't very good, I guess.

**Comment by tafsiri** [comment] 2020-12-10 15:22
No problem. Looks like you got the info you needed to I'll close this for now. Good luck on the project!

**Closed by tafsiri** 2020-12-10 15:22 UTC
Labels: stat:awaiting response, type:bug
