### ISSUE TITLE
Allow alternative GLContexts to be set globally.

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1607] opened 2019-05-23 23:27 UTC
Currently, `canvas_util.ts` has some caching of WebGL context versions with a retrieval function that attempts to load a WebGL context by creating a new `canvas` DOM element.

Ideally, we have a flag or global override to set the WebGL/GL context object.

For instance, setting `WEBGL_FENCE_API_ENABLED` to false will result in this exception when running outside of the browser:

```
(node:89462) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at getWebGLRenderingContext (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/canvas_util.ts:63:18)
    at getWebGLContext (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/canvas_util.ts:37:30)
    at Object.getWebGLContext (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/canvas_util.ts:42:12)
    at Object.getWebGLDisjointQueryTimerVersion (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/webgl_util.ts:516:14)
    at Object.evaluationFn (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/flags_webgl.ts:104:21)
    at Environment.evaluateFlag (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/environment.ts:98:40)
    at Environment.get (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/environment.ts:61:33)
    at Environment.getNumber (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/environment.ts:67:17)
    at GPGPUContext.createFence (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/gpgpu_context.ts:254:13)
    at GPGPUContext.createAndWaitForFence (/Users/kreeger/workspace/tfjs-backend-nodegl/node_modules/@tensorflow/tfjs-core/src/backends/webgl/gpgpu_context.ts:232:31)
```

I tried importing `setWebGLContext` but the key as a `number` does not work on `contexts`. I'll whip up a patch tomorrow for this.

**Comment by pmer** [comment] 2020-06-30 20:14
Relatedly, if you do your own WebGL stuff in the same context as Tensorflow.js, you have to restore TFJS's vertex attributes and ELEMENT_ARRAY_BUFFER because TFJS only sets them once at initialization time. Once you do that, it works fine.

**Comment by sebavan** [comment] 2020-09-15 20:14
@pmer do you know any easy way to set back the TFJS's Vertex Attribs ? I am wondering how involved it might be.

**Comment by pmer** [comment] 2020-09-15 20:53
Yes. I was able to get it to work by checking if `gpgpu.vertexAttrsAreBound` is true, and if it is, then call `gpgpu_util.bindVertexProgramAttributeStreams(gl, false, gpgpu.program, gpgpu.vertexBuffer)`. Right now `vertexAttrsAreBound` is a private member variable, so if you are using TypeScript, you have to cast `gpgpu` to `any` before using it.

This logic works on current TFJS, but since it's not part of the public API, it could break on any future release. Although that's what this GitHub issue is about.

**Comment by sebavan** [comment] 2020-09-15 21:01
AMAZING !!!! I ll give it a try ASAP :-)

**Comment by sebavan** [comment] 2020-09-15 21:47
Works like a charm !!! thanks a ton.

**Comment by pmer** [comment] 2020-09-16 01:00
Glad to hear it!!

I don't think this issue would be too hard to fix by someone who knew how it could fit in best with the public API that TFJS wants to expose. Although it would be nice to not have to create a hack to make this work. @sebavan, may I ask if you have any comments or suggestions if anybody wants to take this up?

**Comment by sebavan** [comment] 2020-09-16 13:52
I cross posted here on the community: https://groups.google.com/a/tensorflow.org/g/tfjs/c/5VAnA7X0BRw/m/7iuomFqQBQAJ

Content is:

Basically, this part helps setting the custom shared context (should double check version and so on):

```const mygl = this.canvas.getContext('webgl2');
setWebGLContext(2, mygl as any);
await tf.setBackend('webgl');```

This (Hackish one) ensures the restored state after I am done with my own work in the canvas (would be great as a restore helper):

```
const gpgpu = (tf.backend() as any).gpgpu;
const gl = this.engine._gl;
if (gpgpu.vertexAttrsAreBound) {
    this.engine.enableScissor();
    gl.useProgram(gpgpu.program);
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, gpgpu.indexBuffer);
    gpgpu_util.bindVertexProgramAttributeStreams(gl, false, gpgpu.program, gpgpu.vertexBuffer);
}
```

And this helps me sharing output internal tensor textures with my app (would also be great as a simpler helper):

```
const output = resize(inputTensor);
const backend = tf.backend() as unknown as tfgl.MathBackendWebGL;
const dataId = (output as any).dataId
const textureData = backend.texData.get(dataId);
const texture = textureData.texture;
```

The only missing part would be able to share inputs data by having a kind of fromTexture equivalent to fromPixels.

Any thoughts, concerns ?

**Comment by pmer** [comment] 2020-09-20 23:25
Nice! That's cool, I think we came to the same solution. :)

The only other thing I did when extracting tensors from TFJS was to `(backend as any).decode()` them because the data on them was encoded in a TFJS internal format. With `.decode()` they are left in a "square-ish" texture (the dimensions of which you can get with `tex_util.getDenseTexShape()`) that I'm able to copy into a texture of my own preferred width/height. Once you're done with the decoded texture, you call `backend.disposeData()` on it. I couldn't figure out how to use encoded texture data, so that's why I took this route.

For a `fromTensor()` function, I did something like this:

```typescript
const myShape = [myHeight, myWidth, myNumChannels];
const myTexture: WebGLTexture = ...;

// Create a temporary TensorInfo that I will free in a little bit.
const tempTensor = backend.makeTensorInfo(texShape, 'float32');
backend.texData.get(tempTensor.dataId).usage = TextureUsage.PIXELS;
(backend as any).uploadToGPU(tempTensor.dataId);

// (Hack) Put my data in the TensorInfo.
const originalTexture: WebGLTexture =
    backend.texData.get(tempTensor.dataId).texture;
backend.texData.get(tempTensor.dataId).texture = myTexture;

// Create a new TensorInfo containing my data in an encoded format.
const program = new FromPixelsPackedProgram(outShape);
const res: tf.TensorInfo =
    backend.runWebGLProgram(program, [tempTensor], 'float32');

// Free the temporary TensorInfo.
backend.texData.get(tempTensor.dataId).texture = originalTexture;
backend.disposeData(tempTensor.dataId);

// Wrap the encoded data in a tf.Tensor.
const tensor: tf.Tensor = tf.engine().makeTensorFromDataId(
    res.dataId,
    res.shape,
    res.dtype,
    backend
);
```

The logic came mostly from `tf.browser.fromPixels()`.

Once I got these insert texture & extract texture functions working, the speed of running TFJS functions every frame in my app became a non-issue. I was always getting 60 FPS! (And getting 144 FPS on 144 Hz displays.)

**Comment by sebavan** [comment] 2020-09-20 23:27
Thanks a lot for the nice trick with .decode() as I was currently struggling with an uggly way of solving it :-)

**Comment by pmer** [comment] 2020-09-20 23:33
I know what you mean—my first attempt was also ugly. This `.decode()` approach was my second attempt. :)

**Comment by pmer** [comment] 2020-09-20 23:38
It'd be really great if Tensorflow.js could fix this, since it sounds like it's not that much work. Without something like this it really limits the usefulness for a whole class of applications, which is unfortunate because Tensorflow.js is otherwise amazing.

**Comment by rthadur** [comment] 2020-09-21 17:55
cc @pyu10055

**Comment by sebavan** [comment] 2020-10-02 13:11
@pmer, about the texture sharing, how did you access FromPixelsPackedProgram and TextureUsage without creating a custom TF build ? I can not find them exported on the current version ?

Just wondering if I am not missing the obvious :-)

**Comment by sebavan** [comment] 2020-10-02 13:51
Mainly because I am currently doing it as such:
```
import { FromPixelsPackedProgram } from '@tensorflow/tfjs-backend-webgl/dist/kernels/FromPixels_utils/from_pixels_packed_gpu'
```

But I am, a bit worried about upgrade and back compat but if #3937 goes in, it will solve all of it.

**Comment by pmer** [comment] 2020-10-02 20:01
I have that exact same line of code, character for character! :) We are lucky that it works without a custom build.

And I'm worried about that upgrades, too. Having texture insertion & deletion is a must-have feature for me (my app will, for its purposes, not work without this), so I am prepared to forego upgrading to any new version of TFJS that would break what we have here. Not a good solution, I know. :)

**Comment by pmer** [comment] 2020-10-02 20:08
I cannot do a custom build IIRC because TFJS is tightly coupled to specific versions of TypeScript, and will not compile with an older or newer version of TypeScript. But my program uses a different version of TypeScript than what TFJS uses, so to do a custom build I'd have to have two versions of TypeScript at once and do two different build processes, which is too complicated for me.

**Comment by sebavan** [comment] 2020-10-02 20:24
Ohhh yup the line works for me, but digging into customs makes me scared on update, hence the custom build but I guess I ll stick with it :-)

**Comment by yuccai** [comment] 2021-01-18 17:22
Hi, I wonder where the current state of tfjs is when it comes to set a custom webgl context.

I'm using :
```
    "@tensorflow/tfjs": "~2.8.4",
    "@tensorflow/tfjs-backend-webgl": "~2.8.4"
```

I want to read output webgl texture of tensorflow js webgl backend in a 3d rendering context like this way : 
``` javascript
  const my3dTexture = new Texture(...);
  const output = model.predict();
  const { texture: tfjsWebGLTexture } = tf.backend().texData.get(output.dataId);
  my3dTexture._texture._webGLTexture = tfjsWebGLTexture;
  console.log(my3dTexture.readPixels());
```
The `my3dTexture.readPixels()` function acts like `output.dataSync()` but it tries to read the data from my 3d rendering context. This piece of code throws the following error : `WebGL: INVALID_OPERATION: framebufferTexture2D: object does not belong to this context`. This is the reason why I want to use the same context.

I tried different solutions based on this thread but I encounter different errors :
  - First try, change the gl context
   ```javascript
import * as tf from "@tensorflow/tfjs";
import { setWebGLContext } from "@tensorflow/tfjs-backend-webgl";

const gl = canvas.getContext("webgl2");
setWebGLContext(2, gl);
await tf.setBackend("webgl");
gl.enable(gl.SCISSOR_TEST);
gl.scissor(0, 0, canvas.width, canvas.height);
 ```
 In this case, the gl context of tfjs is not equal to my 3d context : `gl === tf.backend().gpgpu.gl` is false so the main error is still thrown.
 I tried adding `tf.backend().gpgpu.gl = gl;` but in this case, errors are thrown from tfjs side (`object does not belong to this context`)
   - Second try, create new backend
```javascript
import * as tf from "@tensorflow/tfjs";
import { GPGPUContext, MathBackendWebGL } from "@tensorflow/tfjs-backend-webgl";

  const gl = canvas.getContext("webgl2");
  const gpgpu = new GPGPUContext(gl);
  tf.registerBackend("custom-webgl", () => new MathBackendWebGL(gpgpu));
  await tf.setBackend("custom-webgl");
 ```
 In this case, tfjs context and my 3d context are the same : `gl === tf.backend().gpgpu.gl` is true
 But a basic tensor operation like `tf.square(4)` throws the following error : `Error running Square: Neither modular kernel nor forward func passed`.

As a recap, what I need is to be able to directly use a tfjs webgl texture (generated in the tfjs context) in an other WebGL context. I tried two different ways to set the same context but it fails. Any thoughts ?

**Comment by pmer** [comment] 2021-02-01 21:22
My apologies, butler, but I think this issue there is still an interesting in waiting to hear more.

**Comment by danbri** [comment] 2021-11-24 22:02
Any update on this? I want to be able to do webgl things with tfjs webgl-backed vectors and matrices, I found https://observablehq.com/@dsmilkov/using-custom-webgl-context and this thread, but it isn't clear if there's a stable way of doing so.

**Comment by danbri** [comment] 2021-11-25 16:02
I made a start updating that old example to run in 2021. 

https://observablehq.com/@mazeballs/using-custom-webgl-context

I don't understand everything yet so I just updated the API calls which moved around a bit in the tf modules...

**Comment by pyu10055** [comment] 2021-11-30 17:23
@danbri you can access the tensor texture by doing following:
```
const tensor = tf.ones([100,100]);
const tensor2 = tf.ones([100,100));
const tensor3 = tf.add(tensor, tensor2);
const tensorInfo = tf.backend().texData.get(tensor3.dataId);
```
The tensorInfo contains the WebGL texture and the texture shape information.
But since it is internal storage format, it is likely packed (using all color channels), for example for the above `tensor3`, it looks like this:

```
{shape: Array(2), dtype: 'float32', values: undefined, usage: null, refCount: 1, …}
dtype: "float32"
isPacked: true
refCount: 1
shape: (2) [100, 100]
texShape: (2) [100, 100]
texture: WebGLTexture {}
usage: null
values: undefined
[[Prototype]]: Object
```
To get a unpacked texture you can do this:
```
const unpackedTensor3 = tf.backend().unpackTensor(tensor3);
const unPackedTensorInfo = tf.backend().texData.get(unpackedTensor3.dataId);
```
And its tensorInfo looks like this:
```
{
    "shape": [
        100,
        100
    ],
    "dtype": "float32",
    "usage": null,
    "refCount": 1,
    "texShape": [
        100,
        100
    ],
    "texture": {}
}
```
You can access the texture by doing `unPackedTensorInfo.texture`.

**Comment by danbri** [comment] 2021-11-30 20:36
Thank you - super useful :)

Is there documentation for unpackTensor somewhere? i tried googling but
couldn't find.

Also - can you confirm that the tensor data remains on gpu when unpacked?
can the process be reversed if other code updates the unpacked tensor?

**Comment by pyu10055** [comment] 2021-11-30 22:59
@danbri The `unpackTensor` method is an internal API for webgl backend, it is available to be used, but we are trying to create a more user friendly API across GPU backends.
There is also `packTensor` api, you find the details [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/src/backend_webgl.ts#L712).

But be aware that, the pack and unpack tensor methods will create a new tensor, your original tensor will be still be there, if you question is to feed those tensors back to be used by the models again.

**Comment by danbri** [comment] 2021-12-07 12:39
Thanks for the detailed pointers!

You might find this interesting: https://twitter.com/ankurhandos/status/1431130561804865538?s=20 - it seems similar to my usecase, except the simulation/environment is also GPU-backed whereas I'm looking to focus on Box2D/Liquidfun initially (so therefore wasm, and shared data in wasm is on hold for security reasons still afaik).

**Comment by gaikwadrahul8** [comment] 2023-10-11 12:42
Hi, @nkreeger

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:27
Hi, @nkreeger 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:27 UTC
Labels: type:others, stat:awaiting response, comp:backend-webgl
