### ISSUE TITLE
[wasm] Optimization of tf.browser.fromPixels.

### ISSUE THREAD

**Issue by kylemcdonald** [tensorflow/tfjs#4227] opened 2020-11-13 02:43 UTC
I noticed that [tf.browser.fromPixels](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/browser.ts#L145-L151) can be very slow when it spends time in this loop:

```js
    const numPixels = width * height;
    values = new Int32Array(numPixels * numChannels);
    for (let i = 0; i < numPixels; i++) {
      for (let channel = 0; channel < numChannels; ++channel) {
        values[i * numChannels + channel] = vals[i * 4 + channel];
      }
    }
```

(Also reported by #4218)

I was able to get significantly better performance with my application by calling this function instead:

```js
function convertArrayBufferRGBAToUInt8RGB(buffer) {
  // create view of ArrayBuffer
  const x = new Uint8Array(buffer);
  const n = x.length;
  let i = 0;
  let j = 0;
  // loop through all pixels and shift them over to remove alpha
  while (i < n) {
    x[j] = x[i]; i++; j++;
    x[j] = x[i]; i++; j++;
    x[j] = x[i]; i++; j++;
    i++;
  }
  // return a subset of the original
  return x.slice(0, j);
}
```

And then calling it like sort of like this:

```js
const fromPixels2DContext = document.createElement('canvas').getContext('2d'); // only call this once
function fromPixelsFast(inputElt, width, height) {
  return tf.tidy(() => {
    fromPixels2DContext.canvas.width = width;
    fromPixels2DContext.canvas.height = height;
    fromPixels2DContext.drawImage(inputElt, 0, 0, width, height);
    const buffer = fromPixels2DContext.getImageData(0, 0, width, height).data.buffer;
    const UInt8RGB = convertArrayBufferRGBAToUInt8RGB(inputArray);
    return tf.tensor3d(UInt8RGB, [height, width, 3]);
  });
}
```

I think the thing that makes it faster is connected to:

1. Using Uint8Array instead of UInt32Array (small effect)
2. The unrolled loop is better optimized by the browser. (medium effect)
3. It is more efficient to shuffle data in one array than between two arrays due to cache effects. (big effect)

(But I have not done rigorous testing)

It might even be possible to get a little more speed from `.subarray` instead of `.slice` to avoid making the copy.

A complete example using this function with blazeface and a custom model on a webcam inside a webworker is available [in this repo](https://github.com/kylemcdonald/tfjs-expression-recognition/tree/webworker).

**Comment by wingman-jr-addon** [comment] 2020-11-16 02:01
I'm looking at the other report over in #4218 and the nature of that bug along with an examination of the source lead me to believe this path is primarily triggered for WASM, right? The other backends register their own implementations, I think. Can you confirm?

**Comment by vladmandic** [comment] 2020-11-16 11:51
@kylemcdonald This is very much inline in what I'm suggesting in #4128 

Two suggestions that can enhance your code:

Try OffscreenCanvas before DOM, it's slightly faster and works inside web workers. But it's not supported on Firefox yet.
```js
const fromPixelsCanvas (typeof OffscreenCanvas !== 'undefined') ? new OffscreenCanvas(width, height) : document.createElement('canvas');
```

Try GL `readPixels` method first as its quite a bit faster.  
And fallback to 2D context and `getImageData` if cannot get GL context.  
```js
const fromPixelsGLContext  = fromPixelsCanvas.getContext('webgl');
const buffer = new Uint8Array(canvas.width * canvas.height * 4);
gl.readPixels(0, 0, fromPixelsCanvas.width, fromPixelsCanvas.height, gl.RGBA, gl.UNSIGNED_BYTE, buffer);
```
But...one issue here would be that `getImageData` returns data starting top/left and `readPixels` returns data starting bottom/left, so processing loop needs to be inverted.

Of course, best method would be to implement `fromPixels` directly in WASM backend just like it's implemented in WebGL backend.

**Comment by kylemcdonald** [comment] 2020-11-16 21:26
@vladmandic could you explain more what you mean by "best method would be to implement `fromPixels` directly in WASM backend"? I'm new to WASM and I don't understand what this means. Are you talking about a different way of getting the pixels that is neither `readPixels` nor `getImageData`? Or are you just saying where the code should be located?

@wingman-jr-addon I can confirm that this is designed to target the WASM backend. This is most relevant in the situation where WebGL is unavailable.

**Comment by vladmandic** [comment] 2020-11-16 21:34
@kylemcdonald - yes, that's exactly what I'm saying - it's possible for a WASM module to work directly with canvas, so it could implement it's own function to get pixel data from canvas instead of relying on either GL `readPixels()` or 2D `getImageData()` which are both relatively slow, especially since additional postprocessing is needed to drop alpha channel.

But in the lack of such native implementation, any gain over existing method is welcome!

**Comment by annxingyuan** [comment] 2021-02-16 21:24
Thanks for reporting this @kylemcdonald ! I'm going to close this as a duplicate of https://github.com/tensorflow/tfjs/issues/4218 - which was created 1 day earlier :)

Thanks for the greaat discussion on this issue - this will be a really helpful reference for us!

**Closed by annxingyuan** 2021-02-16 21:24 UTC
Labels: type:others
