### ISSUE TITLE
Universal sentence encoder misbehaves on Android device

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#1619] opened 2019-05-28 17:59 UTC
#### TensorFlow.js version
1.1.2

#### Browser version
74.0.3729.157 (Android)
and
Version 74.0.3729.169 (Official Build) (64-bit)

#### Describe the problem or feature request
The sample program at https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder#usage works fine on my laptop but on my Nexus 5 it produces the same encoding for two different sentences.

On Android it produces
Tensor
  dtype: float32
  rank: 2
  shape: [2,512]
  values:
    [[0.0576198, -0.0094403, 0.0067326, ..., 0.0044462, -0.0386527, 0.0576173],
     [0.0576198, -0.0094403, 0.0067326, ..., 0.0044462, -0.0386527, 0.0576173]]

while all is well on my laptop.

Tensor
  dtype: float32
  rank: 2
  shape: [2,512]
  values:
    [[-0.0415073, 0.0273511 , -0.0006131, ..., 0.0477688 , -0.0659466, -0.0033119],
     [0.0416779 , -0.0223678, -0.0476077, ..., -0.0493374, 0.0493427 , 0.0491257 ]]

#### Code to reproduce the bug / link to feature request

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/universal-sentence-encoder"></script>
<script>
// Load the model.
use.load().then(model => {
  // Embed an array of sentences.
  const sentences = [
    'Hello.',
    'How are you?'
  ];
  model.embed(sentences).then(embeddings => {
    // `embeddings` is a 2D tensor consisting of the 512-dimensional embeddings for each sentence.
    // So in this example `embeddings` has the shape [2, 512].
    embeddings.print(true /* verbose */);
  });
});
</script>

**Comment by dsmilkov** [comment] 2019-05-29 01:10
@annxingyuan curious if we can reproduce this on a Pixel phone?

**Comment by annxingyuan** [comment] 2019-05-30 12:48
@dsmilkov Confirmed this happens on a Pixel phone.

**Comment by annxingyuan** [comment] 2019-05-30 14:07
Values are correct in DEBUG mode.

**Comment by dsmilkov** [comment] 2019-05-30 16:59
Hmm, and debug mode downloads each intermediate value to the CPU... Can you find at which point (which layer) the values start to diverge significantly between the laptop and the Pixel phone?

**Comment by dsmilkov** [comment] 2019-05-30 17:04
Hypothesis: Since debug mode downloads all intermediate values to CPU, there is a higher chance they get re-uploaded as uniforms instead of textures, or the following operation gets forwarded the the CPU backend.

When in debug mode can you disable both uniform uploads and cpu forwarding?

**Comment by ToonTalk** [comment] 2019-06-16 13:27
Is this fixed in 1.2.1? A quick test seems to indicate it is resolved.

**Comment by annxingyuan** [comment] 2019-06-17 12:52
Hmmmm it looks like it is... I'll figure out why... closing this issue in the meantime :)

**Closed by annxingyuan** 2019-06-17 12:52 UTC
Labels: comp:models

**Comment by annxingyuan** [comment] 2019-06-17 13:44
Looks like https://github.com/tensorflow/tfjs-core/pull/1777 accidentally fixed this... I think that means either our CPU-side encoder or packing shader behaved differently on Android.
