### ISSUE TITLE
content in @returns annotation in jsdoc is not displayed in js.tensorflow.org

### ISSUE THREAD

**Issue by bileschi** [tensorflow/tfjs#648] opened 2018-08-28 18:18 UTC
#### Describe the problem or feature request
In JSDoc like the following 
```
/**
 * Gram-Schmidt orthogonalization.
 *
 * @param xs The vectors to be orthogonalized, in one of the two following
 *   formats:
 *   - An Array of `Tensor1D`.
 *   - A `Tensor2D`, i.e., a matrix, in which case the vectors are the rows
 *     of `xs`.
 *   In each case, all the vectors must have the same length and the length
 *   must be greater than or equal to the number of vectors.
 * @returns The orthogonalized and normalized vectors or matrix.
 *   Orthogonalization means that the vectors or the rows of the matrix
 *   are orthogonal (zero inner products). Normalization means that each
 *   vector or each row of the matrix has an L2 norm that equals `1`.
 */
/** @doc {heading: 'Operations', subheading: 'Linear Algebra'} */
```
The content of the `@returns` annotation is consumed and not displayed in the website.  The solution is either to remove the annotation within the jsdoc, or to modify the website to display the content.

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:22
Hi, @bileschi 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:44
Hi, @bileschi 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:44 UTC
Labels: type:docs, comp:website, stat:awaiting response

**Comment by AyushWankhede705** [comment] 2025-04-18 21:50
Hello Everyone I'm Ayush Wankhede. currently aI'm looking forward to gain some short of experience in Programming or mostly likely in Management. I'm free to volunteer anything need. Please let me know if I good help. I'm good communication and managing people, Elc...
