### ISSUE TITLE
Implement sparse metrics in layers metrics

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#26] opened 2018-03-27 17:48 UTC
Including
- ~~sparseCategoricalAccuracy~~
- ~~sparseCategoricalCrossentropy~~
- sparseTopKCategoricalAccuracy

**Comment by caisq** [comment] 2019-08-07 15:56
Closing the PR. This is done.

**Comment by caisq** [comment] 2019-08-07 15:57
Reopening the issue. `sparseTopKCategoricalAccuracy` is still outstanding. It's dependent on https://github.com/tensorflow/tfjs-core/pull/1734/files

**Comment by aralroca** [comment] 2021-03-29 17:12
@caisq how can I use the `fromLogits` and `reduction` in `sparseCategoricalCrossentropy`?

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:30
Hi, @caisq 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:47
Hi, @caisq 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:47 UTC
Labels: type:feature, comp:layers, P2, stat:awaiting response
