### ISSUE TITLE
Allocate nearest largest texture in WebGL texture manager

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#982] opened 2018-12-10 20:06 UTC
Right now the WebGL texture manager reuses textures whose shape matches exactly, however to increase texture reuse, we should relax this constraint and reuse parts of  existing textures.

This means that the texture manager should return the nearest largest texture that can fit the requested size.

**Comment by dsmilkov** [comment] 2018-12-10 20:06
cc @nsthorat @annxingyuan

**Comment by rthadur** [comment] 2021-09-03 17:42
@ahmedsabie  is it possible to verify this ? Thank you

**Comment by gaikwadrahul8** [comment] 2023-10-11 13:51
Hi, @dsmilkov 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:36
Hi, @dsmilkov 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:36 UTC
Labels: comp:core, type:performance, stat:awaiting response
