### ISSUE TITLE
Code samples for start training a model from saved check point..

### ISSUE THREAD

**Issue by rbamila** [tensorflow/tfjs#1136] opened 2019-01-24 05:47 UTC
Try to apply the method described in following comment. But couldn't able to figure it out how to do it exactly. Just loading a model, compile and and start training will do it?
https://github.com/tensorflow/tfjs/issues/481#issuecomment-406525304
@FrozenKiwi

**Comment by rthadur** [comment] 2019-01-24 18:32
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tfjs/issues/new). Please provide all the information it asks. Thank you.

**Comment by BenjaminWegener** [comment] 2019-02-05 15:16
@rbamila wants to know, how the user in the comment manages the "flush" as he calls it.

> Some things I tried:
> Calling GC() in the epoch callback did not resolve the issue.
> Running multiple iterations of model.fit, with a GC between iterations did not resolve the issue
> Running multiple iterations of model.fit by saving the model, releasing it, calling GC(), calling
> tf.disposeVariables(), reloading the model, and continuing training, still did not fix the issue.
> All of the above, plus calling tf.setBackend(tf.getBackend()) FINALLY FIXED IT!

**Comment by rthadur** [comment] 2019-02-06 21:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2019-02-06 21:52 UTC
Labels: stat:awaiting response
