### ISSUE TITLE
feature request : extra information to model

### ISSUE THREAD

**Issue by unrealwill** [tensorflow/tfjs#1181] opened 2019-02-01 12:57 UTC
#### TensorFlow.js version
NA
#### Browser version
NA
#### Describe the problem or feature request
Hello,

I'd like to have a standardized way to save extra_information inside a model in python and have it passed all the way to tensorflowjs.

The use case for example is when I have "Valid" Conv1D but None as time dimension, I need to know what the minimal size to pass as input that won't result in an error.

An other use case, is specifying a License/ author for a model.

But simply a way of passing a dictionary as json inside a field would suffice.

#### Code to reproduce the bug / link to feature request
In python : 
```
model.extraInfo = {"license":"MIT", "minInputShape":(None,10,None),"author":"unrealwill"}
tfjs.converters.save_keras_model(model, url)
```

and then accessing it in javascript using : 
```
tf.loadmodel( url ) .then( function(model)
{ 
console.log(model.extraInfo.license) ; 
console.log(model.extraInfo.minInputShqpe) ; 
console.log(model.extraInfo.author) ; 
}
```

Thanks

**Comment by davidsoergel** [comment] 2019-02-04 22:57
Please see #762 for a prior discussion of this.

**Comment by dsmilkov** [comment] 2019-02-04 22:58
Thanks. Closing this as a duplicate of #762

**Closed by dsmilkov** 2019-02-04 22:58 UTC
Labels: type:feature
