### ISSUE TITLE
Are the left and right labels switched in the posenet example?

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#493] opened 2018-07-05 14:04 UTC
The page https://github.com/tensorflow/tfjs-models/tree/master/posenet shows that the left eye/ear/etc have larger x coordinates than the right eye/ear/etc. This is true of the code and sample pose listed on that page.

I understand that the y coordinate increases as one goes down but why are the x coordinates as they are? Is it that the camera is acting like a mirror and reversing left and right?

**Comment by bileschi** [comment] 2018-07-26 12:32
Wasn't involved in the posenet work , but it's probably a semantics thing.  We should take it as "the person's left eye" not "left as we look at the person".

```
    {
      "position": {
        "y": 71.10383605957,
        "x": 253.54365539551
      },
      "part": "leftEye",
      "score": 0.98781454563141
    },
    {
      "position": {
        "y": 71.839515686035,
        "x": 246.00454711914
      },
      "part": "rightEye",
      "score": 0.99528175592422
    },
```

**Comment by nsthorat** [comment] 2018-07-26 13:20
@oveddan to confirm

**Comment by ToonTalk** [comment] 2018-07-26 13:35
I just experimented where only left eye was visible in the camera and it reported with 99% confidence that my right eye was visible.

**Comment by nsthorat** [comment] 2018-10-26 19:07
One other thing to look at is the `flipHorizontal` bit, which may be mirroring your input.

**Comment by ToonTalk** [comment] 2018-10-27 09:42
Thanks. `flipHorizontal `was indeed true and explains the coordinates. But it doesn't explain the labels. Using https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html I caught a pose where my left eye was off camera and the pose was

1:
part: "leftEye"
position: {x: 45.92205166404222, y: 235.28564273074457}
score: 0.9963957667350769
__proto__: Object
2:
part: "rightEye"
position: {x: -22.933025426105644, y: 241.21025884794497}
score: 0.8927254676818848

If the rightEye refers to my right eye then it should have the positive coordinate and the left the negative coordinate since it is my left eye that is off camera. I understand now that the coordinates are flipped but should the left/right labels be also?

**Comment by rthadur** [comment] 2018-11-28 22:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2018-11-28 22:02 UTC
Labels: comp:models, question

**Comment by oveddan** [comment] 2019-01-28 17:37
Confirmed they are switched when `flipHorizontal` is set to true. We are running into the same issue with BodyPix.   @nsthorat lets reopen this.
