### ISSUE TITLE
Error: Based on the provided shape, [256,108], and dtype float32, the tensor should have 27648 values but has 434

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tfjs#805] opened 2018-10-18 14:36 UTC
#### TensorFlow.js version
0.13.0
#### Browser version
Version 69.0.3497.100 - 64 bit
#### Describe the problem or feature request
I have trained the translation LSTM example [here](https://github.com/tensorflow/tfjs-examples/blob/master/translation/python/translation.py) with default values and the parallel corpus provided by Anki (fr-en).
I get this error
```

Error: Based on the provided shape, [256,108], and dtype float32, the tensor should have 27648 values but has 434
    at assert (tf-core.esm.js:17)
    at new e (tf-core.esm.js:17)
    at Function.e.make (tf-core.esm.js:17)
    at tensor (tf-core.esm.js:17)
    at o (tf-core.esm.js:17)
    at Object.decodeWeights (tf-core.esm.js:17)
    at tf-layers.esm.js:17
    at tf-layers.esm.js:17
    at Object.next (tf-layers.esm.js:17)
    at o (tf-layers.esm.js:17)
loadHostedPretrainedModel @ loader.js:50
async function (async)
loadHostedPretrainedModel @ loader.js:42
init @ index.js:41
button.addEventListener @ index.js:206
14:57:42.394 ui.js:19 Loading pretrained model failed.
```

when loading the model in the tensorflow-js example [here](https://github.com/tensorflow/tfjs-examples/tree/master/translation)
#### Code to reproduce the bug / link to feature request
I have put model.json [here](https://gist.github.com/loretoparisi/17759310ed1480ebb8efcb6d99f49e62) the metadata.json [here](https://gist.github.com/loretoparisi/ac5e00a397bd3bfb07f8f60d987c1d94) and you can download the model shard from here

[group1-shard1of1.zip](https://github.com/tensorflow/tfjs/files/2492292/group1-shard1of1.zip)

**Comment by loretoparisi** [comment] 2018-10-19 08:32
@caisq I was able to make it working in Node.js and I prepared a fully fledged example for Node.js, hopefully this will help in the PR I have sent - https://github.com/tensorflow/tfjs-examples/pull/157

Regarding the browser, could it be due to this comment in `serve.sh` script:

```sh
# prevents it from serving the pretrained models; see
# https://github.com/parcel-bundler/parcel/issues/1098.  Once that issue is
# resolved, a single Parcel server will be sufficient.
```

Thank you.

**Comment by caisq** [comment] 2018-10-19 14:50
@loretoparisi Yeah, i think that is a possibility.

**Comment by rthadur** [comment] 2018-11-16 22:01
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2018-11-16 22:01 UTC
Labels: question

**Comment by nebrelbug** [comment] 2019-01-18 03:13
I ran into this issue when using the `serve` NPM/Yarn package. It seems to not work well with TensorflowJS. When I used Firebase Serve, it worked great.

**Comment by AxelWolf** [comment] 2019-04-27 10:50
We can reproduce this error msg in a browser (Chrome) environment:

"Uncaught (in promise) Error: Based on the provided shape, [1280], the tensor should have 1280 values but has 1279"

In our setup, the error occurs up after making small changes to a model (adding a class to the final classification layer), retraining and exporting. When reloading the page that imports the model, the browser still uses the cached model.json and shards. Solution is to clear the browser cache and reload the page.
