### ISSUE TITLE
How to build tfjs locally ?

### ISSUE THREAD

**Issue by xlpiao** [tensorflow/tfjs#4751] opened 2021-02-26 04:26 UTC
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04

**Describe the problem**
- I modified some files under directory of `tfjs` and `tfjs-backend-webgl` and I wanna build it. Is there a script to build  `tfjs`  ?
- Do I have to add a new webpack and add some rules there? 

Thanks

**Comment by vladmandic** [comment] 2021-02-26 12:32
not an official way, but my quick hack:
```bash
git clone --depth 1 https://github.com/tensorflow/tfjs
cd tfjs
find . -maxdepth 1 -type d | while read d; do
  pushd $PWD
  cd $d
  if [ -f package.json ]; then
    yarn install --ignore-optional --ignore-engines
  fi
  popd
done

cd ./tfjs
yarn run build-deps
yarn run build
yarn run build-npm

cd ../tfjs-node
yarn run build-npm

cd ../tfjs-node-gpu
./prep-gpu.sh
yarn run build-npm

cd ../tfjs-backend-webgpu
yarn run build-npm
```

**Comment by xlpiao** [comment] 2021-03-02 03:05
@vladmandic  Thanks for your reply. I followed above commands. Error happens when  `yarn  run build-deps` is executed. I think this is something related to node or tsc, but I'm not quite sure. By the way, I am building tfjs-v2.8.4 tag version.

--- error message: 
```bash
/home/xlpiao/tfjs/tfjs:$ yarn run build-deps

yarn run v1.22.5
$ yarn build-core && yarn build-layers && yarn build-converter && yarn build-data && yarn build-backend-cpu && yarn build-backend-webgl
$ cd ../tfjs-core && yarn && yarn build
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node ./scripts/enumerate-tests.js && tsc && yarn bundle
../../node_modules/@types/eslint/index.d.ts:260:41 - error TS2694: Namespace '"/home/xlpiao/tfjs/tfjs-core/node_modules/@types/estree/index"' has no exported member 'ChainExpression'.

260         ChainExpression?: (node: ESTree.ChainExpression & NodeParentExtension) => void;
                                            ~~~~~~~~~~~~~~~

../../node_modules/@types/eslint/index.d.ts:283:42 - error TS2694: Namespace '"/home/xlpiao/tfjs/tfjs-core/node_modules/@types/estree/index"' has no exported member 'ImportExpression'.

283         ImportExpression?: (node: ESTree.ImportExpression & NodeParentExtension) => void;
                                             ~~~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jinjingforever** [comment] 2021-03-11 02:07
Hi Xianglan,

I checked out tfjs-v2.8.4 but didn't see any issues when running "yarn build-deps" from tfjs/tjfs. It is a little bit strange to see that the error is in `tfjs-core/node_modules/@types/eslint`, because I don't actually see it on my machine. Here is everything under `tfjs-core/node_modules/@types`:

```
color-name
estree
jasmine
long
minimatch
node
node-fetch
offscreencanvas
resolve
seedrandom
webgl-ext
```

Is it possible that this might be caused by some new code you wrote locally? 

Thanks!

**Comment by xlpiao** [comment] 2021-03-11 14:55
@jinglescode Thanks for you reply. I put `tfjs` under some other project and that might be the reason for the building error. Since I moved tfjs out of that project directory, above commands works well. Issue resolved.

**Comment by rthadur** [comment] 2021-03-11 16:43
Thank you for confirming , closing this issue.

**Closed by rthadur** 2021-03-11 16:43 UTC
Labels: type:build/install
