### ISSUE TITLE
tfjs-examples: Add tensorboard logging option to examples involving tfjs-node-based training

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1299] opened 2019-02-27 18:34 UTC
#### TensorFlow.js version
tfjs-node / tfjs-node-gpu 0.3.1

**Comment by gaikwadrahul8** [comment] 2023-08-30 15:10
Hi, @caisq 

Apologize for the delayed response and I see we have updated our official documentation w.r.t tfjs-examples, it seems like we have added tensorboard logging option to examples invloving tfjs-node-based training, If I'm not wrong

Please refer this [official documentation ](https://github.com/tensorflow/tfjs-examples/tree/master/simple-object-detection#monitoring-model-training-with-tensorboard)

I see tfjs-examples [fashion-mnist-vae](https://github.com/tensorflow/tfjs-examples/blob/master/fashion-mnist-vae), [snake-dqn](https://github.com/tensorflow/tfjs-examples/blob/master/snake-dqn), [simple-object-detection](https://github.com/tensorflow/tfjs-examples/blob/master/simple-object-detection) where tensorboard logging option used. Thank you!

**Comment by gaikwadrahul8** [comment] 2023-10-11 13:00
Hi, @caisq 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:32
Hi, @caisq 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:32 UTC
Labels: type:feature, comp:examples, stat:awaiting response
