### ISSUE TITLE
uncaught (in promise) TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kallols** [tensorflow/tfjs#175] opened 2018-04-11 05:36 UTC
I have imported a pre-trained keras model through a json file but while running the program I got the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at h (tfjs@latest:1)
    at t.predict (tfjs@latest:1)
    at t.predict (tfjs@latest:1)
    at Object.success (sample.js:19)
h @ tfjs@latest:1
t.predict @ tfjs@latest:1
t.predict @ tfjs@latest:1
(anonymous) @ sample.js:19
async function (async)
(anonymous) @ sample.js:14
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
```

This is my java script code below;

```
var a = (form.input1.value);
    $.post('http://127.0.0.1:5000/',{"text":a}, async function(response)
    {
        //console.log('response: ',response);
        var arr=response;
        const model= await tf.loadModel('./json/model.json');
        console.log(model.predict(arr))

    });
```

Please let me know how to solve this issue.

**Comment by dsmilkov** [comment] 2018-04-11 13:28
Hi @kallols 

Note that model.predict() takes a `Tensor` ([api ref](https://js.tensorflow.org/api/0.8.0/#tf.Model.predict)), whereas I suspect `arr=response` gives you a regular js array? Can you try wrapping that in a Tensor using [tf.tensor](https://js.tensorflow.org/api/0.8.0/#tensor)

**Comment by dsmilkov** [comment] 2018-04-11 13:29
Duplicate of #166

**Closed by dsmilkov** 2018-04-11 13:29 UTC
