### ISSUE TITLE
Issue Raspberry install tfjs-node 3.7.0 , wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by franckOL** [tensorflow/tfjs#5173] opened 2021-06-04 13:46 UTC
When I install tfjs-node, and run it

```bash
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> const tf = require('@tensorflow/tfjs');
undefined
> require('@tensorflow/tfjs-node')
node-pre-gyp info This Node instance does not support builds for Node-API version 8
node-pre-gyp info This Node instance does not support builds for Node-API version 8
Uncaught:
Error: /home/pi/program/nanocptscenariorunner/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
>
```

When doing
```bash
npm rebuild @tensorflow/tfjs-node 
....
gyp verb node dev dir /home/pi/.cache/node-gyp/14.16.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
../binding/tfjs_backend.cc: In function ‘TFE_TensorHandle* tfnodejs::CreateTFE_TensorHandleFromStringArray(napi_env, int64_t*, uint32_t, TF_DataType, napi_value)’:
../binding/tfjs_backend.cc:196:64: error: ‘TF_TString’ was not declared in this scope
                                          array_length * sizeof(TF_TString)));
                                                                ^~~~~~~~~~
../binding/tfjs_backend.cc:198:15: error: ‘t’ was not declared in this scope
....
```

Nodejs: 14.13
Raspbian lite strech
Raspberry 3 armv7l ==> 32 bits

**Comment by pyu10055** [comment] 2021-06-07 18:18
@franckOL there is a mis-match between the binding (TF 2.4.1) and RPI TF binary (v1.4.0)
We will try to build a new RPI TF binary (2.4.1). TF have dropped official support for RPI (no new releases), If you have manually built before, please share your steps. thanks

**Comment by franckOL** [comment] 2021-06-08 07:33
In fact I understand than `npm rebuild @tensorflow/tfjs-node` is the rebuilding process, but as you see I have another issue on that (`TF_TString` unknown symbol)

**Comment by playground** [comment] 2021-06-29 13:54
@pyu10055 @franckOL I'm running into the same issue in Raspberry p3

I'm running tfjs-node v3.3.0 due to a regression bug with v3.7 as suggested by @pyu10055 https://github.com/tensorflow/tfjs/issues/5161#issuecomment-854972551,
has this been resolved for v3.7?

What to do to get it to run in RPi
```
> node index.js

node:internal/modules/cjs/loader:1167
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /server/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1167:18)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/server/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'ERR_DLOPEN_FAILED'
}

```

**Comment by franckOL** [comment] 2021-06-29 14:25
@playground As you see a PR is done to fix that, already merged, just waiting for release 3.7.x

**Comment by playground** [comment] 2021-06-29 15:33
Thanks @franckOL, I was also checking with @pyu10055 if the other regression bug has been addressed so I can run v3.7.x.

**Comment by playground** [comment] 2021-07-17 15:46
Any updates on this?

**Comment by rthadur** [comment] 2021-07-29 18:57
cc @mattsoulanille

**Comment by franckOL** [comment] 2021-08-02 12:27
Test today version 3.8.0 : always wrong ELF class: ELFCLASS64

**Comment by playground** [comment] 2021-08-02 12:43
V3.8.0 works for me on rpi4 and Nvidia NX but broke for Mac.

**Comment by franckOL** [comment] 2021-08-02 12:56
> V3.8.0 works for me on rpi4 and Nvidia NX but broke for Mac.

@playground dans rpi4 is 64 bits platform ?

**Comment by franckOL** [comment] 2021-08-02 12:58
> > V3.8.0 works for me on rpi4 and Nvidia NX but broke for Mac.
> 
> @playground dans rpi4 is 64 bits platform ?

oh yes ==> Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz
https://www.raspberrypi.org/products/raspberry-pi-4-model-b/specifications/

but rpi3 64 bit too
Quad Core 1.2GHz Broadcom BCM2837 64bit CPU

Try to clean everything and see.
I work on rapsbian lite.

**Comment by playground** [comment] 2021-08-02 14:02
@franckOL rpi4 running ubuntu 32bit and  NX 64bit, I'm using SavedModel.

**Comment by franckOL** [comment] 2021-08-02 16:20
Just try again, a clean env on raspberry 3 , raspbian : 
```
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> const tf = require('@tensorflow/tfjs')
undefined
> require('@tensorflow/tfjs-node')
node-pre-gyp info This Node instance does not support builds for Node-API version 8
node-pre-gyp info This Node instance does not support builds for Node-API version 8
Uncaught:
Error: /tmp/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by playground** [comment] 2021-08-02 17:13
@franckOL I'm running my app with  node v14.17.3 and in a docker container with node v16.3.0 and both loads up fine

```
platform  linux
Started on 3000
2021-08-02 13:09:39.283490: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: ./model
2021-08-02 13:09:40.358427: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
2021-08-02 13:09:40.358568: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: ./model
2021-08-02 13:09:44.264451: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-08-02 13:09:44.837456: W tensorflow/core/platform/profile_utils/cpu_utils.cc:118] Failed to find bogomips or clock in /proc/cpuinfo; cannot determine CPU frequency
2021-08-02 13:09:50.320029: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 153600 exceeds 10% of free system memory.
2021-08-02 13:09:50.321330: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 153600 exceeds 10% of free system memory.
2021-08-02 13:09:50.322138: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 153600 exceeds 10% of free system memory.
2021-08-02 13:09:50.330052: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 153600 exceeds 10% of free system memory.
2021-08-02 13:09:50.335342: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 153600 exceeds 10% of free system memory.
2021-08-02 13:09:50.622648: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: ./model
2021-08-02 13:09:53.412700: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 14129215 microseconds.
loading time:  ./model, 25695.750468969345
version:  { name: 'Demo model', version: '1.0.0' }
./public/images/image.png
predictions: 1 {
  detectedBox: [ '0.026', '0.328', '0.215', '0.538' ],
  detectedClass: 'hard-hat',
  detectedScore: '1.000'
}
time took:  19462.35897707939
```
```
FROM arm32v7/node:16.3.0

RUN apt-get update -y && apt-get install -y apt-utils && apt-get install fswebcam -y && apt-get install mpg123 -y && apt-get install vim -y

WORKDIR /server

COPY . /server
RUN npm install -g npm
RUN npm install

VOLUME /demo_model_mms_helper_shared_volume
EXPOSE 3000
CMD [ "npm", "start" ]
```

**Comment by rthadur** [comment] 2021-08-12 14:22
@franckOL could you please update if you are still facing same issue ?

**Comment by franckOL** [comment] 2021-08-12 14:26
> @franckOL could you please update if you are still facing same issue ?

I update my version nodejs form 14.17.1 to 14.17.3. And it is **OK**

**Comment by rthadur** [comment] 2021-08-12 14:57
Thank you , closing this issue .

**Closed by rthadur** 2021-08-12 14:57 UTC
Labels: comp:node.js, type:build/install

**Comment by mcmoe** [comment] 2022-08-22 00:19
I am facing the `ELFLCASS64` issue on the latest 3.19.0 release. I'm running on a Raspberry PI 4 arm7l (32bit) and Node.js v18.7.0. I attempted previous releases and all failed with the same error until I hit 3.13.0 which seems to be working fine.

For all releases > 3.1.13 I get the below:


package.json

```json
{
  "type": "module",
  "name": "tf",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@tensorflow/tfjs-node": "3.13.x"
  }
}
```

tf.js: `import '@tensorflow/tfjs-node';`

Running node tf.js results with the following error:

```js
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: xxx/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: wrong ELF class: ELFCLASS64
    at Module._extensions..node (node:internal/modules/cjs/loader:1204:18)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (xxx/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.7.0
```


Any ideas?

**Comment by KingCh1ll** [comment] 2023-06-18 15:54
I am still facing the issue. Downgrading NodeJs to v14 is not a solution to me. Does anybody know a good fix?
