### ISSUE TITLE
Universal Sentence Encoder Model runs very slow after embedding large datasets

### ISSUE THREAD

**Issue by fawazahmed0** [tensorflow/tfjs#3471] opened 2020-06-18 10:34 UTC
**TensorFlow.js version**
2.0.1

**Node Version**
12.18.0

**OS**
Windows 7

**Prerequisite:**
`yarn add @tensorflow/tfjs @tensorflow/tfjs-node @tensorflow-models/universal-sentence-encoder`

**Steps to Reproduce:**
1. Download and unzip [debug use model.zip](https://github.com/tensorflow/tfjs/files/4797975/debug.use.model.zip)
1.  Run `node checktime.js`  and note down the time taken to execute
1. Run `node embedlargedata.js`, this script will embed large amount of data using universal sentence encoder model (takes around 1 hr)
1. Run `node checktime.js` and note down the time taken to execute
You will observe that after embedding large amount of data, the universal sentence encoder model will run very slow even for small datasets.

**Comment by fawazahmed0** [comment] 2020-06-20 21:55
This seems to solve the issue:
`npm cache clean --force`
but I have to do it every time, after embedding large datasets, otherwise it will run very slow

**Comment by pyu10055** [comment] 2020-06-24 21:51
cc @annxingyuan I think there is a mem leak on the USE model based on the benchmark page.

**Comment by annxingyuan** [comment] 2020-06-25 13:35
@pyu10055 I think the issue is that on the benchmark page we get the USE output data as part of the `predict` function, which is unlike all our other models (so the benchmarking script's tensor cleanup mechanism fails to apply to the USE). I sent a fix here: https://github.com/tensorflow/tfjs/pull/3510

**Comment by rthadur** [comment] 2020-08-14 01:09
Fix has been merged, thank you all.

**Closed by rthadur** 2020-08-14 01:09 UTC
Labels: comp:models, stat:awaiting response, type:bug
