### ISSUE TITLE
How to get bounding box from custom trained model detection?

### ISSUE THREAD

**Issue by sundowatch** [tensorflow/tfjs#2816] opened 2020-03-04 01:10 UTC
Hi,

I've trained a custom model with one object, converted it into graph model and using on the browser. Here is my code:

```
        async function predict() {
            const model = await tf.loadGraphModel('./model/model.json');
            let img = document.getElementById('test');

            var example = tf.browser.fromPixels(img);
            example = example.expandDims(0);

            const output = await model.executeAsync(example);
            output.forEach(val=>{
                console.log(val);
            });
        }
```
It's giving these values:
```
t {kept: false, isDisposedInternal: false, shape: Array(3), dtype: "float32", size: 1200, …}
t {kept: false, isDisposedInternal: false, shape: Array(3), dtype: "float32", size: 600, …}
t {kept: false, isDisposedInternal: false, shape: Array(1), dtype: "float32", size: 1, …}
t {kept: false, isDisposedInternal: false, shape: Array(3), dtype: "float32", size: 600, …}
t {kept: false, isDisposedInternal: false, shape: Array(3), dtype: "float32", size: 1200, …}
t {kept: false, isDisposedInternal: false, shape: Array(5), dtype: "float32", size: 4915200, …}
t {kept: false, isDisposedInternal: false, shape: Array(2), dtype: "float32", size: 300, …}
t {kept: false, isDisposedInternal: false, shape: Array(2), dtype: "float32", size: 300, …}
```

How can I know is there any mathces/predictions on the image? And if is there, how can I get the bounding box of it?

The pretrained models have these options. But how can we do it on our own models?

**Comment by tafsiri** [comment] 2020-03-04 14:58
@sundowatch to get the data (an array) from a tensor (e.g. val) you call [`await val.data()`](https://js.tensorflow.org/api/latest/#tf.Tensor.data) or you can call [`val.dataSync()`](https://js.tensorflow.org/api/latest/#tf.Tensor.dataSync) without the await. That will give you a JavaScript array with whatever your model was trained to predict. Beyond that we can't really help with how to interpret that output.

If by chance this was a model you trained using AutoML, you can take a look at this package https://github.com/tensorflow/tfjs/tree/master/tfjs-automl documenting how to get output from those trained models.

**Comment by sundowatch** [comment] 2020-03-04 19:40
> @sundowatch to get the data (an array) from a tensor (e.g. val) you call [`await val.data()`](https://js.tensorflow.org/api/latest/#tf.Tensor.data) or you can call [`val.dataSync()`](https://js.tensorflow.org/api/latest/#tf.Tensor.dataSync) without the await. That will give you a JavaScript array with whatever your model was trained to predict. Beyond that we can't really help with how to interpret that output.
> 
> If by chance this was a model you trained using AutoML, you can take a look at this package https://github.com/tensorflow/tfjs/tree/master/tfjs-automl documenting how to get output from those trained models.

Thanks for your response. My model is Graph model. It was a saved_model. I've trained it on Python and converted via tensorflowjs_converter.  

Actually, I need to interpret the output data after executeSync.

**Comment by sundowatch** [comment] 2020-03-09 07:06
Finally I've trained my model on Google Cloud AutoML as @tafsiri 's mention. But when I use it, I've some error. Here is my code:
```
<script src="https://unpkg.com/@tensorflow/tfjs"></script>
<script src="https://unpkg.com/@tensorflow/tfjs-automl"></script>
<img id="test" crossorigin="anonymous" src="test.jpg"><script>
async function run() {
  const model = await tf.automl.loadImageClassification('model3/model.json');
  const image = document.getElementById('test');
  const predictions = await model.classify(image);
  console.log(predictions);
  // Show the resulting object on the page.
  const pre = document.createElement('pre');
  pre.textContent = JSON.stringify(predictions, null, 2);
  document.body.append(pre);
}
run();
</script>
```
I'm using this on **browser**.
And the console error:
`graph_executor.ts:109 Uncaught (in promise) Error: This execution contains the node 'Preprocessor/map/while/Exit_2', which has the dynamic op 'Exit'. Please use model.executeAsync() instead. Alternatively, to avoid the dynamic ops, specify the inputs [Preprocessor/map/TensorArrayStack/TensorArrayGatherV3]`

When I use `executeAsync()` instead of `classify()` I'm having another issue:

`index2.html:7 Uncaught (in promise) TypeError: model.executeAsync is not a function at run 
`

**Comment by tafsiri** [comment] 2020-03-09 15:30
@sundowatch Could you tell us more about your model and steps to reproduce? Is it an **image classification** model or an **object detection** model? Your code above suggests its an image classification task but the issue title suggests object detection.

Did you train it with AutoML Vision? A few pointers for this workflow are in https://blog.tensorflow.org/2019/10/build-and-deploy-tensorflowjs-models.html 

cc @dsmilkov

**Comment by sundowatch** [comment] 2020-03-15 13:13
I've now trained with AutoML and it works fine. But don't know why can't I use it with tensorflow training.

**Comment by tafsiri** [comment] 2020-03-16 14:17
I'm going to close this issue since the original problem has been solved. But if you are looking for more general "how can I do X" tips. I would suggest using StackOverFlow, there is both a [tensorflow](https://stackoverflow.com/questions/tagged/tensorflow) tag and a [tensorflow.js](https://stackoverflow.com/questions/tagged/tensorflow.js) that may have some helpful pointers. You might also find some of the online courses listed on [this page](https://www.tensorflow.org/resources/learn-ml) helpful.

**Closed by tafsiri** 2020-03-16 14:17 UTC
Labels: stat:awaiting response, type:support
