### ISSUE TITLE
tfjs-models/handpose failing on tf.js 2.3 with 

### ISSUE THREAD

**Issue by markstrefford** [tensorflow/tfjs#3862] opened 2020-08-28 13:46 UTC
When using the latest version of tf.js (2.3.0 at time of writing), hand pose fails to build with this error:

```"node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.esm.js:17:1325: Cannot resolve dependency worker_threads"```

The GitHub version's package.json has the following versions:

```
    "@tensorflow/tfjs-backend-wasm": "2.1.0",
    "@tensorflow/tfjs-backend-webgl": "2.1.0",
    "@tensorflow/tfjs-converter": "2.1.0",
    "@tensorflow/tfjs-core": "2.1.0"
```

which work ok.

Replace [package.json](https://github.com/tensorflow/tfjs-models/blob/master/handpose/package.json) versions with these and run `parcel build index.html` to get the error above: 

```
    "@tensorflow/tfjs-backend-wasm": "^2.3.0",
    "@tensorflow/tfjs-backend-webgl": "^2.3.0",
    "@tensorflow/tfjs-converter": "^2.3.0",
    "@tensorflow/tfjs-core": "^2.3.0"
```

**Comment by annxingyuan** [comment] 2020-09-01 17:08
Hi @markstrefford - thanks for reporting this. The issue is the latest TF.js requires a node module `worker_threads`, but we did not exclude it from the browser build. This will be fixed in the next release, but in the meantime you can do something like this locally to get around the problem: https://github.com/tensorflow/tfjs-models/pull/518

**Comment by TomWyllie** [comment] 2020-09-09 21:42
I'm experiencing the issue, also missing `perf_hooks` when trying to build using webpack (in a project built with `vue-cli`), the error message is here in case it helps anybody else find this thread. A revert back down to 2.1.0 from 2.3.0 resolved this error for me, but the suggested changes to `package.json` didn't.

```
These dependencies were not found: 
* perf_hooks in ./node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.esm.js
* worker_threads in ./node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.esm.js
```

**Closed** 2020-09-29 18:34 UTC
Labels: comp:models, comp:wasm, stalled, stat:awaiting response, type:bug
