### ISSUE TITLE
posenet\demo\coco.js: function __clone()... could not be cloned error when trying to start dev demo server

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tfjs#5000] opened 2021-04-28 04:26 UTC
Hi, I cloned the tfjs-models repository and was about to try out posenet demo.

I followed the instructions as per GitHub: https://github.com/tensorflow/tfjs-models/tree/master/posenet/demo

everything went well but when I did yarn watch, I got the following error:

"
PS C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo> yarn watch
yarn run v1.22.10
$ cross-env NODE_ENV=development parcel index.html --no-hmr --open
Server running at http://localhost:1234 
×  C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\coco.js: function __clone() {
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    at Object.serialize (v8.js:256:7)
    at _default (C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\node_modules\@babel\core\lib\transformation\util\clone-deep.js:16:30)
    at normalizeFile (C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\node_modules\@babel\core\lib\transformation\normalize-file.js:52:36)
    at normalizeFile.next (<anonymous>)
    at run (C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\node_modules\@babel\core\lib\transformation\index.js:31:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\node_modules\@babel\core\lib\transform-ast.js:20:41)
    at Generator.next (<anonymous>)
    at evaluateSync (C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\node_modules\gensync\index.js:251:28)
    at Function.sync (C:\Users\raywl\Documents\achiever\Android\AI services\tfjs-models\posenet\demo\node_modules\gensync\index.js:89:14)

"
a browser tab also loaded up with the same build error.

I am running on Windows 10 and my editor is Visual Studio Code:

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Please advise.

**Comment by rthadur** [comment] 2021-04-28 17:10
@FlyWong thanks for reporting , i could reproduce the same in MAC OS , will dig deep more in to actual issue  and keep you posted.

**Comment by FlyWong** [comment] 2021-05-03 02:04
Hi,

is there any update on this issue?
________________________________

**Comment by rthadur** [comment] 2021-05-06 22:46
this is a duplicate of https://github.com/tensorflow/tfjs/issues/4921 , will track the same issue at one place. Closing this issue. Thank you

**Closed by rthadur** 2021-05-06 22:46 UTC
Labels: type:build/install
