### ISSUE TITLE
Error when converting manifest.json into Keras hdf5

### ISSUE THREAD

**Issue by JivanRoquet** [tensorflow/tfjs#2777] opened 2020-02-20 00:05 UTC
#### Describe the problem or feature request

There is an error when trying to use tensorflowjs_converter to convert a json file to a Keras model.

Source manifest.json file:
https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_100/manifest.json

Error description:
**Field "modelTopology" is missing from the JSON content.**

#### Code to reproduce the bug / link to feature request

Open a terminal and type the following commands:

```bash
wget https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_100/manifest.json
tensorflowjs_converter --input_format=tfjs_layers_model --output_format=keras manifest.json ./posenet.h5
```

The following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 645, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 649, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 608, in convert
    args.output_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 222, in dispatch_tensorflowjs_to_keras_h5_conversion
    model = keras_tfjs_loader.load_keras_model(config_json_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_tfjs_loader.py", line 194, in load_keras_model
    _check_config_json(config_json)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_tfjs_loader.py", line 96, in _check_config_json
    raise KeyError('Field "modelTopology" is missing from the JSON content.')
KeyError: 'Field "modelTopology" is missing from the JSON content.'
```

**Comment by rthadur** [comment] 2020-02-20 17:27
I was able to reproduce the same but it sounds like the file you're trying to load contains only variable weights, but does not specify the model topology (aka "architecture"), i.e. the types of layers and the connections among them. Please see https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model regarding how to get a combined topology+weights model file, and https://js.tensorflow.org/tutorials/import-keras.html for how to convert that to the TF.js format.

**Comment by rthadur** [comment] 2020-03-06 21:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2020-03-06 21:15 UTC
Labels: comp:converter, stat:awaiting response, type:support
