### ISSUE TITLE
[RN] Pose Detection not working on android.

### ISSUE THREAD

**Issue by GwangjoGong** [tensorflow/tfjs#5967] opened 2021-12-27 10:23 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes. I referred to the pose detection example.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Monterey 12.0.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S10 5G
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): ^0.8.0
- Browser version: Chrome 96.0
- Tensorflow.js Converter Version: ^3.11.0
- Expo version : 43.0.0

**Describe the current behavior**
Pose estimation not working properly only on Android. (keypoints are detected, but very low score)

There was no error during preparation (load model, handleImageTensorReady). 
Also, camera preview works properly.

**Describe the expected behavior**
Pose estimation should work same as IOS.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

##### package.json
```
"@tensorflow-models/pose-detection": "^0.0.6",
"@tensorflow/tfjs": "^3.11.0",
"@tensorflow/tfjs-react-native": "^0.8.0",
"expo": "~43.0.0",
"expo-camera": "~12.0.3",
"expo-file-system": "~13.0.3",
"expo-gl": "~11.0.3",
"expo-gl-cpp": "~11.0.1",
```
##### code
```typescript
// !!This screen is displayed only in the landscape orientation!!

import { Camera } from 'expo-camera';
import React from 'react';
import { Platform, StyleSheet, View } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { colors } from 'src/styles';

import * as PoseDetection from '@tensorflow-models/pose-detection';
import * as tf from '@tensorflow/tfjs';
import { cameraWithTensors } from '@tensorflow/tfjs-react-native';

export type CameraBackdropHandle = {
  flush: () => number;
};

type CameraBackdropProps = {
  setLoading: () => void;
};

const TensorCamera = cameraWithTensors(Camera);

const inputTensorHeight = 270;
const inputTensorWidth = Platform.OS === 'ios' ? 480 : 360;

const outputTensorHeight = 180;
const outputTensorWidth = Platform.OS === 'ios' ? 320 : 240;

const MIN_KEYPOINT_SCORE = 0.4;

export const CameraBackdrop = React.forwardRef<
  CameraBackdropHandle,
  CameraBackdropProps
>(({ setLoading }, ref) => {
  const [model, setModel] = React.useState<PoseDetection.PoseDetector | null>(
    null,
  );
  const [keypoints, setKeypoints] = React.useState<
    PoseDetection.Keypoint[] | null
  >(null);

  const [diffBuffer, setDiffBuffer] = React.useState<number[]>([]);

  const targetKeypoints = [
    'nose',
    'left_shoulder',
    'right_shoulder',
    'left_elbow',
    'left_wrist',
    'right_elbow',
    'right_wrist',
    'left_hip',
    'right_hip',
    'left_knee',
    'right_knee',
  ];

  const calculatePoseDifference = (
    prevKeypoints: PoseDetection.Keypoint[],
    newKeypoints: PoseDetection.Keypoint[],
  ) => {
    const calculatableKeypoints = newKeypoints.filter(k =>
      prevKeypoints.find(p => p.name === k.name),
    );

    if (calculatableKeypoints.length === 0) {
      setDiffBuffer(prev => [...prev, 0]);
    }

    let diff = 0;

    for (const keypoint of calculatableKeypoints) {
      const prevKeypoint = prevKeypoints.find(k => k.name === keypoint.name)!;

      const xDiff = keypoint.x - prevKeypoint.x;
      const yDiff = keypoint.y - prevKeypoint.y;

      const distance = Math.sqrt(xDiff ** 2 + yDiff ** 2);

      diff += Math.round(distance);
    }

    diff /= calculatableKeypoints.length;

    setDiffBuffer(prev => [...prev, diff]);
  };

  const handleImageTensorReady = async (
    images: IterableIterator<tf.Tensor3D>,
  ) => {
    const loop = async () => {
      if (model) {
        const imageTensor = images.next().value;

        const poses = await model.estimatePoses(
          imageTensor,
          undefined,
          Date.now(),
        );
        if (poses.length > 0) {
          const newKeypoints = poses[0].keypoints.filter(
            k =>
              (k.score ?? 0) > MIN_KEYPOINT_SCORE &&
              targetKeypoints.find(p => p === k.name),
          );

          setKeypoints(prev => {
            if (prev) {
              calculatePoseDifference(prev, newKeypoints);
            }
            return newKeypoints;
          });
        }
        tf.dispose([imageTensor]);

        requestAnimationFrame(loop);
      }
    };

    loop();
  };

  const cameraView = () => {
    return (
      <View style={styles.container}>
        <TensorCamera
          style={styles.camera}
          type={Camera.Constants.Type.front}
          rotation={Platform.OS === 'ios' ? 90 : 0}
          resizeWidth={outputTensorWidth}
          resizeHeight={outputTensorHeight}
          resizeDepth={3}
          autorender
          onReady={handleImageTensorReady}
          onMountError={err => console.log(err)}
        />
        <View style={styles.modelResults}>{renderPose()}</View>
      </View>
    );
  };

  const renderPose = () => {
    if (model && keypoints) {
      const keypointsCircles = keypoints.map((k, i) => {
        return (
          <Circle
            key={`skeletonkp_${i}`}
            cx={k.x}
            cy={k.y}
            r="4"
            strokeWidth="0"
            fill="green"
          />
        );
      });

      return (
        <Svg
          height="100%"
          width="100%"
          viewBox={`0 0 ${inputTensorWidth} ${inputTensorHeight}`}
        >
          {keypointsCircles}
        </Svg>
      );
    } else {
      return null;
    }
  };

  React.useImperativeHandle(ref, () => ({
    flush: () => {
      if (diffBuffer.length === 0) {
        return 0;
      } else {
        const avg = diffBuffer.reduce((a, b) => a + b, 0) / diffBuffer.length;
        setDiffBuffer([]);
        return avg;
      }
    },
  }));

  React.useEffect(() => {
    const prepare = async () => {
      await tf.ready();
      try {
        const model = await PoseDetection.createDetector(
          PoseDetection.SupportedModels.MoveNet,
          {
            modelType: PoseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,
            enableSmoothing: true,
          },
        );

        setModel(model);
        setLoading();
      } catch (err) {
        console.log(err);
      }
    };
    prepare();
  }, []);

  return model ? cameraView() : null;
});

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: -1,
    top: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  camera: {
    position: 'absolute',
    width: inputTensorWidth,
    height: inputTensorHeight,
  },
  modelResults: {
    position: 'absolute',
    width: inputTensorWidth,
    height: inputTensorHeight,
    zIndex: 20,
  },
  cover: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 0,
    top: 0,
    left: 0,
    backgroundColor: colors.black,
  },
});
```

**Comment by rthadur** [comment] 2021-12-28 19:55
Did you get chance to check the working example provided here https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection ?

**Comment by GwangjoGong** [comment] 2021-12-29 03:48
@rthadur 
I tested the working example on both OS, but neither worked. (Galaxy S10 5G, iPhone 11 Pro)

**Result**
IOS : app crashed after warning: initialization of backend rn-webgl failed
Android : only black screen displayed.(both front/back camera) frame rate was about 4~5fps.

**Test Process**
1. clone repo
2. `yarn && yarn start`
3. Scan QR code and launch app with Expo Go

**Comment by steswinbank** [comment] 2021-12-29 21:17
I can confirm the same behaviour as @GwangjoGong using the examples https://github.com/tensorflow/tfjs-examples/tree/master/react-native/pose-detection on a Pixel 4a and a iPhone 8.

**Comment by jinjingforever** [comment] 2022-01-05 00:28
Hi,

This is likely to be caused by incompatible expo-gl and expo-gl-cpp. Please double check the version combination mentioned [here](https://github.com/tensorflow/tfjs-examples/tree/master/react-native). Any higher version of expo-gl and expo-gl-cpp might cause crash. 

If the app doesn't work directly from the cloned repo, that might indicate some other problems.. I will need to borrow a pixel 4 somewhere for further testing:)

**Comment by GRenkel** [comment] 2022-01-07 20:16
I had the same problem as @GwangjoGong using the example with Galaxy A52s. When testing in a Iphone 12, the application just crashed.

**Comment by rthadur** [comment] 2022-01-14 23:06
related PR has been merged , closing this issue. Feel free to @mention to reopen if the issue still exists. Thank you

**Closed by rthadur** 2022-01-14 23:06 UTC
Labels: type:bug, comp:react-native, stat:awaiting response, stalled

**Comment by GwangjoGong** [comment] 2022-01-26 09:20
@jinjingforever 
Thank you for the update. I've tested the example on Samsung Galaxy S10, but the example still not working properly.

**Expected behavior**
keypoints should be displayed just like the image on the `README.md`

**Actual behavior**
App does not crashed, but the keypoints(green circles) not displayed properly. (only 1-2 circles shown randomly)

**Test Process**
1. clone repo
2. `yarn` => Failed with ```error An unexpected error occurred: "https://registry.yarnpkg.com/colors/-/colors-1.4.2.tgz: Request failed \"404 Not Found\"".```
3. `rm yarn.lock`
4. `yarn && yarn start`
5. set camera to front and adjust position to show my face and shoulder. (just like image on `README.md`
