### ISSUE TITLE
Moving GL initialization into registerBackend() factory method causes a GC exception during unit tests.

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1732] opened 2019-07-10 16:46 UTC
When moving all headless WebGL initialization into the factor method of `registerBackend()` the unit tests in core crash with a bad pointer during a GC cycle. I'm guessing that something is messing with ref-counting/weak-ref'ing GL contexts during the tfjs-core:

Stack trace:
```
#0  0x000000000f503c50 in ?? ()
#1  0x00000000008e8b82 in (anonymous namespace)::v8impl::Reference::FinalizeCallback(v8::WeakCallbackInfo<(anonymous namespace)::v8impl::Reference> const&) ()
#2  0x0000000000e96ab3 in v8::internal::GlobalHandles::DispatchPendingPhantomCallbacks(bool) ()
#3  0x0000000000e96cda in v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#4  0x0000000000ed38da in v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) ()
#5  0x0000000000ed4704 in v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) ()
#6  0x0000000000ed4eda in v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) ()
#7  0x0000000000ed85b7 in v8::internal::IncrementalMarkingJob::Task::RunInternal() ()
#8  0x0000000000bca866 in v8::internal::CancelableTask::Run() ()
#9  0x0000000000964ca4 in node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) ()
#10 0x0000000000966062 in node::PerIsolatePlatformData::FlushForegroundTasksInternal() ()
#11 0x0000000000a498df in uv__async_io (loop=0x24adfe0 <default_loop_struct>, w=<optimized out>, events=<optimized out>) at ../deps/uv/src/unix/async.c:118
#12 0x0000000000a5a5c8 in uv__io_poll (loop=loop@entry=0x24adfe0 <default_loop_struct>, timeout=0) at ../deps/uv/src/unix/linux-core.c:375
#13 0x0000000000a4a21b in uv_run (loop=0x24adfe0 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:370
#14 0x00000000008e6f45 in node::Start(v8::Isolate*, node::IsolateData*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&) ()
#15 0x00000000008e5239 in node::Start(int, char**) ()
#16 0x00007ffff6af252b in __libc_start_main (main=0x89ec50 <main>, argc=3, argv=0x7fffffffd998, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffd988) at ../csu/libc-start.c:308
#17 0x000000000089ed85 in _start ()
```

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:23
Hi, @nkreeger 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:23 UTC
Labels: type:others, stat:awaiting response, comp:headless_nodegl
