### ISSUE TITLE
Cannot convert saved model with nn.dropout

### ISSUE THREAD

**Issue by VjunetXuuftofi** [tensorflow/tfjs#1740] opened 2019-07-15 21:27 UTC
#### TensorFlow.js version
1.2.2.1
#### Tensorflow version
2.0.0b1

#### Browser version
N/A

#### Describe the problem or feature request
I am unable to convert a tensorflow saved model that uses nn.dropout.

#### Code to reproduce the bug / link to feature request
In python:
```
from tensorflow import keras
import tensorflow as tf
from tensorflow.python.ops import nn

class TestModel(keras.models.Model):
    def __init__(self):
        super(TestModel, self).__init__()

    @tf.function(
        input_signature=[tf.TensorSpec([None, None, None, 1], tf.float32)])
    def inference(self, inputs):
        inputs = nn.dropout(inputs, rate=0.25)
        return inputs

model = TestModel()
tf.saved_model.save(model, "saved_model_test")
```
Then, with the converter:
`tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model saved_model_test web_model_test`

Error is as follows:
Traceback (most recent call last):
  File "/home/user/.conda/envs/general/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/home/user/.conda/envs/general/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 556, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/home/user/.conda/envs/general/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 291, in convert_tf_saved_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "/home/user/.conda/envs/general/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 129, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
StatefulPartitionedCall

The model can be loaded fine in Python with `tf.saved_model.load("saved_model_test")`.

Thanks for looking at this.

**Comment by rthadur** [comment] 2019-07-15 22:15
@pyu10055 can you please help with this ?

**Comment by pyu10055** [comment] 2019-07-19 23:21
@VjunetXuuftofi dropout ops are usually not used in the inference graph, can you explain your use case here? thanks.

**Comment by VjunetXuuftofi** [comment] 2019-07-22 21:10
@pyu10055 The dropout is used for bayesian approximation as described here: https://arxiv.org/abs/1506.02142

**Comment by pyu10055** [comment] 2019-07-22 23:30
@VjunetXuuftofi The issue is fixed upstream in TF grappler, but unfortunately you will need to wait for the next TF 1.14 updated before you can get this fix.

**Comment by rthadur** [comment] 2019-08-02 20:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2019-08-02 20:21 UTC
Labels: comp:converter, stat:awaiting response, type:bug
