### ISSUE TITLE
Start logging tfjs-layers browser benchmarks to Firebase

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1374] opened 2019-03-13 14:09 UTC

**Comment by caisq** [comment] 2019-03-13 14:09
cc @annxingyuan

**Comment by annxingyuan** [comment] 2019-03-13 14:21
Hey @caisq - I'm going to close this as it is a duplicate of https://github.com/tensorflow/tfjs/issues/985

**Closed by annxingyuan** 2019-03-13 14:21 UTC
Labels: type:performance
