### ISSUE TITLE
Add property for symbol source in docs.json

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#365] opened 2018-05-30 20:52 UTC
_From @tafsiri on March 19, 2018 15:44_

It would be nice to have a property in the docs json for which api the symbol comes from (core or api). Its inferrable from the github url so not urgent, but would be nice. This can be done in the merge step of the build.

cc @nsthorat thoughts?

_Copied from original issue: tensorflow/tfjs-website#26_

**Comment by tafsiri** [comment] 2018-05-30 20:52
_From @nsthorat on March 19, 2018 17:3_

Yeah this should be easy, I think maybe it's easier to just do it in the individual repo parser. Either way should work.

**Comment by rthadur** [comment] 2019-07-24 22:26
@tafsiri is this done ? if yes, can we close this issue ? thank you

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:25
Hi, @tafsiri 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:46
Hi, @tafsiri 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:46 UTC
Labels: type:docs, comp:website, stat:awaiting response
