### ISSUE TITLE
Bi-Directional LSTM model with Embedding layer for Language Translation 

### ISSUE THREAD

**Issue by jaygit123** [tensorflow/tfjs#4663] opened 2021-02-09 19:10 UTC
Hi,

I have created a Bi-Directional LSTM model with Embedding layer in Keras (Python) for Language Translation and converted to tfjs Graph model.
In the Keras (python) model, I give the input to model for prediction as an array of padded sequences (using Tokenizer, dataset is first fit_on_texts(), texts_to_sequences() and then pad_sequences()). So, for training and prediction I use the array of padded sequences (sentences). This way the model works perfectly.

Input layer of the model:
`model.add(Embedding(src_vocab, n_units, input_length=src_timesteps, mask_zero=True))`
src_vocab - 30973
n_units - 256
src_timesteps - 109

But in tfjs, when I give a tokenized, padded sentence converted to tensor2d and give as input for model.executeAsync() function, it doesn't accept and I get the below error.

> Uncaught (in promise) Error: Error in where:  Shapes 1,1 and 1,256 must match

I am quite new to tfjs and would appreciate any inputs on the above.

Thanks in advance.

**Comment by jaygit123** [comment] 2021-02-10 12:11
Hi @mattsoulanille,

Just noticed that in the existing tfjs examples on language tasks like text generation & translation the sentences to be predicted are tokenized, padded and then one-hot encoded before giving as input to predict() method. 

Though one-hot encoding is not required for the Keras (Python) version of the model I am using, not sure if I have to do one-hot encoding to give as input to converted tfjs model's predict() method.

Any inputs will be helpful. 

Thanks.

**Comment by mattsoulanille** [comment] 2021-02-10 14:22
Hi @jaygit123,

Thanks for the report. I don't know off the top of my head what's wrong here, but I'm pretty sure the converted model is suppose to take the same inputs as it does in tf (i.e. you shouldn't have to one-hot encode). Are you able to provide a reproduction (codepen or github repo is fine) that I can take a look at? Thanks!

**Comment by jaygit123** [comment] 2021-02-10 20:28
Hi @mattsoulanille,

Thanks for the response.

Below are the necessary files I have shared:
1. notebook with tf model inference steps & its dataset
2. tf model file 156mb in size ( [https://drive.google.com/file/d/1c77Wcd5p1giFmYp5n_VlQXwCGWk5PEg0/view?usp=sharing](url) )
3. tf model's corresponding tfjs model files
4. required HTML & JS files for testing tfjs model
5. screenshot of the error (browser js console)

Please check this github link to access the above mentioned files - [https://github.com/jaygit123/tfjs-translator](url)

I hope the above files will help you in checking. Let me know if any other details / files are required.  

Thanks.

**Comment by mattsoulanille** [comment] 2021-02-11 23:02
Hi @jaygit123,

I was able to reproduce the bug with the files you've shared, but I haven't found the cause yet. I noticed you're using a Graph model, so it's possible this is related to #4579 (although this doesn't seem too likely since I tried the workaround for that issue and it didn't help). I'll try converting to a Layers model to see if that helps, and I'll keep you posted.

**Comment by jaygit123** [comment] 2021-02-12 15:13
Hi @mattsoulanille ,

Thanks for the update. Let me know if you want me to try any option / fix. 
Shall wait to hear from you on the issue & fix, if applicable.

Regards,
Jay

**Comment by jaygit123** [comment] 2021-02-14 04:52
Hi @mattsoulanille ,
Any updates? Were you able to find the reason for the error? Any fix / workaround?

Regards,
Jay

**Comment by jaygit123** [comment] 2021-02-16 18:00
Hi @mattsoulanille ,
Any updates? 

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-17 16:29
Hi @jaygit123,

Sorry for not getting back to you sooner. I've found a workaround, and a likely bug in our graph model runner / converter. If you use a layers model, it should work. [Here's an example using the demo you shared](https://github.com/mattsoulanille/tfjs-translator).

**Comment by jaygit123** [comment] 2021-02-18 05:04
Hi @mattsoulanille ,

Thanks for the workaround. Shall try out. 
Given the small file size of graph model, I would prefer to use the same. So, is there a way to use graph model and still avoid this issue? Maybe change the model arch or avoid certain operations or use a different version of converter, etc.? Do let me know. 

Also, let me know if I should log a bug for this problem.

Regards,
Jay

**Comment by jaygit123** [comment] 2021-02-18 15:27
Hi @mattsoulanille ,

I tried the workaround of using layer model and it worked without the shape error. But the predicted output doesn't make sense to me. Please see the tf prediction and tfjs prediction output below.

**Issues:**
1. tfjs prediction's shape is (80, 23609) whereas tf model's prediction is (80)
2. tfjs prediction values are all float values (it should be embedding array just like the tf model's prediction)

Could you let me know if the tfjs conversion is creating these issues are I am misinterpreting the tfjs prediction? 

**tf prediction for 1 sentence input: (shape: 1, 80)**
array([  9,  46,  15, 349,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0])

**tfjs prediction for 1 sentence input: (shape of prediction tensor: 1, 80, 23609)**
    [[0.0279146, 0, 0.0000827, ..., 0.0000393, 0.0000114, 1e-7],
     [0.0279146, 0, 0.0000827, ..., 0.0000393, 0.0000114, 1e-7],
     [0.0279146, 0, 0.0000827, ..., 0.0000393, 0.0000114, 1e-7],
     ...,
     [0.0279146, 0, 0.0000827, ..., 0.0000393, 0.0000114, 1e-7],
     [0.0279146, 0, 0.0000827, ..., 0.0000393, 0.0000114, 1e-7],
     [0.0279146, 0, 0.0000827, ..., 0.0000393, 0.0000114, 1e-7]]

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-19 15:28
Hi @jaygit123,

When I look at the saved keras model in python, I see the following output shape:
```python
>>> import tensorflow as tf
>>> print(tf.version.VERSION)
2.4.1
>>> model = tf.keras.models.load_model('./Bi-LSTM-medium-TPU-256units.h5')
>>> print(model.outputs)
[<KerasTensor: shape=(None, 80, 23609) dtype=float32 (created by layer 'time_distributed_1')>]
```
This seems to match the tfjs layers output shape. I'm using the model file shared via the Drive link you posted above. Is that the right one?

**Comment by jaygit123** [comment] 2021-02-19 19:31
Hi @mattsoulanille 
Yes, it's the same model I shared with you.
If you check the output of that model, you will see it generates proper predictions as array of int numbers which refer to the index of those words in word embedding.
But in case of tfjs model, the output is a matrix of 80, 23609 filled with float values.
Hence my question about any model conversion issue or my misinterpretation of predictions.

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-19 21:24
Hi @jaygit123 
Maybe I'm running your model incorrectly. When I run `model.predict()` in tf, it gives me an output shape of `(1, 80, 23609)` filled with `float32`s. How are you running the model in tf?

```python
>>> import tensorflow as tf
>>> model = tf.keras.models.load_model('./Bi-LSTM-medium-TPU-256units.h5')
>>> input = tf.random.uniform((1,109))
>>> prediction = model.predict(input)
>>> prediction.shape
(1, 80, 23609)
>>> prediction.dtype
dtype('float32')
>>> prediction
array([[[7.0784455e-07, 1.1108966e-22, 8.9243825e-34, ...,
         1.3846356e-12, 2.2302575e-05, 1.8853796e-06],
        [3.5453806e-05, 1.6757647e-09, 3.4782508e-22, ...,
         5.2590633e-11, 1.7273683e-03, 7.8318141e-07],
        [1.2617011e-05, 2.0112324e-16, 1.0599732e-18, ...,
         5.6663545e-08, 6.6595458e-05, 6.3414939e-07],
        ...,
        [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00]]], dtype=float32)


```

**Comment by jaygit123** [comment] 2021-02-20 03:18
Hi @mattsoulanille ,

Please use/ refer the notebook I had shared to see how I am using the keras model.

Regards,
Jay

**Comment by jaygit123** [comment] 2021-02-23 14:03
Hi @mattsoulanille ,

Hope you were able to check the notebook for usage of keras model. Any update on why the tfjs converted model is returning float values? 

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-23 17:33
Hi @jaygit123,

I took a look at your notebook, and it looks like you're using `predict_classes` (instead of `predict`), which returns the highest-scored output class instead of an array of the output class scores. That's why you're getting an output shape of (1, 80) of integers corresponding to the class instead of (1, 80, 23609) of floats corresponding to class weights. I don't think tfjs has `predict_classes` yet, so you'll have to manually find each class with the highest prediction score in the (1, 80, 23609) output.

Here's an example of doing that in Python:
```python
>>> classes = model.predict_classes(input)
>>> classes
array([[23099,  4610,    11,  1046,    81,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11, 22345, 16934,
        16980, 17039,    64,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]])
>>> prediction = model.predict(input)
>>> np.argmax(prediction, 2)
array([[23099,  4610,    11,  1046,    81,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11,    11,    11,
           11,    11,    11,    11,    11,    11,    11, 22345, 16934,
        16980, 17039,    64,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]])
```

**Comment by jaygit123** [comment] 2021-02-24 20:04
Hi @mattsoulanille 

Thanks for the input. 
As suggested, I have used tf.argMax(prediction, 2) on the output of `predict()` method, to get each class with the highest prediction score in (1, 80, 23609) output. But, still I see a different output from tfjs model than that of the keras model.

Input tensor (shape: 1, 109): [[3, 160, 6, ..., 0, 0, 0],]
Output tensor of Keras model's `predict_classes() `method: [[3, 160, 6, ..., 0, 0, 0],] (shape is 1, 80)
`tf.argMax()` Output tensor of tfjs model: [[14, 147, 1257, ..., 1257, 1257, 1257],] (shape is 1, 80)

Note sure what I am missing. Kindly help. 

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-25 16:35
The predictions should be the same, but I was able to reproduce this locally as well (and with different tfjs backends). I'll update you when I've found out more.

**Comment by jaygit123** [comment] 2021-02-25 17:00
Hi @mattsoulanille ,
Thanks for the update. Will wait to hear from you.
Just to confirm...using tf.argMax() is ok right? 

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-25 17:16
Using [`tf.argMax`](https://js.tensorflow.org/api/latest/#argMax) should be fine. I've found a difference in what `model.predict` returns before running argMax on it, so there's definitely something wrong here. Might be a converter bug.

I took a look with [Netron](https://github.com/lutzroeder/netron) at the keras model file and the layers converted model files, and it looks like some of the steps in the model may be missing some configuration data in the layers model. However, it's possible I'm misreading Netron. I'd post a screenshot but I don't want to share the full model details if it's not public.

**Comment by jaygit123** [comment] 2021-02-25 18:35
@mattsoulanille , I too thought about it being converter bug...so wondering if trying with a different version of converter will reveal something...what do you say? 

I have added you to a private repo. Please upload the screenshot there.  

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-02-25 20:51
@jaygit123 I converted the model using version 3.1.0, which is up-to-date with 3.2.0 (3.2.0 didn't have any converter commits). I could try with an earlier version to see if there are any differences. 

I've uploaded the Netron screenshot to the repo.

**Comment by jaygit123** [comment] 2021-02-26 09:57
@mattsoulanille Thanks for the Netron screenshot...I too am not seeing any difference between the models.

BTW, I had used converter v 3.0.0. 
> tensorflowjs 3.0.0
> 
> Dependency versions:
>   keras 2.4.0
>   tensorflow 2.4.1

Do you have any specific earlier version of converter in mind for checking? Let me know, so I can also check.

Regards,
Jay

**Comment by jaygit123** [comment] 2021-03-01 16:24
@mattsoulanille , any updates on this?

Regards,
Jay

**Comment by jaygit123** [comment] 2021-03-06 08:03
Hi @mattsoulanille , were you able to make any progress on this issue? 
Should we conclude that this is a 'converter' related bug or do you have any other observations? 
Either way, wish to have a resolution at the earliest, please. 

Regards,
Jay

**Comment by jaygit123** [comment] 2021-03-11 15:25
Hi @mattsoulanille , @rthadur 
Could you guys help with this issue? 

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-03-11 15:34
Hi @jaygit123. Sorry I haven't gotten a chance to take a deeper look at this and fix it. Here's what I've found out since I last updated you.

By cutting layers off your model until the output from the browser and from tf are the same, I've determined that there's likely something wrong with how tfjs handles the bidirectional LSTM layer. I actually no longer think this is a converter bug, since the weights I thought were missing are actually stored in separate files and appear in the tfjs model after it's loaded in the browser.

I'll make time to look at this today. Thanks again for your patience.

**Comment by mattsoulanille** [comment] 2021-03-11 22:35
Hi @jaygit123 

I've partially found out what's causing this bug. It is indeed a problem with how tfjs is running the bidirectional LSTM layer. For some reason, the second bidirectional layer in the model always returns zero for all indices above 255 in its output tensor. What's even more strange is that this doesn't happen when I run the second bidirectional layer by itself in a new model. This behavior makes me think the first bidirectional layer, which uses 256 as an output dimension, is somehow triggering this model executor bug.

Since the second bidirectional layer works fine when it's split into its own model, I tried splitting your model in half and passing the outputs of the first half to the input of the second half. This seems to produce correct results, and I've pushed example code that does this to your repository on the `split_model` branch. This, of course, should not be necessary, and I'm looking for a fix.

**Comment by jaygit123** [comment] 2021-03-12 06:20
Hi @mattsoulanille ,
Thanks for the detailed analysis and workaround. Appreciate your support.
Sure, shall wait for the fix.  

Regards,
Jay

**Comment by mattsoulanille** [comment] 2021-03-19 14:35
Not stale.

The graph model is a separate issue, and splitting it so that the bidirectional LSTM layers are in separate models did not help. I still get the same `Shapes 1,1 and 1,256 must match` error.

**Comment by kinsei0916** [comment] 2021-03-27 16:14
Hi @mattsoulanille 

I have the same issue with my bidirectional LSTM model:
`Error in where: Shapes 1,1 and 1,64 must match`

And I found an issue that `where` op doesn't broadcast the input tensors correctly.
As [TensorFlow Docs](https://www.tensorflow.org/api_docs/python/tf/where), all input tensors `conditions`, `a`,  and `b`, are supposed to be broadcasted, whereas we get an error if we specify the inputs which have different shapes with `conditions` and `a`/`b`.

https://github.com/tensorflow/tfjs/blob/d7b58165c5aec73378363747e688161d16fe2e18/tfjs-core/src/ops/where.ts#L53-L84

I sent a PR #4872 which fixes this issue and works well with my model.

**Comment by jaygit123** [comment] 2021-03-29 11:45
Hi @kinsei0916 ,
Thanks for the update. If you have sample code to show usage of the fix PR #4872 , do share so i can try it out for my issue?

**Comment by kinsei0916** [comment] 2021-03-29 23:37
Hi @jaygit123 ,

Here is the reproduction steps:

1. Clone my repo from [kinsei0916/tfjs](https://github.com/kinsei0916/tfjs)
2. `git checkout fix-where-op` to switch to this PR branch
3. `cd tfjs-core`
4. `yarn publish-local` to build and publish locally
5. Move into your project directory and run `yalc add -D @tensorflow/tfjs-core`

**Comment by jaygit123** [comment] 2021-03-30 13:47
Thanks @kinsei0916 . Shall try out.

**Comment by jaygit123** [comment] 2021-04-01 12:09
Hi @kinsei0916 ,

I followed the steps you had mentioned but was unsuccessful in getting the fix work. 
`yarn publish-local` results in the below errors. Do let me know how to progress.

_yarn run v1.12.3
$ rimraf dist/ && yarn build && rollup -c && yalc push
$ node ./scripts/enumerate-tests.js && tsc && yarn bundle
src/engine_test.ts:494:49 - error TS2339: Property 'arrayWithExactContents' does not exist on type 'typeof jasmine'.

494     expect(profile.kernelNames).toEqual(jasmine.arrayWithExactContents([
                                                    ~~~~~~~~~~~~~~~~~~~~~~

src/jasmine_util.ts:115:23 - error TS2339: Property 'getEnv' does not exist on type 'typeof jasmine'.

115   const env = jasmine.getEnv();
                          ~~~~~~

src/public/chained_ops/register_all_chained_ops_test.ts:172:29 - error TS2554: Expected 1 arguments, but got 2.

172           .toBe('function', `${opName} chained op not found`);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._

Regards,
Jay

**Comment by kinsei0916** [comment] 2021-04-01 17:00
Hi @jaygit123 ,

It seems that jasmine is not installed or you use an outdated version of it.
Please try running `yarn` before step 4.

**Comment by kinsei0916** [comment] 2021-04-17 13:34
Hi @jaygit123 ,

This issue seems to be fixed in the latest release [tfjs-v3.4.0](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v3.4.0). I hope this works well!

**Comment by jaygit123** [comment] 2021-04-18 15:56
Hi @kinsei0916 ,
Thanks for the update.

I tried my model on tfjs-v3.4.0 and did not get prediction's shape related error. 
But, the prediction of Keras model and tfjs model are different. When i use predict(input).dataSync() the output shape becomes 1888720 (= 80 * 23609). If I don't use dataSync() on prediction, shape of prediction is 1, 80, 23609 as expected. And when i do argmax of this prediction (1, 80, 23609), output has no values. 

Not sure what I am missing. Could you help clarify? 
I have added you to the repo with my keras & tfjs model for you to reproduce the issue & check. 

Regards,
Jay

**Comment by kinsei0916** [comment] 2021-04-20 20:22
Hi @jaygit123 ,

Thank you for sharing. I got the same output using Graph model as when using Layers model, which seems to be correct. I pushed the code to your repository, so please take a look.

**Comment by jaygit123** [comment] 2021-04-21 16:15
Hi @kinsei0916 , @mattsoulanille ,

I tried with a new Bidirectional LSTM model on tfjs-3.4.0 and got the same results on both Keras and tfjs (used Graph model).
So, I see the issue reported earlier by me is fixed. 

Thanks a ton for your help & support. 

Regards,
Jay

**Comment by rthadur** [comment] 2021-04-22 16:25
Closing this issue as this is resolved , please @mention if this needs more attention. Thank you

**Closed by rthadur** 2021-04-22 16:25 UTC
Labels: stat:awaiting response, type:others
