### ISSUE TITLE
Problems with running script code in tflite

### ISSUE THREAD

**Issue by Zengyf-CVer** [tensorflow/tfjs#5265] opened 2021-06-30 08:31 UTC
##### When I run the script code in the tflite README, an error like this appears in the chrome console:
![ksnip_20210630-162655](https://user-images.githubusercontent.com/41098760/123928042-0e316b00-d9c0-11eb-9f7d-599df35f04ab.png)

##### The code in my html:
- https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite#via-a-script-tag
```html
    <!-- Adds the CPU backend -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu"></script>
    <!-- Import @tensorflow/tfjs-core -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
    <!--
      Import @tensorflow/tfjs-tflite

      Note that we need to explicitly load dist/tf-tflite.min.js so that it can
      locate WASM module files from their default location (dist/).
    -->

    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite/dist/tf-tflite.min.js"></script>
```

**Comment by rthadur** [comment] 2021-06-30 18:48
@Zengyf-CVer are you using VPN ? is there a restriction for google links ?

**Comment by Zengyf-CVer** [comment] 2021-06-30 23:52
> @Zengyf-CVer are you using VPN ? is there a restriction for google links ?
##### Google link is normal, I run the following script is no problem：
```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite/dist/tf-tflite.min.js"></script>
```
##### But when running the following two scripts, there is a problem that the link cannot be found：
```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script> 
```
A question that confuses me, why is there` .map` behind the link?
![ksnip_20210701-075135](https://user-images.githubusercontent.com/41098760/124044962-3ca35a80-da41-11eb-8c3a-59487e08a358.png)

**Comment by rthadur** [comment] 2021-07-01 20:23
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rthadur** [comment] 2021-07-29 06:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2021-07-29 06:16 UTC
Labels: type:build/install
