### ISSUE TITLE
Warm up layers models when they are loaded.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#224] opened 2018-04-24 02:14 UTC
If we pass a tensor of zeros to the model it will compile all the shader programs and upload weights to the GPU, thus making the first inference much faster.

This should be an easy win.

**Comment by bileschi** [comment] 2018-04-24 16:25
Can you explain a little more?  Something like calling `model.predict` internally as the last step in `model.compile` ?

**Comment by nsthorat** [comment] 2018-04-24 17:04
Actually I was thinking `model.predict(tf.zeros(inputLayer.shape));` as the last step of `tf.loadModel`.

**Comment by bileschi** [comment] 2018-04-24 17:48
Seems reasonable.  Quick question:  In general a model might have input layer(s) with incomplete shapes, say [?, 100, 100],  typically for batch.   If we _guess_ the batch size, and are incorrect, does the warm-up behavior still work, or does the GPU memory need to be re-allocated because of the shape change?

**Comment by dsmilkov** [comment] 2018-04-24 18:49
Good q. In that case, we should warmup with the most common case in inference, `batchSize=1`. If we happen to be wrong, some of the GPU programs will be re-compiled, but that's fine.

**Comment by rikkitook** [comment] 2021-05-19 10:56
Little side note: we noticed that on the full tensorflow with gpu enabled, consecutive calls with different batch sizes leads to session reheating. Like, for example, first call with batchsize = 1 is long, first call with batchsize = 5 is also long on the same session

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:28
Hi, @nsthorat 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:47
Hi, @nsthorat

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:47 UTC
Labels: type:feature, comp:layers, P2, stat:awaiting response
