### ISSUE TITLE
Error: Based on the provided shape, [3,3,576,15], the tensor should have 77760 values but has 4784

### ISSUE THREAD

**Issue by sandhyacs** [tensorflow/tfjs#1642] opened 2019-05-31 04:58 UTC
I have trained a custom tensorflow model i.e. ssd_inception_v2 in python using tensorflow version 1.12.0, and converted it into tensorflow js using tfjs converter version 0.8.0.

After conversion, I got 13 shards file and one weight_manifest.json file and 1 .pb file. When I am trying to detect the object in image, getting error as:

util.ts:106 Uncaught (in promise) Error: Based on the provided shape, [3,3,576,15], the tensor should have 77760 values but has 4784
    at v (util.ts:106)
    at Fn (tensor_ops.ts:77)
    at o (io_utils.ts:129)
    at pc (io_utils.ts:79)
    at weights_loader.ts:234
    at Array.forEach (<anonymous>)
    at weights_loader.ts:229
    at Array.forEach (<anonymous>)
    at weights_loader.ts:210
    at index.js:98

This trained model is working fine in python, but not in javascript. Please help me if possible. 

link for model is :
https://raw.githubusercontent.com/rash1994/updated_json/master/weights_manifest.json

**Comment by msektrier** [comment] 2019-05-31 10:56
Have you checked that the input tensor has the same shape in python and tfjs? See also https://github.com/tensorflow/tfjs/issues/1583#issuecomment-497667271

**Comment by sandhyacs** [comment] 2019-05-31 12:11
tensor name is same, but i haven't checked  that the input tensor has the same shape in python and tfjs.... Can you please tell me how can i check?

**Comment by sandhyacs** [comment] 2019-06-03 04:11
Hi, I have checked the input tensor has not same shape in python and tfjs. First two line is same but others are not same. Please tell me how to resolve this issue?

**Comment by pyu10055** [comment] 2019-06-07 04:02
@sandhyacs can you provide your code to reproduce this problem? thanks.

**Comment by sandhyacs** [comment] 2019-06-07 04:44
@pyu10055  here is the code:

let modelPromise;
let baseModel = 'master';

window.onload = () => modelPromise = cocoSsd.load();

const button = document.getElementById('toggle');
button.onclick = () => {
  image.src = image.src.endsWith(imageURL) ? image2URL : imageURL;
};

const select = document.getElementById('base_model');
select.onchange = async (event) => {
  const model = await modelPromise;
  model.dispose();
  modelPromise = cocoSsd.load(
      event.srcElement.options[event.srcElement.selectedIndex].value);
};

const image = document.getElementById('image');
/* let tensor_image=tf.browser.fromPixels(image)
    .resizeNearestNeighbor([300,300])
    .toFloat()
    .expandDims(); */
image.src = imageURL;

const runButton = document.getElementById('run');
runButton.onclick = async () => {
  const model = await modelPromise;
  console.log('model loaded');
  console.time('predict1');
  const result = await model.detect(image).data();
  console.timeEnd('predict1');

**Comment by pyu10055** [comment] 2019-06-19 20:07
This looks like weight loading error, can you try to convert the model using tfjs 1.2.1?
It should generate the model.json and weight sharding files.

**Comment by sandhyacs** [comment] 2019-06-20 04:53
@pyu10055  , Thank you for your reply. Actually previously i was doing the same, i got some version issue so i used tfjs 0.8.0 as my model is trained on tensorflow 1.12.0.

**Comment by sandhyacs** [comment] 2019-07-17 05:09
this input shape problem got solved. if you want to convert .pb into .json you have to enter following command:
tensorflowjs_converter --input_format=tf_saved_model --output_format=tensorflowjs --output_node_names=Postprocessor/ExpandDims_1,Postprocessor/Slice --saved_model_tags=serve  saved_model tfjs_files

**Comment by rthadur** [comment] 2019-07-18 22:10
Thank you , will be closing this issue.

**Closed by rthadur** 2019-07-18 22:10 UTC
Labels: comp:converter, type:support
