### ISSUE TITLE
Long-running shaders result in webgl context lost

### ISSUE THREAD

**Issue by decentralion** [tensorflow/tfjs#263] opened 2018-05-04 02:36 UTC
#### TensorFlow.js version
0.10.0

#### Browser version
Chrome 64.0.3282.167 (Linux)

#### Describe the problem or feature request
Consider the following toy example of matrix exponentiation:
```js
const size = 10000;
const iters = 10;

let tensor, tmp;
tensor = tf.zeros([size, size]);
for (let i=0; i<iters; i++) {
  tmp = tensor.matMul(tensor);
  tensor.dispose();
  tensor = tmp;
}
tensor.max().print();
```

#### Expected:
The program should always print 0, and neither the behavior nor memory usage should vary as `iters` increases, since it results in multiplying the exact same matrix, and the tensor is disposed after being used.

#### Actual: 
With `iters = 5`, the program behaves as expected. With `iters = 10` I have seen the following three behaviors:

* Sometimes it prints NaN, and Chrome reports that "WebGL hit a snag"
* Sometimes it errors with "Couldn't compile vertex shader"
* Sometimes it errors with the long failed script compilation found [here]

[here]: https://gist.github.com/decentralion/7473c7a05d1656efb03b0d2d2cecab52#file-result

#### Reproduction
Navigate to https://js.tensorflow.org/, open the console, and post the example script there. If it works as expected, try increasing the number of iterations and see if it breaks.

**Comment by dsmilkov** [comment] 2018-05-05 01:45
Hey Dandelion, thanks for the detailed report! And hi again!

This is consistent with our observation of executing long-running shaders. A matmul of matrices of size 10Kx10K is ~2TFLOPS. The hypothesis is that Chrome is trying to protect itself and other tabs by prematurely killing the shader program if it takes more than x seconds. This results in either a `NaN` or `WebGL hit a Snag` error.

The solution is non-trivial, but the idea is to use some [divide and conquer](https://en.wikipedia.org/wiki/Matrix_multiplication_algorithm#Divide_and_conquer_algorithm) where we internally divide our matmul job into several smaller matmul shader calls, each on the order GLOPS, instead of TFLOPS, which will keep Chrome and other browsers happy.

We won't be prioritizing this yet, since it hasn't come up in real use-cases (existing ML models), but happy to revisit this later, or take contributions!

**Comment by decentralion** [comment] 2018-05-05 01:46
Cool, thanks for the info. Our conclusion was similar, namely that if we need to handle really big matrices, we should partition them. And :wave: back :smile:

**Comment by rthadur** [comment] 2018-10-30 21:51
@decentralion please let us know if this is still an issue ?

**Comment by decentralion** [comment] 2018-10-31 18:31
@rthadur here's my result from running the reproduction in the issue locally:
![image](https://user-images.githubusercontent.com/1400023/47810366-5e803880-dd00-11e8-91ab-f423970c67b5.png)

**Comment by rthadur** [comment] 2019-10-08 22:27
I was not able to reproduce the error now with latest versions, so will be closing this issue , feel free to comment so that we can reopen.Thank you.
![image](https://user-images.githubusercontent.com/43972606/66437956-170a2e00-e9e0-11e9-908b-e758d5959880.png)

**Closed by rthadur** 2019-10-08 22:27 UTC
Labels: P2, stat:awaiting tensorflower, type:bug

**Comment by josephrocca** [comment] 2020-01-21 03:58
@rthadur I'm getting a crash in Chrome 79:

![image](https://user-images.githubusercontent.com/1167575/72774057-5e4dbf00-3c5d-11ea-9219-f29f7d69fb43.png)

Here's a demo: https://jsbin.com/jequtodute/1/edit?html,output For me the crash occurs after about 1 minute.

I'm on an Ubuntu/PopOS 19.04, with a GTX 2070. As mentioned here: https://github.com/snowme34/tone-the-ear/issues/21 the CPU back-end still works fine.

**Comment by dsmilkov** [comment] 2020-02-13 16:14
Thanks! We won't be able to fix this for several reasons:
- The fix for this is non-trivial and likely impossible without breaking the API since we would need to "release the GPU and the main thread", but we probably won't be able to keep the entire matmul operation synchronous (`tf.matmul().dataSync()` will break).
- Huge matmuls like this do not show up in practical ML models, thus making this a low priority for the time being.
