### ISSUE TITLE
`tf.loadModel` with URL shouldn't fail in NodeJS if `fetch` is defined

### ISSUE THREAD

**Issue by asross** [tensorflow/tfjs#479] opened 2018-06-29 13:40 UTC
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version

0.11.7

#### Browser version

N/A

#### Describe the problem or feature request

Currently, calling `tf.loadModel` with an HTTP URL in NodeJS ends up hitting [this `ENV.IS_BROWSER` check](https://github.com/tensorflow/tfjs-core/blob/master/src/io/browser_http.ts#L43-L46) and failing.

However, the code in `BrowserHTTPRequest` that follows this check actually _does_ work in Node, provided one adds a [`window.fetch` polyfill](https://www.npmjs.com/package/node-fetch).

Although a clear workaround for this problem would be to load the model from the filesystem, I think it would be a lot more convenient for NodeJS users to be able to load models from a URL, especially if that model is being maintained/improved by an external party. So it might make more sense to only error if fetch is undefined, or better yet, add an explicit Node alternative (possibly based on the fetch polyfill itself) and rename `BrowserHTTPRequest` to `HTTPRequest`.

FWIW, what we're currently doing is temporarily pretending that Node is actually a web browser:
```js
const prevIsBrowser = tf.ENV.getFeatures().IS_BROWSER;
tf.ENV.features.IS_BROWSER = true;
const model = await tf.loadModel(modelUrl);
tf.ENV.features.IS_BROWSER = prevIsBrowser;
```
But this isn't ideal!

**Comment by ChALkeR** [comment] 2018-07-04 15:20
Replacing `fetch` with `const fetch = require('node-fetch')` in core and depending on `node-fetch` should be unobtrusive, as node-fetch has a very minimal impl for browsers, [source](https://github.com/bitinn/node-fetch/blob/master/browser.js).

**Comment by rthadur** [comment] 2018-11-21 21:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by haganbt** [comment] 2018-11-25 02:36
Please can this be reopened? This is a priority for usage in a microservices environment where `global.fetch` cannot be set. See https://github.com/tensorflow/tfjs/issues/617#issuecomment-440522402

**Comment by caisq** [comment] 2019-02-12 15:35
Duplicate of https://github.com/tensorflow/tfjs/issues/410, which is fixed recently

**Closed by caisq** 2019-02-12 15:35 UTC
Labels: comp:core, comp:layers, comp:node.js, stat:awaiting response
