### ISSUE TITLE
[Codelab]: Making Predictions from 2D Data

### ISSUE THREAD

**Issue by stevenfox** [tensorflow/tfjs#1803] opened 2019-08-09 13:13 UTC
#1340 ## Describe the problem or feature request

### Syntactic error

Notably the argmax function is what gives us the index of the highest probability class. Remember that the model outputs a probability for each class. Here we find out the highest probability and **assign use** that as the prediction.

### Suggestion 

Notably the argmax function is what gives us the index of the highest probability class. Remember that the model outputs a probability for each class. Here we find out the highest probability and **assign** that as the prediction.

**Comment by rthadur** [comment] 2019-08-09 14:44
As this is not a bug or feature request , closing this issue.

**Closed by rthadur** 2019-08-09 14:44 UTC
