### ISSUE TITLE
String identifiers for losses, activations, etc. are not clearly documented in the API docs.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1315] opened 2019-03-04 20:36 UTC
See https://stackoverflow.com/questions/54980045/tensorflow-js-is-there-a-list-of-all-the-identifiers

`Model.compile` should inline all the loss types for you: https://js.tensorflow.org/api/0.15.3/#tf.Model.compile

**Comment by davidsoergel** [comment] 2019-03-06 18:58
This applies to activations too.

**Comment by davidsoergel** [comment] 2019-03-06 19:03
Oh yeah: also metrics, constraints, initializers, and regularizers.

Search for `type .*Identifier` in the tfjs-layers code to find all the definitions.

**Comment by emer7** [comment] 2019-03-13 03:34
Hi, I'm new to Tensorflow but would like to learn something new!
Is this issue available to be worked on?

**Comment by nsthorat** [comment] 2019-03-18 19:25
This one unfortunately might be a little involved so I'm going to take off the good first issue tag :)

**Comment by tafsiri** [comment] 2019-03-19 16:10
related to #680 #1171

**Comment by sbrl** [comment] 2021-01-14 16:24
Just currently falling over this. Are the string names for the loss functions in Tensorflow.js documented _anywhere_? I'm having some serious trouble trying to train a model for my PhD, because I can't get the right loss function. I thought at first that the loss function names would match [the documentation](https://js.tensorflow.org/api/latest/#Training-Losses), but apparently not.

It's rather awkward to use Tensorflow.js at all without any loss functions.

**Comment by davidsoergel** [comment] 2021-01-14 17:13
This is not exactly "documentation", and it's obviously not very easy to find, but at least it will solve your concrete problem now: https://github.com/tensorflow/tfjs/blob/f111dc03a87ab7664688011812beba4691bae455/tfjs-layers/src/keras_format/loss_config.ts#L16

Similarly, for other string identifiers (activations, metrics, constraints, initializers, and regularizers), see the neighboring files under https://github.com/tensorflow/tfjs/tree/master/tfjs-layers/src/keras_format.

In general these should match the string identifiers used for Python Keras.  For instance, https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy shows `name='categorical_crossentropy'`.  However, the TFJS implementations may not be up to date with the Python Keras ones (in particular, any new losses etc. added in the last year or two on the Python side are probably not implemented in TFJS yet).

**Comment by sbrl** [comment] 2021-01-14 17:35
Thanks so much, @davidsoergel! That's very helpful. It is no substitute for proper documentation, but it will be helpful to solve my immediate issue. Thanks again!

**Comment by sbrl** [comment] 2021-02-01 17:30
I've just tried the `sparse_categorical_crossentropy` one like this @davidsoergel:

```js
model.compile({
	optimizer: this.tf.train.adam(),
	loss: 'sparse_categorical_crossentropy',
	// These are guesses - we don't actually know just yet what they are called
	metrics: [ "accuracy", "categoricalCrossentropy", "categoricalAccuracy" ]
});
```

....but it crashes with the following error:

```
ValueError: Unknown loss sparse_categorical_crossentropy
    at new ValueError (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:186:28)
    at get (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:5177:15)
    at LayersModel.compile (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:8966:34)
    at Sequential.compile (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:10894:20)
    at TemporalCNN.reset (file:///path/to/project/common/ai/temporal_cnn/TemporalCNN.mjs:353:14)
    ....
```

If I try specifying `loss: this.tf.losses.sparseCategoricalCrossentropy` directly, then I get this error:

```
ValueError: When passing an Array as loss, it should have one entry per model output. The model has 1 output(s), but you passed loss=.
    at new ValueError (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:186:28)
    at LayersModel.compile (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:8958:23)
    at Sequential.compile (path/to/project/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:10894:20)
    at TemporalCNN.reset (file://path/to/project/common/ai/temporal_cnn/TemporalCNN.mjs:353:14)
```

....so I'm out of ideas.

**Comment by sbrl** [comment] 2021-02-02 16:01
It looks like `sparseCategoricalCrossentropy` is not actually exposed in `tf.losses`:

```
console.log(tf.losses);
{
  absoluteDifference: [Function: absoluteDifference__op],
  computeWeightedLoss: [Function: computeWeightedLoss__op],
  cosineDistance: [Function: cosineDistance__op],
  hingeLoss: [Function: hingeLoss__op],
  huberLoss: [Function: huberLoss__op],
  logLoss: [Function: logLoss__op],
  meanSquaredError: [Function: meanSquaredError__op],
  sigmoidCrossEntropy: [Function: sigmoidCrossEntropy__op],
  softmaxCrossEntropy: [Function: softmaxCrossEntropy__op]
}
```

....so I think there's another factor at play here and the file you linked to @davidsoergel doesn't accurately reflect the loss functions implemented?.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:32
Hi, @nsthorat

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:32 UTC
Labels: comp:layers, type:docs, stat:awaiting response
