### ISSUE TITLE
Missing op: MatrixBandPart

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1969] opened 2019-09-04 15:35 UTC
Reference from TensorFlow: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/matrix-band-part

This op is used by the [Music Transformer model](https://colab.sandbox.google.com/drive/1h2s1xkrVEm2MXPEdISfrhtBZrNZq9iNZ#scrollTo=PBngSJvP_En7&forceEdit=true&offline=true&sandboxMode=true).

**Comment by Kriyszig** [comment] 2019-10-04 09:33
Is this issue taken?
If not I can get an implementation ready by tomorrow hopefully!

**Comment by annxingyuan** [comment] 2019-10-04 11:41
@Kriyszig Fantastic! It's all yours :)

**Comment by DirkToewe** [comment] 2019-10-15 23:46
[PR#1520](https://github.com/tensorflow/tfjs-core/pull/1520) from January already implemented `tf.linalg.bandPart`. It is purely based on existing tfjs operations and, according to some quick and dirty benchmarks, it is around 10 times slower than a backend-based implementation, which should be acceptable for an `O(n²)` operation. I've taken the liberty to add [PR#2155](https://github.com/tensorflow/tfjs/pull/2155) to the benchmark [here](https://dirktoewe.github.io/tfjs-experiments/tfjs_bandPart_benchmark.html). PR#2155 currently seems to have some performance issues caused by the way that concat is used.

**Comment by Kriyszig** [comment] 2019-10-16 16:37
@DirkToewe, Can you port PR#1520 to this monorepo? Your implementation scales really well unlike mine.

**Comment by DirkToewe** [comment] 2019-10-16 19:44
Okay, will do as soon as I can.

**Comment by hrldcpr** [comment] 2020-02-06 21:30
Seems like this can be closed now, thanks to #2226?

**Comment by rthadur** [comment] 2021-08-11 04:42
Closing this issue as the related PR has been merged.

**Closed by rthadur** 2021-08-11 04:42 UTC
Labels: good first issue, comp:core
