### ISSUE TITLE
[WASM] Move xnn delete operator to a shared util that manages the count.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#2335] opened 2019-11-05 20:16 UTC
Right now each kernel manages its own disposal and count. Let's share this in backend.cc and we can also use unique_ptrs to dispose the xnn operators automatically.

**Comment by gaikwadrahul8** [comment] 2023-08-31 17:22
Hi, @nsthorat 

Apologize for the delayed response and I see https://github.com/tensorflow/tfjs/blob/84ee729089d9d2f31dc5ef4b52f3b15514bd478f/tfjs-backend-wasm/src/cc/backend.cc so just to confirm, have we taken care of this issue or not ?

CC :@pyu10055

If Am I missing something here please let me know ? Thank you!

**Comment by gaikwadrahul8** [comment] 2023-10-11 11:16
Hi, @nsthorat

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open. 

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:20
Hi, @nsthorat

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed** 2023-10-18 19:20 UTC
Labels: type:others, comp:wasm
