### ISSUE TITLE
Add tutorial on how to write serializable custom layers to js.tensorflow.org

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#674] opened 2018-09-04 13:52 UTC

**Comment by bionicles** [comment] 2019-09-02 23:20
Please!

**Comment by caisq** [comment] 2019-09-03 01:40
@bionicles Thanks for the feedback. Note that we already have at least two examples of serializable custom layers in the tfjs-examples repo:

1. In the `date-conversion-attention` example: https://github.com/tensorflow/tfjs-examples/blob/master/date-conversion-attention/model.js#L25. This example includes a custom layer called `GetLastTimestepLayer` that is saved with the its containing model and later loaded with it. 

2. In the `custom-layer` example: https://github.com/tensorflow/tfjs-examples/blob/master/custom-layer/custom_layer.js#L34. See the custom layer `Antirectifier`.

What's currently lacking is an example of a serializable custom layer with trainable weights. Is that what you are looking for, @bionicles ?

**Comment by cybermax-008** [comment] 2020-07-09 08:43
> @bionicles Thanks for the feedback. Note that we already have at least two examples of serializable custom layers in the tfjs-examples repo:
> 
> 1. In the `date-conversion-attention` example: https://github.com/tensorflow/tfjs-examples/blob/master/date-conversion-attention/model.js#L25. This example includes a custom layer called `GetLastTimestepLayer` that is saved with the its containing model and later loaded with it.
> 2. In the `custom-layer` example: https://github.com/tensorflow/tfjs-examples/blob/master/custom-layer/custom_layer.js#L34. See the custom layer `Antirectifier`.
> 
> What's currently lacking is an example of a serializable custom layer with trainable weights. Is that what you are looking for, @bionicles ?

Hi,
@caisq can you please answer the question posed by you in the above comment. 
In my model.json (converted from Keras model after slicing only a part of it's weights) ], there are some layers, `TensorFlowOpLayer` created due to the operations like slicing, reshape and stack. There are total of 9 layers corresponding to the classname : `TensorFlowOpLayer`. 
Further, we created 9 custom layers with same `static get className` (TensorFlowOpLayer). 

Unfortunately, While loading the converted model.json in tfjs using `loadLayersModel` , I get the error, which I mentioned in this issue raised by me earlier #3566. 

And I found all those layers are `trainable` later from going through the model.json. 

So, what do you think? does the error is due to the fact it is `trainable` ? Any inputs on this will be helpful !

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:14
Hi, @caisq 

I apologize for the delayed response and I see source code https://github.com/tensorflow/tfjs-examples/blob/master/custom-layer/custom_layer.js#L34 where we implemented custom layer class is to support serialization if I'm not wrong

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:40
Hi, @caisq 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:40 UTC
Labels: comp:layers, type:docs, P3, stat:awaiting response
