### ISSUE TITLE
Generalize trick in pointwiseConv to avoid expensive reshaping.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1336] opened 2019-03-06 22:17 UTC
In `convWithMatMul` (pointwiseConv), if `x` has an odd number of rows and so will need to be expensively reshaped, we pretend that `x` has an even number of rows temporarily, run the kernel, then restore `x`'s shape. This logic should be moved to `compileAndRun` so other kernels can avoid expensive reshapes.

**Comment by gaikwadrahul8** [comment] 2023-10-11 12:59
Hi, @annxingyuan 

I apologize for the delayed response and I see this PR https://github.com/tensorflow/tfjs-core/pull/1610 got merged so May I know have we taken care of this issue or not ? 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:32
Hi, @annxingyuan 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:32 UTC
Labels: comp:core, type:performance, stat:awaiting response
