### ISSUE TITLE
Save tensors from react-native cameraWithTensors api to jpeg

### ISSUE THREAD

**Issue by ClementWalter** [tensorflow/tfjs#4001] opened 2020-10-01 10:42 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using):

    "@tensorflow/tfjs": "2.0.0",
    "@tensorflow/tfjs-backend-webgl": "2.0.0",
    "@tensorflow/tfjs-core": "2.0.0",
    "@tensorflow/tfjs-react-native": "0.3.0",

- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently when using the `cameraWithTensor` HOC one can handle directly the underlying tensor to make e.g. real-time prediction. It would be nice to be able to store the stream of tensors as jpeg or video for instance for later use or visualization.

I have created a repo to showcase my currently unsuccessful attempts: https://github.com/ClementWalter/tfjs-expo-example

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by tafsiri** [comment] 2020-10-01 15:07
@ClementWalter Thanks for your request. Quick question about the code in the repo you posted. What is the goal of this line? https://github.com/ClementWalter/tfjs-expo-example/blob/13b552720d11d7a0be02eef2a26d7253cefe968a/utils.js#L9 What shape tensor to you get from that operation?

I guess it would be nice to know if the issue is with the tensor data or with the jpeg encoding/file writing. Are you able to write a synthetic image to disk and have it appear as expected (e.g. a gradient or something similar that can be created programatically)?

**Comment by ClementWalter** [comment] 2020-10-02 15:37
Ok so there were two things:

 - actually the `encodeJpeg(tensor)` was wrong because
    - I mixed channels and pixels order
    - I was adding a 4th channel in case tensor only had 3 but not stacking a channel full of 255 but copying  the red channel of the input tensor (the link you mentionned)
 - I was using `Dimensions.height` and `Dimensions.width` for the `cameraTexture(Height|Width)` and it cropped the image. Indeed I had to use your magic number from https://github.com/tensorflow/tfjs/blob/master/tfjs-react-native/integration_rn59/components/webcam/realtime_demo.tsx to have this work.

Things that are still unclear to me:
 - where does these numbers (1920 x 1080 for iOs) come from?
 - why the `GLView.takeSnapshotAsync(gl, {rect: {x: 0, y: 0, width: 1080, height: 1920}})` still crops the image a bit?

And eventually but not related to this encodeJpeg feature: wether to use the `autorender` props or call the `updatePreview` and `gl.endFrameEXP`.

**Comment by 0xori** [comment] 2020-10-12 12:47
Hi @ClementWalter Have you managed to get it done?
I'm facing the same problem, trying to save a jpeg from the stream.

**Comment by ClementWalter** [comment] 2020-10-12 12:52
yes! actually if you go to https://github.com/ClementWalter/tfjs-expo-example/blob/master/utils.js the function does the job. I will try to push it as a contrib to tfjs-react-native very soon. However, as I have said above, I don't really understand the magic numbers used for width and height in the `cameraWithTensor` module.

**Comment by 0xori** [comment] 2020-10-12 13:20
perfect! thanks!
tried your code, it works but for some reason I'm getting the jpeg with extra black padding.
for your question, as far as I understand the "magic numbers" comes from the [docs](https://js.tensorflow.org/api_react_native/0.3.0/#cameraWithTensors). 

>  Currently expo does not support automatically determining the
>  resolution of the camera texture used. So it must be determined
>   empirically for the supported devices and preview size.

**Comment by ClementWalter** [comment] 2020-10-12 13:23
But is it just iOs VS Android or does it depend on the device as well? Because I have noticed that if they are too small for instance, then the image is cropped. Maybe it is the reason why you get black padding, because they are too big for your device

**Comment by 0xori** [comment] 2020-10-14 08:24
I'm assuming it depends on the device. you can actually get the device available picture sizes. take a look at [expo-camera docs](https://docs.expo.io/versions/latest/sdk/camera/#getavailablepicturesizesasync).
when I'm changing the dimensions according to the results, I'm getting better capture proportions.

**Comment by gaikwadrahul8** [comment] 2023-05-03 09:42
Hi, @ClementWalter 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now so I see your previous comment and you mentioned you would do contribution for this feature request so May I know have you contributed for this feature request or not ? if yes please feel free to close this issue ?

If this feature haven't implemented as of now then May I know are you still looking for this feature in TFJs ?

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2 ](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md). Thank you!

**Closed** 2023-05-17 10:15 UTC
Labels: type:feature, stat:awaiting response, stat:contributions welcome, stalled
