### ISSUE TITLE
Not able to run model on HTMLImageElement

### ISSUE THREAD

**Issue by ritikrishu** [tensorflow/tfjs#1242] opened 2019-02-14 10:51 UTC
#### TensorFlow.js version
0.15.1
#### Browser version
Chrome 71.0.3578.98
#### Describe the problem or feature request
when I try to run `model.detect` on a remote image. It says,
```
Could not write to TensorArray index 0,
          because the value dtype is int32, but TensorArray dtype is float32.
```
However, if I serve the image from a localhost server, it works.
#### Code to reproduce the bug / link to feature request
```
async function init(){
      const model = await cocoSsd.load('mobilenet_v2');
      let img1 = new Image()
      // to bypass cross origin issue
      img1.src = `https://i.imgur.com/xFWR5e4.jpg?${Date.now()}`
      img1.crossOrigin = ""
      img1.onload = async function(){
		img1 = tf.image.resizeBilinear(tf.fromPixels(img1), [400, 400]);
                const result = await model.detect(img1);
      }
}
```
https://jsfiddle.net/rszv6a70/28/

**Comment by ritikrishu** [comment] 2019-02-14 10:58
Also does not works with local file system images, unless I serve them via localhost as well.

**Comment by tafsiri** [comment] 2019-02-15 15:45
I can confirm that I can reproduce the bug and it seems to be a regression between 0.14.1 and 0.14.2

@ritikrishu You can change the script tag that loads tfjs in your program to `<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.14.1/dist/tf.min.js"> ` as a workaround in the meantime.

cc @pyu10055

**Comment by ritikrishu** [comment] 2019-02-15 18:43
@tafsiri thanks, bro! you saved my day ❤️

**Comment by dsmilkov** [comment] 2019-03-06 07:00
This is fixed in https://github.com/tensorflow/tfjs-core/pull/1577 as part of 1.0

**Closed by dsmilkov** 2019-03-06 07:00 UTC
Labels: comp:models, type:bug
