### ISSUE TITLE
Not working on Safari; Freezing/Weird behavior

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#2063] opened 2019-09-18 19:05 UTC
I am having problems with using tensorflow.js on safari such as here https://emojiscavengerhunt.withgoogle.com. I didn't need to test my project without safari but it is still not working and now I need it. This is what happens when I use it on safari but it works fine on chrome. https://drive.google.com/file/d/1YCni_rY2zmmL0hkOJAx09_cdeKR-0Ri9/view. Version 12.1.1 (14607.2.6.1.1) of safari. mac 10.14.5 I don't particularly care about this game but I see the same issue in one of my projects so figured if we can figure the problem out here, we can figure out the problem in my project.

I had raises an issue a while ago but never really followed up.

**Comment by rthadur** [comment] 2019-09-18 22:05
this is a duplicate of #1174 , please use #1174  with latest findings , thank you

**Closed by rthadur** 2019-09-18 22:05 UTC
