### ISSUE TITLE
Kaggle integration.

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1028] opened 2018-08-31 17:38 UTC
We have an email thread with the Kaggle folks from April explaining how to download data via direct HTTP requests to their API.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:42
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:42 UTC
Labels: type:feature, stat:awaiting response, comp:data
