### ISSUE TITLE
NCHW Support for conv2d on loaded Frozen Model

### ISSUE THREAD

**Issue by GolemXlV** [tensorflow/tfjs#1648] opened 2019-06-02 13:56 UTC
#### TensorFlow.js version
1.0.0-alpha2, 1.1.2
#### Browser version
latest
#### Describe the problem or feature request
Hello there!
I'm trying to load graph model in js browser and make a predict on tensor (1, 512). Model is loaded successfully, but on predict i received an error:
conv2d: depth of input (4) must match input depth for filter 512.
Looks like, the problem is an unsupported NCHW data format in conv2d.
![Screenshot from 2019-06-02 17-51-57](https://user-images.githubusercontent.com/22293035/58762243-4f47be80-855f-11e9-8d71-f70fc066be80.png)

![Screenshot from 2019-06-02 17-54-40](https://user-images.githubusercontent.com/22293035/58762284-933ac380-855f-11e9-9123-705c742f3f06.png)

#### Code to reproduce the bug / link to feature request
[model.json](https://gist.github.com/GolemXlV/c6fb098ec3fe59c144c2ed6329f336cc)

**Comment by rthadur** [comment] 2019-06-03 17:19
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by GolemXlV** [comment] 2019-06-03 20:25
@rthadur but can you give me any feedback about NCHW support in conv2d op? I didn't found any notes about this in documentation.

**Comment by tafsiri** [comment] 2019-06-03 21:49
I'm going to re-open this as it is a potential feature request. As per the [API docs](https://js.tensorflow.org/api/latest/#conv2d) NCHW is not currently supported in tf.conv2d (only NHCW). But we would be open to PRs to add support for that format. The code for [conv2d is here](https://github.com/tensorflow/tfjs-core/blob/ef1e1018fbc6e3fa559e6e3ad92b2a4da2f7fc8d/src/ops/conv.ts#L145).

**Comment by tafsiri** [comment] 2019-06-03 21:50
I'll note that the issue is not specific to frozen models.

**Comment by syt123450** [comment] 2019-06-14 20:20
Hi @tafsiri , I sent a PR [tensorflow/tfjs-core#1791](https://github.com/tensorflow/tfjs-core/pull/1791) to make conv2d support `NCHW` dataFormat, could you please take a look at it? Thanks!

**Comment by rthadur** [comment] 2020-03-17 17:11
Related PR has been merged, thank you all.

**Closed by rthadur** 2020-03-17 17:11 UTC
Labels: comp:core, stat:contributions welcome, type:feature
