### ISSUE TITLE
tfjs-node size exceeds in aws lambda

### ISSUE THREAD

**Issue by saumilsdk** [tensorflow/tfjs#2817] opened 2020-03-04 07:17 UTC
TFJS Node Version
"@tensorflow/tfjs-node": "^1.5.2"

Problem:
Unable to use tfjs-node while deploying serverless project.

> Function exceeds the maximum allowed size of 262144000 bytes. The actual size is 368100943 bytes.

**Comment by rthadur** [comment] 2020-03-04 17:01
Closing this as this a duplicate of #2809 , we can the track the issue there. Thank you

**Comment by rthadur** [comment] 2020-03-04 17:13
This will be a feature request , thank you

**Comment by kangyizhang** [comment] 2020-03-04 19:50
The tfjs-node library is depending on tensorflow c library, which is ~300MB. It's even bigger for gpu version. There is no way to reduce the library size dramatically. You will need to increase the size limit of your serverless environment.

**Closed by kangyizhang** 2020-03-04 19:50 UTC
Labels: P1, comp:node.js, type:feature
