### ISSUE TITLE
tf-core.esm.js : unknown dtype bool

### ISSUE THREAD

**Issue by 116050423** [tensorflow/tfjs#553] opened 2018-07-27 10:26 UTC
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tensorflowjs_converter --version
Using TensorFlow backend.

tensorflowjs 0.5.4

Dependency versions:
keras 2.1.6
tensorflow 1.9.0

#### Browser version
N/A

#### Describe the problem or feature request
I use the latest tensorflowjs_converter(build from source code, so virtually it's 0.5.5) to convert below Object Detection models, then use tfjs to load the converted model, but failed
The reproduce procedure is simple.
Converte ssd_mobilenet_v1_coco_2018_01_28 and then load it. Then you can see the error.
Download from model zoo, url is:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

The converter has just support dtype bool in 0.5.5, maybe  tf core haven't support now?

#### Code to reproduce the bug / link to feature request

tf-core.esm.js:227 Uncaught (in promise) Error: Weight Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater has unknown dtype bool.
at eval (tf-core.esm.js:227)
at Array.forEach ()
at eval (tf-core.esm.js:227)
at Array.forEach ()
at Object.eval (tf-core.esm.js:227)
at eval (tf-core.esm.js:227)
at Object.eval [as next] (tf-core.esm.js:227)
at i (tf-core.esm.js:227)

**Comment by dsmilkov** [comment] 2018-07-30 00:02
Duplicate of #550. See https://github.com/tensorflow/tfjs/issues/550#issuecomment-408715309

**Closed by dsmilkov** 2018-07-30 00:02 UTC
