### ISSUE TITLE
Error in clip: min (0) must be less than or equal to max ([object Object]) for Retrained tf.Keras MobileNet

### ISSUE THREAD

**Issue by rajeev-tbrew** [tensorflow/tfjs#908] opened 2018-11-14 12:17 UTC
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.13.2
#### Browser version
Version 70.0.3538.102 (Official Build) (64-bit)
#### Describe the problem or feature request
Re-Trained a Mobilenet model (alpha=0.25) on new data and model predicts with no issues in tf.keras. Converted the model to tfjs. But getting the following error when doing the prediction in Web (model loading has no issues).
#### Code to reproduce the bug / link to feature request
![image](https://user-images.githubusercontent.com/38608333/48481925-3252d480-e835-11e8-9cb6-c1454f03781c.png)

**Comment by tafsiri** [comment] 2018-11-14 14:29
cc @caisq @pyu10055

**Comment by caisq** [comment] 2018-11-14 15:41
@rajeev-tbrew The fact that "max" shows up as "([object Object])", instead of a number, looks suspicious. Is it possible for you to share the model JSON with us? I think we should be able to reproduce this issue by just using the JSON, and the weights are not necessary. Thanks.

**Comment by rajeev-tbrew** [comment] 2018-11-15 10:03
@caisq Here is the model JSON file. Thanks a lot for your help

[model.zip](https://github.com/tensorflow/tfjs/files/2584691/model.zip)

**Comment by rajeev-tbrew** [comment] 2018-11-15 10:03
Sorry, clicked on by mistake

**Comment by rajeev-tbrew** [comment] 2018-11-19 08:54
Folks

Is there an update on the same. Thanks.

Regards
Rajeev

**Comment by caisq** [comment] 2018-11-19 18:14
@nsthorat Can you take a look at this? This seems to be an issue in the tfjs-core function clipByValue. It doesn't allow min and max to be equal. But the corresponding function in TensorFlow (tf.clip_by_value) allows them to be equal.

**Comment by caisq** [comment] 2018-11-19 18:16
@nsthorat Scratch that. What I said about tf.cipByValue was not true. I'll investigate this further.

**Comment by caisq** [comment] 2018-11-20 14:53
After some investigation, I found the error happens because the `max_value` property of some ReLU activations in the network is saved as `{"value":6,"type":"ndarray"}`, instead of a plain number (`6`). 

@fchollet Is this a recent change in tf.keras? Is there a reason why `max_value` of the relu layer is stored as an object instead of a plain number?

**Comment by caisq** [comment] 2018-11-20 14:56
@rajeev-tbrew 

As a temporary & hacky workaround, you can replace all instance of `{"value":6,"type":"ndarray"}` with `6` in your model.json.

**Comment by YajJackson** [comment] 2018-11-20 18:38
@caisq I ran into this issue as well. my model.json held `{"type":"ndarray", "value":6}`, and replacing all instances with 6 seems to fix the issue.

**Comment by rajeev-tbrew** [comment] 2018-11-22 07:50
Thank you @caisq !!!

The temporary workaround has solved the issue.

**Comment by rthadur** [comment] 2018-11-26 18:40
Closing this issue as this was resolved.

**Comment by caisq** [comment] 2019-01-27 05:06
Will push a thorough fix to this issue soon.

**Closed** 2019-01-29 03:45 UTC
Labels: comp:converter, comp:layers, stat:awaiting response
