### ISSUE TITLE
Cannot create tensor from Uint8ClampedArray

### ISSUE THREAD

**Issue by jameswex** [tensorflow/tfjs#374] opened 2018-06-01 19:47 UTC
#### Describe the problem or feature request

tf.tensor constructors can be provided a TypedArray, but not a Uint8ClampedArray, even though Uint8ClampedArray is a TypedArray.

**Comment by dsmilkov** [comment] 2018-10-24 20:32
Duplicate of https://github.com/tensorflow/tfjs/issues/757

**Closed by dsmilkov** 2018-10-24 20:32 UTC
Labels: core
