### ISSUE TITLE
Converter should not call backend-specific readSync method as part of getting parameter values during model hydration.

### ISSUE THREAD

**Issue by annxingyuan** [tensorflow/tfjs#1595] opened 2019-05-21 16:50 UTC
Instead the converter should either:

1) allow core operations to take tensors or numbers (TensorLike) where it can, or 
2) the model should become async if it needs a param value that is the result of another operation

Also, if we have the value on the CPU from weights directly and we can’t make it a tensor then we should just use that.

cc @nsthorat

**Comment by nsthorat** [comment] 2019-05-21 16:52
Ping, this is going to be a launch blocker for WebGPU, WASM, and other async backends. We should try to prioritize this when you get a chance.

**Comment by pyu10055** [comment] 2019-05-21 20:25
the engine should read from the correct backend based on the tensor location:
  readSync(dataId: DataId): DataValues {
    // Route the read to the correct backend.
    const info = this.state.tensorInfo.get(dataId);
    return info.backend.readSync(dataId);
  }

**Comment by pyu10055** [comment] 2019-05-21 20:32
Investigated the posenet issue, notice only it is due to TFJS tf.pad op, the padding param is number array, in TF the param is a tensor.

**Comment by nsthorat** [comment] 2019-05-21 21:48
Future backends will not have `dataSync()` at all, we should avoid all calls to `dataSync()` in the converter by any of the 3 approaches outlined in the original issue.

Great, can we fix that for the pad op for now and then fix this more generally by removing all calls to `dataSync()`?

**Comment by pyu10055** [comment] 2019-05-21 23:15
There are several other ops that requires number or number[] for input tensors

|op| params|
|===|===|
Prod|axes
Conv2DBackpropInput| outputShape
Fill| shape, value
LinSpace| start, stop, num
OneHot| depth, onValue, offValue
Ones| start
RandomUniform| shape
Range| start, stop, step
TruncateNormal| start
Zeros| start
NonMaxSuppressionV2/V3|naxOutputSize, iouThreshold, scoreThreshold
ResizeBilinear|size
ResizeNearestNeighbor|size
CropAndResize|cropSize
Transpose|perm
SparseToDense|outputShape
Max/Min/Mean/Sum/All/Any/ArgMax/ARgMin/Prod|axis
ConcatV2/Concat/GatherV2/ReverseV2|axis
Slice|begin, size
stridedSlice|begin, end, strides
Tile|reps
Split|axis
SplitV|axis, numOrSizeSplits
ScatterNd|shape
SparseToDense|outputShape
ExpendDims|axis
Pad|padding
Reshape|shape
SpaceToBatchND|blockShape, padding
BatchToSpaceND|blockShape, crops

**Comment by nsthorat** [comment] 2019-05-21 23:22
Great table! Some of these ops in core can be modified to take Tensor. Ones that fundamentally take number should be considered making the model async.

At the end of the day, no dataSync should ever be called by the converter.

**Comment by pyu10055** [comment] 2019-05-22 00:45
Can you explain why can other backend support cannot have readSync, webgl fundamentally does not readSync either, it is a js blocking call. 
Having a readSync method would be very useful in eager mode and console.

**Comment by nsthorat** [comment] 2019-05-22 00:55
For the WebAssembly backend we will be running it in a WebWorker, which only has async readbacks.

WebGPU is the same — it just happens to be that we can dataSync in a subset of cases where we haven’t yet uploaded to the GPU (but this is an implementation detail that should not be exposed, we will not in the long run support any dataSync in WebGPU).

**Comment by nsthorat** [comment] 2019-05-22 00:58
As an aside, is it bad to call dataSync even on the WebGL backend as it will block the UI thread.

**Comment by gaikwadrahul8** [comment] 2023-10-11 12:43
Hi, @annxingyuan 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:27
Hi, @annxingyuan 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:27 UTC
Labels: comp:converter, type:others, stat:awaiting response
