### ISSUE TITLE
Unknown layer: Dot

### ISSUE THREAD

**Issue by jscriptcoder** [tensorflow/tfjs#738] opened 2018-09-27 08:16 UTC
Hi there, 

I've seen an issue reported a while ago, https://github.com/tensorflow/tfjs/issues/218, where this "Unknown layer: Dot" was mentioned, but there was no a clear solution. Besides the error message seems to be different in my case:

"Uncaught (in promise) Error: Unknown layer: Dot. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass()."

I'm using **TensorFlow.js 0.13.1**, in **Chrome 68**

The keras model trained can be found here: https://github.com/jscriptcoder/date-translator/tree/master/jupyter, `dates_model.h5` file, and the converted model is here: https://github.com/jscriptcoder/date-translator/tree/master/tfjsmodel. The Jupyter notebook with the training is here: https://bit.ly/2Oc14Ce.

I'm using **Tensorflow 1.10.0** as backend and **Keras 2.2.2**. To convert the model I used **Tensorflowjs 0.6.0**.

Now, the error message seems to be quite clear when it says: "_The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code_", in that case the question is, how can I do so?

Thanks a lot,
Fran

**Comment by caisq** [comment] 2018-09-27 20:59
This is a duplicate of #218

**Closed by caisq** 2018-09-27 20:59 UTC
Labels: layers
