### ISSUE TITLE
IIS Serves model incorrectly with causing inputcheck to fail

### ISSUE THREAD

**Issue by Neuroforge** [tensorflow/tfjs#586] opened 2018-08-08 06:29 UTC
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
TensorFlow 0.6.1

#### Browser version
Crhome 67 Windows

#### Describe the problem or feature request

When running my model on MacOS it works fine.

When running under Windows the checkInput fails with a mismatch.

Running locally under MaCOS - Input is "image"
Running locally under Windows - Input is "ModelName/image"

Served from IIS to MacOS - Input is "ModelName/Image"
Served from IIS to Windows - Input is "ModelName/Image"

#### Code to reproduce the bug / link to feature request

```
	GraphExecutor.prototype.checkInput = function (inputs) {
        var _this = this;
        var inputKeys = Object.keys(inputs);
        var missing = [];
        var extra = [];
        this.placeholders.forEach(function (name) {
            if (inputKeys.indexOf(name) === -1)
                missing.push(name);
        });
        inputKeys.forEach(function (name) {
            if (_this.placeholders.indexOf(name) === -1)
                extra.push(name);
        });
        if (missing.length > 0) {
            throw new Error("Missing input placeholders: " + missing);
        }
        if (extra.length > 0) {
            throw new Error("Extra input tensors: " + extra);
        }
```

**Comment by pyu10055** [comment] 2018-08-08 20:33
This is interesting, did you convert the python model in windows or macOS? 
the input name should be internal to the model file, the name should not be changed by the serving mechanism.

Can you share the model with us, so we can reproduce?

**Comment by Neuroforge** [comment] 2018-08-08 21:15
The model was converted in MacOS.

The files are all on this page. You can see the error here....
https://www.john-daniel-bell.com/TFDemo

Model files are here....
https://www.john-daniel-bell.com/data/tensorflowjs_model.pb
https://www.john-daniel-bell.com/data/group1-shard1of2
https://www.john-daniel-bell.com/data/group1-shard2of2

**Comment by pyu10055** [comment] 2018-08-11 05:32
@Neuroforge I checked your tensorflowjs_model.pb file, its place holder name is:
TfPoseEstimator/image
and your website loads the model fine with my mac.
Looks like only serving the model locally with mac would have a different placeholder name?

**Comment by Neuroforge** [comment] 2018-08-11 05:35
The issue is that the name is different in these two cases.

Running locally on a Mac works.

When it is served then this error arises.

Unhandled Promise Rejection: Error: Missing input placeholders:
TfPoseEstimator/image

Not sure how to solve this and why it should be different.

**Comment by pyu10055** [comment] 2018-08-13 19:55
@Neuroforge before we figure out why the model input name is changed in different envs, the inference API actually does not require you to provide the place holder name.

`predict(
      inputs: tfc.Tensor|tfc.Tensor[]|tfc.NamedTensorMap,
      config?: tfc.ModelPredictConfig): tfc.Tensor
      |tfc.Tensor[]|tfc.NamedTensorMap`

you can run 
`const outputMap = frozenModel.predict(inputTensor);`

**Comment by rthadur** [comment] 2018-11-28 22:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2018-11-28 22:03 UTC
Labels: Windows, comp:converter, comp:core
