### ISSUE TITLE
Provide API allow user to use http request with headers in Node

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1002] opened 2018-09-27 20:17 UTC
urlDataSource and urlChunkIterator accepts string and browser Request object as source in Browser env. In node it only accept string. We need to allow user use http request in node env.

**Comment by bileschi** [comment] 2019-02-07 17:12
The Request object API should also be threadded up to tf.data.csv.  The current implementation only supports string URLs, correct?

**Comment by davidsoergel** [comment] 2019-02-07 17:58
tf.data.csv() should indeed accept Requests; https://github.com/tensorflow/tfjs-data/pull/135 should fix that.  

This bug is specifically about Node, though, IIUC.

**Comment by bileschi** [comment] 2019-02-07 18:45
Thanks

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:00
Hi, @kangyizhang 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:38
Hi, @kangyizhang 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:38 UTC
Labels: type:feature, P3, stat:awaiting response, comp:data
