### ISSUE TITLE
yarn build-deps under tfjs-backend-webgpu failed

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5420] opened 2021-08-03 01:59 UTC
With https://github.com/tensorflow/tfjs/pull/5416 applied. There are still two issues when run yarn build-deps under tfjs-backend-webgpu on Windows:
1. The command line is too long
```
ERROR: /build/tfjs/tfjs-core/src/BUILD.bazel:44:16: Action tfjs-core/src/tests.ts failed: (Exit 1): enumerate_tests_bin.bat failed: error executing command bazel-out/host/bin/tools/enumerate_tests_bin.bat -r tfjs-core/src -o bazel-out/x64_windows-fastbuild/bin/tfjs-co
re/src/tests.ts tfjs-core/src/browser_util_test.ts tfjs-core/src/buffer_test.ts ... (remaining 244 argument(s) skipped)
The command line is too long.
Target //tfjs-core:tfjs-core_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
2.  There is a typo here:
```
+++ b/link-package/package.json
@@ -6,7 +6,7 @@
   "license": "Apache 2.0",
   "private": true,
   "scripts": {
-    "build": "yarn build-backend-cpu && yarn build-backend-webgo && yarn build-core && yarn build-tflite && yarn reinstall",
+    "build": "yarn build-backend-cpu && yarn build-backend-webgl && yarn build-core && yarn build-tflite && yarn reinstall",
```

**Comment by mattsoulanille** [comment] 2021-08-03 14:46
1. The "command line is too long" error is caused by the new [enumerate_tests rule](https://github.com/tensorflow/tfjs/pull/5361/files#diff-7ead6c2057626da9b8cec1097fc4325f10355b6dfcfca60bf643e94bb96bc701R12-R17). This rule passes the path of every test file as an argument. I'll work on a fix for this by [writing the test file paths to a file](https://docs.bazel.build/versions/main/skylark/lib/actions.html#write) instead of passing them in command line arguments.

2. Typo is fixed by #5419 (thanks @qjia7)!

**Closed** 2021-08-03 18:14 UTC
Labels: bazel, type:build/install
