### ISSUE TITLE
Add WASM backend

### ISSUE THREAD

**Issue by nebrelbug** [tensorflow/tfjs#1497] opened 2019-04-05 02:51 UTC
#### TensorFlow.js version
1.0.4
#### Browser version
Chrome 73
#### Describe the problem or feature request
Has there been any further discussion about using WASM to optimize performance? I noticed there was discussion in #36, but it was decided to wait and eventually `tfjs-node` was created.

**Possible Benefits of WASM**
- Run in any WASM environment
- Maybe higher speed than WebGL if users have slow graphics?

**Comment by dsmilkov** [comment] 2019-04-05 17:52
Hi, thanks for filing this issue. A WASM backend is in our roadmap for this quarter. We can use this issue for updates.

**Comment by startupgurukul** [comment] 2019-04-07 00:22
Folks at intel have been making webml/webnn and recently made some amazing strides of hitting 31fps    running coco SSD models. 

https://github.com/intel/webml-polyfill/issues/650#issuecomment-475127456

 you already know about them as mentioned about them during TF summit, really looking forward for WASM backend in this quarter :)

**Comment by startupgurukul** [comment] 2019-05-27 00:37
Hi folks update on this, curious to see the performance compared to tflite and tensorflow

**Comment by dsmilkov** [comment] 2019-05-29 21:19
Thanks for the reference. We are closely following the amazing work that Intel has done, led by @huningxin. Our wasm backend will most likely not be able to reach that level of performance since we won't be able to access hardware acceleration beyond SIMD 128bit.

We will start developing our WASM backend in the open, on GitHub very soon. Stay tuned!

**Comment by huningxin** [comment] 2019-05-30 05:42
Thanks for the update @dsmilkov . As you know, [webml-polyfill](https://github.com/intel/webml-polyfill) currently reuses tfjs-core WebGL kernels for [GPU implementation](https://github.com/intel/webml-polyfill/tree/master/src/nn/webgl) and compiles tf-lite kernels to WASM for [CPU implementation](https://github.com/intel/webml-polyfill/tree/master/src/nn/wasm/src). It's a great news that tfjs will have a WASM backend soon. It would simplify the webml-polyfill and benefit the [webnn spec](https://webmachinelearning.github.io/webnn/) development. Highly looking forward to that.

**Comment by chirva-ivan** [comment] 2019-08-13 09:34
Hey, guys. Are there any updates on this issue?

**Comment by dsmilkov** [comment] 2019-08-13 13:55
We just started by adding the framework (skeleton) code around it: https://github.com/tensorflow/tfjs-core/pull/1863 We will be slowly ramping up on this.

**Comment by camsjams** [comment] 2019-09-05 18:25
While fully understanding that this a new and still experimental backend, are you planning on publishing to npm?

**Comment by dsmilkov** [comment] 2019-09-06 17:32
We are still very early in the process so publishing something to npm is not useful at this time. I'll ping this issue when we have more updates.

**Comment by bhack** [comment] 2019-09-20 13:48
For out of browser WASI I just opened https://github.com/tensorflow/mlir/issues/140 in the MLIR repo.

**Comment by rthadur** [comment] 2019-10-15 01:19
This has been done and should be available in latest releases.Thank you.

**Comment by tiziano88** [comment] 2019-10-15 10:17
Great news! Which release has now Wasm support? And are there any instructions about it? Looking forward to trying it out.

**Comment by nsthorat** [comment] 2019-10-15 11:47
This is actually still in progress we’ll update this when we’re ready to release :)

**Comment by Annaero** [comment] 2019-11-08 14:59
> This is actually still in progress we’ll update this when we’re ready to release :)

Hello, do you have any updates?

**Comment by dsmilkov** [comment] 2019-12-05 20:28
Hi all,

We are excited to share that we just released our first alpha release of the WASM backend.
See the [README.md](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/README.md) in the `tfjs-backend-wasm` folder for how to use it. At this point we have about ~30 kernels - see [all_kernels.ts](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/src/kernels/all_kernels.ts#L21) for the list.

We would love to get your feedback, testing, and help as we are polishing towards a general release!

Thanks!

**Comment by dsmilkov** [comment] 2019-12-05 20:29
Closing this issue since it's a general issue tracking our WASM release. Feel free to file separate issues if you run into problems.

**Closed by dsmilkov** 2019-12-05 20:28 UTC
Labels: comp:wasm, type:feature

**Comment by whatevergeek** [comment] 2019-12-05 20:57
Thanks @dsmilkov 
This is great news.

**Comment by bhack** [comment] 2019-12-05 20:57
@dsmilkov Are you involved as team in https://bytecodealliance.org/?

**Comment by camsjams** [comment] 2019-12-05 23:09
There appears to be a directory called `wasm-out` missing in the published npm version, I get an error:
```
Module not found: Error: Can't resolve '../wasm-out/tfjs-backend-wasm' in '/var/www/node_modules/@tensorflow/tfjs-backend-wasm/dist'
```

Here is a screenshot of installed items:
![image](https://user-images.githubusercontent.com/833485/70281945-2b18a480-1771-11ea-85e1-0d60ea9ebcfe.png)

**Comment by dsmilkov** [comment] 2019-12-05 23:29
Thanks for finding that out. We just released `1.4.0-alpha2` with the fix. Let us know how it goes.

**Comment by camsjams** [comment] 2019-12-05 23:52
@dsmilkov Thanks! Is this published to npm as well?

**Comment by camsjams** [comment] 2019-12-06 00:24
It looks to be working so far in the sense that our application hasn't crashed or thrown errors. I will you know how it goes :+1:

**Comment by startupgurukul** [comment] 2019-12-06 00:40
Great new congrats on alpha, 

Cameron, pls do share the performance improvements you notice during your experiments with wasm backend.

**Comment by chirva-ivan** [comment] 2019-12-06 12:37
Did everything following the example from README and got an error. Do I need some special build of tfjs-core? Any Ideas? 

![Screenshot from 2019-12-06 15-30-44](https://user-images.githubusercontent.com/18259976/70323312-84e6a080-183d-11ea-8e41-0305af502265.png)

**Comment by nsthorat** [comment] 2019-12-06 14:46
@chirva-ivan which browser are you using? If you open the initialization error what does it say?

**Comment by chirva-ivan** [comment] 2019-12-06 15:27
@nsthorat using Chrome 78
![Screenshot from 2019-12-06 18-26-16](https://user-images.githubusercontent.com/18259976/70334182-faf70180-1855-11ea-9fd3-de7636c34a5f.png)

**Comment by nsthorat** [comment] 2019-12-06 15:37
@chirva-ivan is it possible for you to stand up a demo for us to look at?

**Comment by dsmilkov** [comment] 2019-12-06 15:38
Are you using Parcel? Can you share a small project/build script that we can reproduce? Thanks!

**Comment by yashints** [comment] 2019-12-09 00:43
Here is a codesandbox with above error

https://codesandbox.io/s/naughty-montalcini-s0gjk

**Comment by yashints** [comment] 2019-12-10 23:34
@dsmilkov I am still getting the error in the browser, was the fix just for node?

**Comment by dsmilkov** [comment] 2019-12-14 20:43
I just sent https://github.com/tensorflow/tfjs/pull/2559 for review where I document how to use the WASM backend with bundlers and also added starter projects for webpack and parcel. See [update readme from the PR](https://github.com/tensorflow/tfjs/tree/9c11267db3f3562756440450945a4801d80d2690/tfjs-backend-wasm#using-bundlers).
