### ISSUE TITLE
[Doc generator] fileName is broken.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#364] opened 2018-05-30 20:52 UTC
_From @nsthorat on March 21, 2018 14:22_

It currently just contains the lineNumber.

_Copied from original issue: tensorflow/tfjs-website#35_

**Comment by tafsiri** [comment] 2018-05-30 20:52
nice to fix. though i've also stopped using the filename in the template so i don't think this is urgent. (i still use the link)

**Comment by tafsiri** [comment] 2018-05-30 20:52
_From @nsthorat on March 23, 2018 19:3_

Can I just remove it then?

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:26
Hi, @tafsiri 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:46
Hi, @tafsiri 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:46 UTC
Labels: type:docs, comp:website, stat:awaiting response
