### ISSUE TITLE
Document tf.io.loadWeights() and allow it to take a model.json URL

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1438] opened 2019-03-22 16:25 UTC
tf.io.loadWeights() does not exist in the API docs, let's document it.

The first argument is the WeightsManifestConfig, we should allow taking a URL to the model.json to avoid having to fetch it yourself.

**Comment by gaikwadrahul8** [comment] 2023-08-31 10:42
Hi, @nsthorat 

Apologize for the delayed response and I see https://github.com/tensorflow/tfjs-core/blob/master/tfjs-core/src/io/weights_loader.ts but we haven't documented it if I'm not wrong. Thank you!

**Comment by gaikwadrahul8** [comment] 2023-10-11 12:48
Hi, @nsthorat 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:29
Hi, @nsthorat

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:29 UTC
Labels: comp:core, type:docs, stat:awaiting response
