### ISSUE TITLE
"can't locate attribute: 'keras_version'" error encountered when using tfjs_convterter

### ISSUE THREAD

**Issue by David-Xiang** [tensorflow/tfjs#785] opened 2018-10-12 07:48 UTC
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Environment
Mac 10.13.6
Python 3.6
Keras 2.2.4
tensorflow 1.11.0
tensorflowjs 0.6.2

#### Describe the problem or feature request
I was trying to converter the keras pertained model [DenseNet201](https://keras.io/applications/#densenet)
`tensorflowjs_converter --input_format=keras DenseNet201.h5 densenet201`
and the error occured:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 247, in main
    split_weights_by_layer=FLAGS.split_weights_by_layer)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 75, in dispatch_keras_h5_to_tensorflowjs_conversion
    h5_file, split_by_layer=split_weights_by_layer)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 161, in h5_merged_saved_model_to_tfjs_format
    self._check_version(h5file)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 109, in _check_version
    keras_version = as_text(h5file.attrs['keras_version'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'keras_version')"
```

**Comment by David-Xiang** [comment] 2018-10-12 07:58
same problem occurred when converting model [ResNet50 and NASNet Mobile](https://keras.io/applications/)

**Comment by bileschi** [comment] 2018-10-12 14:30
This is probably related to recent changes in allowable serializations introduced in tensorflow 1.11.  See also #744 

Can you share the converted json?

**Comment by David-Xiang** [comment] 2018-10-12 15:50
Because converting failed, no json file is generalized.
And the convert command is like:
```python
import tensorflow.keras as keras
from keras.applications.densenet import DenseNet201
import os

model = DenseNet201(weights="imagenet")
model.save("DenseNet169.h5")
os.system("tensorflowjs_converter --input_format=keras DenseNet201.h5 densenet201")

```

**Comment by caisq** [comment] 2018-10-15 14:00
@David-Xiang Can you share the content of the model json with us so we can try reproducing it on our end?

**Comment by longing81** [comment] 2018-11-05 12:29
Have you solved the problem? How to do that? I am now face to the same serious problem...thx!

**Comment by longing81** [comment] 2018-11-05 13:20
I just solved this problem! In fact, I don't know where the problem is. I googled for a long time. I saw someone saying that it might be a tensorflow version 1.11. I also changed 1.11 to 1.10. But this is not very useful. Finally, I am desperate. Go back and modify the path of my model, try it again, and delete the blank in front of the "convert_models" of "tensorflowjs_converter --input_format keras \  
  convert_models/NASNet-mobile.h5 \ tfjsModels_NASNet ". I didn't expect it to succeed. So maybe the problem lies in the file path, and there can be no spaces before the file in the statement? Who knows? If you have the same problem, try it like me. If anyone has a better answer, I hope to tell me, thank you!

**Comment by ParvaShah** [comment] 2018-11-07 21:50
Try this format:
 !tensorflowjs_converter --input_format=keras my_model.h5 my_tfjs_model
here my_model.h5 is model and my_tfjs_model is folder. 
Don't use complex file directory.
Hope it helps.

**Comment by rthadur** [comment] 2018-11-30 21:58
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2018-11-30 21:58 UTC
Labels: comp:converter

**Comment by tempdeltavalue** [comment] 2025-01-12 14:01
Still exists 

2025-01-12 13:59:48.315874: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1736690388.349280    5747 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1736690388.359483    5747 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-12 13:59:48.391591: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
🌲 Try https://ydf.readthedocs.io/, the successor of TensorFlow Decision Forests with more features and faster training!
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 959, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 963, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 949, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 619, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 90, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    model_json, groups = conversion.h5_merged_saved_model_to_tfjs_format(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 226, in h5_merged_saved_model_to_tfjs_format
    _check_version(h5file)
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 127, in _check_version
    keras_version = as_text(h5file.attrs['keras_version'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Unable to synchronously open attribute (can't locate attribute: 'keras_version')"
