### ISSUE TITLE
Support non-batched inputs for layers model.predict().

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#317] opened 2018-05-20 17:17 UTC
Right now we expect a batched input when making a prediction.

We should allow predicting without a batch dimension (single example).

**Comment by caisq** [comment] 2018-06-18 13:46
@zaidalyafeai Thanks for the suggestion. I think that won't be as easy-to-use as letting the method determine whether the input is a batch or an individual example automatically. The method should be able to do that based on the shape. One thing I want to explore is whether we can get Keras to make the same change on the Python side as well. @fchollet

**Comment by nsthorat** [comment] 2018-06-18 13:53
+1 to doing this automatically. No need for an explicit bit when it's pretty easy to infer.

**Comment by caisq** [comment] 2019-02-12 15:27
Maybe instead of supporting non-batched,  single-example input in `predict`, which will involve some ambiguity for models with multiple inputs, we should add a method called `predictOnExample()`

**Comment by nsthorat** [comment] 2019-02-12 15:33
Can you remind me what the problem with multi-input models is? I still think we should do this as part of `predict`.

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:26
Hi, @nsthorat 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:46
Hi, @nsthorat

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:46 UTC
Labels: type:feature, comp:layers, P2, stat:awaiting response
