### ISSUE TITLE
Use AliasedBuffer Node.js concept to avoid C++/JS boundary issues

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#609] opened 2018-08-14 21:10 UTC
Crossing the JS/C++ boundary can be expensive - especially for loop'd operations. This is especially an issue with OpDef attributes used in Op execution. We can try and use the AliasedBuffer technique to avoid crossing that boundary. 

Sample code referenced here: https://github.com/nodejs/node/blob/0d64f33c9658b82897efb9355c0fc2caec034299/src/aliased_buffer.h

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:24
Hi, @nkreeger 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:45
Hi, @nkreeger 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:45 UTC
Labels: type:performance, comp:node.js, P3, stat:awaiting response
