### ISSUE TITLE
The "Try Tensorflow.js!" demo does not work in MacOS Safari Technology Preview Release 163

### ISSUE THREAD

**Issue by stevexbritton** [tensorflow/tfjs#7364] opened 2023-02-10 17:32 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 13.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): Not sure how codepen loads Tensorflow, but it breaks for me when using npm.
- TensorFlow.js version (use command below): 4.2.0 (and earlier versions)
- Browser version: MacOS Safari Technology Preview Release 163 (and 162)
- Tensorflow.js Converter Version:

**Describe the current behavior**
The "Try Tensorflow.js!" Codepen demo referenced on the tensorflow.js API page (https://js.tensorflow.org/api/latest/) does not work on MacOS Safari Technology Preview Release 163. No result is printed.
If a data() call is made to the returned tensor, instead of the print(), it never resolves.

I think this is a serious problem and will break many people's code when Apple role out this version of Safari.

**Describe the expected behavior**
Result printed to the console window as occurs when using previous versions of Safari or other browsers.

**Standalone code to reproduce the issue**
The "Try Tensorflow.js!" link on tensorflow.js API page (https://js.tensorflow.org/api/latest/) takes you to a codepen demonstrating the problem.

**Other info / logs** Include any logs or source code that would be helpful to
```html
// Define a model for linear regression.
const model = tf.sequential();
model.add(tf.layers.dense({units: 1, inputShape: [1]}));

// Prepare the model for training: Specify the loss and the optimizer.
model.compile({loss: 'meanSquaredError', optimizer: 'sgd'});

// Generate some synthetic data for training.
const xs = tf.tensor2d([1, 2, 3, 4], [4, 1]);
const ys = tf.tensor2d([1, 3, 5, 7], [4, 1]);

// Train the model using the data.
model.fit(xs, ys).then(() => {
  // Use the model to do inference on a data point the model hasn't seen before:
  // Open the browser devtools to see the output
  model.predict(tf.tensor2d([5], [1, 1])).print();
});
```

**Comment by pyu10055** [comment] 2023-02-13 21:10
@stevexbritton I tried the demo on the safari tech preview version, I could not find what is the cause for the no result, I suspect that it is related to safari Content Security Policy, no sure if there are any changes to the preview version, do you know if what is the schedule for releasing this preview?

**Comment by stevexbritton** [comment] 2023-02-14 17:09
Sorry, I don't know the Safari release schedule. I was hoping you guys might have more direct contact with Apple. What I can tell you is the current version is 16.3 and the Technology Preview is called 16.4!

**Comment by stevexbritton** [comment] 2023-02-27 10:17
This still does not work in Technology preview 164.
I'm not sure you realise how big of an issue this is.  When Apple release this, which bug report #7399 says is March, Tensorflow users will NOT be able to get their results if they are using the Webgl backend.

**Comment by pyu10055** [comment] 2023-02-28 23:47
just tested it again, it does seem that the fit() function is failing on the webgl backend, but still works on cpu.
The graph model execution still works, seems to be not webgl itself but the fit() function specific.

**Comment by pyu10055** [comment] 2023-03-02 00:13
@stevexbritton We have found the cause of the issue, Safari added support of Offscreen canvas but the fencing API does not work on that. We are trying to contact Safari to fix this, meaning we will add work around to avoid using Offscreen canvas on Safari.

**Comment by pyu10055** [comment] 2023-03-03 19:49
Apple just inform us that this bug is fixed with [WebKit bug 250532](https://bugs.webkit.org/show_bug.cgi?id=250532), and it will be available in the next STP.

**Closed** 2023-03-03 19:55 UTC
Labels: type:bug
