### ISSUE TITLE
Operations with variable tensor sizes cause GPU Memory leaks

### ISSUE THREAD

**Issue by justadudewhohacks** [tensorflow/tfjs#604] opened 2018-08-13 16:02 UTC
#### TensorFlow.js version

- tfjs-core 0.11.9
- tfjs-core 0.12.10

#### Browser version

- chrome 67.0.3396.99 (64-Bit)
- firefox 61.0.1 (64-Bit)

#### Describe the problem or feature request

Running operations with variable input tensor sizes causes GPU memory leaks (not tracked by tf.memory stats, but can be tracked using chrome task manager for example):

``` javascript
for (let i = 0; i < iterations; i++) {
  const height = Math.floor(Math.random() * maxTensorSize)
  const width = Math.floor(Math.random() * maxTensorSize)

  console.log(height, width)

  const t1 = tf.ones([height, width])
  const t2 = tf.ones([height, width])

  // do something
  const sum = t1.add(t2)

  t1.dispose()
  t2.dispose()
  sum.dispose()

  await tf.nextFrame()

  console.log(tf.memory())
}
```

#### Code to reproduce the bug / link to feature request
https://github.com/justadudewhohacks/tfjs-tensor-size-memoryleak-issue

**Comment by Lewuathe** [comment] 2018-08-17 08:01
@justadudewhohacks Thank you so much for the detail report and sample application.

But in my environment, the memory leak was not observed in Chrome task manager.
![screen shot 2018-08-17 at 16 57 33](https://user-images.githubusercontent.com/1713047/44254805-e648c180-a23e-11e8-95f9-002db99e1a06.png)

Even I ran the application several times, memory footprint was kept around 100MB. I launched the sample application according to README and checked the Chrome task manager.

**Comment by justadudewhohacks** [comment] 2018-08-18 14:07
Hi @Lewuathe,

Thanks for reviewing this. I should have mentioned that you have to toggle the GPU memory tab in the task manager:

![gpu-mem-leak](https://user-images.githubusercontent.com/31125521/44300014-46536c80-a300-11e8-86e8-3ad2c75ba0a0.jpg)

I could reproduce this on my desktop machine and laptop (both AMD GPUs + latest version of chrome), on an Intel GPU, as well as on my android device.

After some time the browser throws an exception saying **WebGL context lost**. Mobile chrome on android crashes almost immediately.

Hope this helps.

**Comment by justadudewhohacks** [comment] 2018-08-27 07:10
In case someone is facing the same issue, when training an image classifier or an object detector, you can mitigate that issue by resizing your images to a fixed input size, before calling `tf.fromPixels` and instead of doing tensor operations for padding and resizing:

``` typescript
export function imageToSquare(img: HTMLImageElement | HTMLCanvasElement, inputSize: number): HTMLCanvasElement {

  const dims = img instanceof HTMLImageElement 
    ? { width: input.naturalWidth, height: input.naturalHeight }
    : img 
  const scale = inputSize / Math.max(dims.height, dims.width)
  const width = scale * dims.width
  const height = scale * dims.height

  const targetCanvas = document.createElement('canvas')
  targetCanvas .width = inputSize
  targetCanvas .height = inputSize
  targetCanvas.getContext('2d').drawImage(img, 0, 0, width, height)

  return targetCanvas
}
```

**Comment by nsthorat** [comment] 2018-10-29 21:43
Ah yes, this is because we cache textures based on their physical shape, you are basically purposefully getting cache misses every single time. We've found that that's usually pretty rare. Resizing to a fixed input size will absolutely fix the problem :)

Just curious, why was your canvas changing size all the time in practice?

**Comment by justadudewhohacks** [comment] 2018-10-29 22:10
Thanks for clarification, I guess that explains it. You are probably right, in most cases the input size of tensors should be fixed anyways. 

I was facing the issue when training models on images, which where different in size. I was resizing each image with tf.resizeBilinear, which was causing these memory leaks. 

Also this was an issue in face-api.js, since you would first run your images through an object detector, which returns multiple bounding boxes of different sizes and extract sub images from these regions for further classification (for instance face landmark detection or computing a face descriptor). This was also a performance issue resulting in flaky inference times, since I guess the graph was recompiled everytime for different input shapes? 

However, by now I am using the code snippet I posted above for resizing, which works pretty well. So this is not really an issue from my side anymore.

**Comment by nsthorat** [comment] 2018-10-30 14:31
Ah yeah, if the output tensors are variably sized, we'll possibly have to recompile the shaders every time.

If you can provide a simple standalone HTML page that shows the issue we can look into making it faster (it's possible we can do things like upload the shape as a uniform to avoid recompilation).

cc @annxingyuan

**Comment by rthadur** [comment] 2018-12-05 21:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2018-12-05 21:44 UTC
Labels: comp:core, stat:awaiting response, type:performance

**Comment by RohanGautam** [comment] 2019-05-05 14:05
This is happening to me too!
For me, i've pinpointed it down to the following line in my code:
`img = tf.browser.fromPixels(webcamElement);`
where `webcamElement` is a frame from the webcam, all the major webcam setup is from google's example [here](https://codelabs.developers.google.com/codelabs/tensorflowjs-teachablemachine-codelab/index.html#0).

I'm resizing `img` and passing it though a CNN. Even when I _dont_ resize it with tf.js, and change the shape of the webcam frame itself, the issue persists.

Memory leak is clearly the issue as `tf.memory()` tells me the memory increases _very_ rapidly

I have tried:
* clearing texture cache manually, from #1440 
* `tf.disposeVariables()` after each frame is done processing from [here](https://groups.google.com/a/tensorflow.org/forum/#!topic/tfjs/v4OoeFKf_2Q).

Let me know if there is any other info you'd like me to provide! I'm kinda stumped about this issue at the moment.

**Comment by RohanGautam** [comment] 2019-05-06 07:49
UPDATE: I'm currently able to get it working by calling `tf.dispose()` on every tensor after i'm done using it. Seems to work for now, but it's kinda janky. Hope it helps someone though!

**Comment by nsthorat** [comment] 2019-05-07 18:39
@RohanGautam, do you think you could post the code you are having problems with?

**Comment by RohanGautam** [comment] 2019-05-08 04:03
sure! I've boiled it down to the following minimum code required to reproduce the error:
`index.html` : 
```html
<html>

<head>
    <meta charset="UTF-8">
    <title>MemLeak</title>
    <!-- Load the latest version of TensorFlow.js -->
    <script src="https://unpkg.com/@tensorflow/tfjs"></script>
</head>

<body>
    <video autoplay playsinline muted id="webcam" width="250" height="250"></video>
    <!-- Load index.js after the content of the page -->
    <script src="index.js"></script>
</body>

</html>
```


`index.js` :
```javascript
const webcamElement = document.getElementById('webcam');

async function app() {

    await setupWebcam();
    while (true) {
        //!! source of leak !!
        const img = tf.browser.fromPixels(webcamElement);
        // Doing stuff with the image//
        console.log(tf.memory())
        await tf.nextFrame();
    }
}


async function setupWebcam() {
    return new Promise((resolve, reject) => {
        const navigatorAny = navigator;
        navigator.getUserMedia = navigator.getUserMedia ||
            navigatorAny.webkitGetUserMedia || navigatorAny.mozGetUserMedia ||
            navigatorAny.msGetUserMedia;
        if (navigator.getUserMedia) {
            navigator.getUserMedia({ video: true },
                stream => {
                    webcamElement.srcObject = stream;
                    webcamElement.addEventListener('loadeddata', () => resolve(), false);
                },
                error => reject());
        } else {
            reject();
        }
    });
}

app();
```

**Comment by nsthorat** [comment] 2019-05-08 15:39
Ah so regular tf.Tensors not tf.Variables. Check out the guide here for why that is not a bug: https://www.tensorflow.org/js/guide/tensors_operations#memory

**Comment by dhasegan** [comment] 2020-05-12 17:42
@RohanGautam did you get to fix your problem? I am having the same issue and tf.dispose and tf.tidy does not work.
My specs:
- "@tensorflow/tfjs": "1.7.4"
Browser:
- Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by RohanGautam** [comment] 2020-05-13 11:08
@dhasegan 
> @RohanGautam did you get to fix your problem? I am having the same issue and tf.dispose and tf.tidy does not work.
> My specs:
> 
>     * "@tensorflow/tfjs": "1.7.4"
> 
> 
> Browser:
> 
>     * Chrome Version 81.0.4044.138 (Official Build) (64-bit)

Yeah I did! Was working on it a long while back, so had to dig up the archives. It was fixed in [this commit](https://github.com/RohanGautam/LangSign/commit/7464c0ad9e4e284253c905b39880111c1c8d566a) in my personal project. 

Basically involved disposing everything, **including intermediate products** of computation.
```javascript
const img = tf.browser.fromPixels(webcamElement);
const resizedImg = tf.image.resizeBilinear(img, [150, 150])
const batchedImage = resizedImg.expandDims(0);
//--------disposing intermediate products too-------------//
tf.dispose(img);
tf.dispose(resizedImg);
tf.dispose(batchedImage);
console.log(tf.memory());
```
But you say `dispose` didn't work for you :/ I'd suggest `console.log(tf.memory())`-ing in your intermediate steps and narrowing down where it's happening.

**Comment by dhasegan** [comment] 2020-05-13 19:25
`tf.memory()` is not increasing for me. my input has varying sizes as well and each new size there is a new shader that is created and cached in the TFJS library: https://github.com/tensorflow/tfjs/issues/3061

There is no cache purge so it slowly accumulates GPU memory (as seen in the Chrome Task Manager). You might reach a similar issue if you have different sizes for `webcamElement`
