### ISSUE TITLE
Failed installation of tfjs-tflite-node on MacOS

### ISSUE THREAD

**Issue by kevin-keraudren** [tensorflow/tfjs#7142] opened 2022-12-06 20:35 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
MacOS Monterey (version 12.6)

```
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! CXX(target) Release/obj.target/node_tflite_binding/binding/node_tflite_binding.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@19.1.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "/usr/local/opt/python@3.10/bin/python3.10"
```

**Describe the problem**
tfjs-tflite-node fails to install on MacOS through `npm install` due to "exceptions being disabled".

For details on `tfjs-tflite-node`, see https://github.com/mattsoulanille/tfjs/tree/tfjs-tflite-node/tfjs-tflite-node

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Adding `"tfjs-tflite-node": "^0.0.2",` to `package.json` and running `npm install`.

**Any other info / logs**
```
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../binding/node_tflite_binding.cc:19:
npm ERR! In file included from node_modules/node-addon-api/napi.h:2981:
npm ERR! node_modules/node-addon-api/napi-inl.h:74:3: error: cannot use 'try' with exceptions disabled
npm ERR!   try {
npm ERR!   ^
npm ERR! node_modules/node-addon-api/napi-inl.h:93:3: error: cannot use 'try' with exceptions disabled
npm ERR!   try {
npm ERR!   ^
npm ERR! node_modules/node-addon-api/napi-inl.h:461:3: error: cannot use 'throw' with exceptions disabled
npm ERR!   NAPI_THROW_IF_FAILED(*this, status, Object());
npm ERR!   ^
```

**Comment by gaikwadrahul8** [comment] 2023-04-21 11:28
Hi, @kevin-keraudren 

Apologize for the delayed response and I was able to replicate the issue, I'm able to install `@tensorflow/tfjs-tflite` on my `MacOS` `M1` for your reference I have package.json dependancies below and also I have added screenshot below for your reference so I would request you to please give it try from your end, Let us know whether is it resolving your issue or not ? 

If issue still persists please let us know with error log to do further investigation to find out the root cause for your issue ? Thank you!

Here is package.json file information :

```
"dependencies": {
    "@tensorflow/tfjs-core": "^3.20.0",
    "@tensorflow/tfjs-tflite": "^0.0.1-alpha.9",
    "tfjs-tflite-node": "^0.0.2"
  }

```

Here is screenshot where `@tensorflow/tfjs-tflite` is importing successfully:

![image](https://user-images.githubusercontent.com/115997457/233624983-7c66ea06-a517-41ee-9146-b4d7bf12b6b3.png)

**Closed** 2023-05-05 12:58 UTC
Labels: type:build/install, stat:awaiting response, stalled, comp:tfjs-tflite
