### ISSUE TITLE
tfjs-node v0.0.0

### ISSUE THREAD

**Issue by aravindvnair99** [tensorflow/tfjs#4998] opened 2021-04-27 23:23 UTC
https://github.com/tensorflow/tfjs/blob/d72d7597e6f91cb1c2a2a15e01df12f217bba041/tfjs-node/package.json#L3

Why is the version `0.0.0`?

https://www.npmjs.com/package/@tensorflow/tfjs-node says `3.5.0`

**Comment by rthadur** [comment] 2021-04-28 17:45
please check the PR https://github.com/tensorflow/tfjs/pull/2958 , which has the context ,thank you .
Closing this as this is not a bug/feature request.

**Closed by rthadur** 2021-04-28 17:45 UTC
Labels: comp:node.js, type:bug
