### ISSUE TITLE
Issues with tensorflowjs_converter - permission denied on directory

### ISSUE THREAD

**Issue by dasimandl** [tensorflow/tfjs#238] opened 2018-04-26 16:03 UTC
#### TensorFlow.js version
Tensorflow 1.5 - I downgraded because I was getting illegal hardware issues. This was a recommended solution on the message boards.

#### Browser version
This issue is not running in browser - newest chrome release

I am running into an error while trying to convert a saved mobilenet model using tfjs-converter.
I copied the command line - I/O below. I tried this using the full path and the relative path (shown below). I also tried this as sudo and as current user. Im sure this is some very simple error on my part, but after some time google searching I was unable to find a solution. Thank you.

sudo tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='MobilenetV1/Predictions/Reshape_1' \
    --saved_model_tags=serve
    ./input-model \
    ./output-model
/usr/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
usage: TensorFlow.js model converters. [-h] --input_format
                                       {tf_saved_model,keras}
                                       [--output_node_names OUTPUT_NODE_NAMES]
                                       [--saved_model_tags SAVED_MODEL_TAGS]
                                       input_path output_dir
TensorFlow.js model converters.: error: too few arguments
zsh: permission denied: ./input-model

**Comment by caisq** [comment] 2018-04-27 13:59
cc @pyu10055

**Comment by pyu10055** [comment] 2018-05-03 19:02
@dasimandl I suspect that your converter command is split into multiple lines. try following:

tensorflowjs_converter \
--input_format=tf_saved_model \
--output_node_names='MobilenetV1/Predictions/Reshape_1' \
--saved_model_tags=serve \
./input-model \
./output-model

**Comment by dsmilkov** [comment] 2018-10-24 19:55
Closing since this issue is likely outdated. Feel free to re-open if the problem is there using the latest converter.

**Closed by dsmilkov** 2018-10-24 19:55 UTC
Labels: converter
