### ISSUE TITLE
Infer dtype from first n records, when it's not specified

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1017] opened 2018-10-04 18:34 UTC
Python tf.data already does this: https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/python/data/experimental/ops/readers.py?rcl=215304249&l=129

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:38
Hi, @davidsoergel 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:38 UTC
Labels: type:feature, stat:awaiting response, comp:data
