### ISSUE TITLE
"response.arrayBuffer is not a function" while loadLayersModel (Node.js)

### ISSUE THREAD

**Issue by kqtus** [tensorflow/tfjs#2029] opened 2019-09-12 07:51 UTC
## TensorFlow.js version
1.2.9
#### Browser version
any

#### Describe the problem or feature request
I have exported a Keras model written in Python, then converted it with tensorflowjs_converter and uploaded it to server. Then, I get error while loading it. I have tried it with @tensorflow/tfjs-node' as well as @tensorflow/tfjs'.

`
TypeError: response.arrayBuffer is not a function
    at f:\Developer\x\node_modules\@tensorflow\tfjs-core\dist\io\weights_loader.js:97:90
    at Array.map (<anonymous>)
    at Object.<anonymous> (f:\Developer\x\node_modules\@tensorflow\tfjs-core\dist\io\weights_loader.js:97:48)
    at step (f:\Developer\x\node_modules\@tensorflow\tfjs-core\dist\io\weights_loader.js:48:23)
    at Object.next (f:\Developer\x\node_modules\@tensorflow\tfjs-core\dist\io\weights_loader.js:29:53)
    at fulfilled (f:\Developer\x\node_modules\@tensorflow\tfjs-core\dist\io\weights_loader.js:20:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

#### Code to reproduce the bug / link to feature request

File is publicly available, bin file also resides there.
`
const tf = require('@tensorflow/tfjs-node');
`
`
model = await tf.loadLayersModel('https://storage.googleapis.com/valid-ship-252510.appspot.com/1568271407928-tfjs_model_1/model.json');
`

**Comment by kqtus** [comment] 2019-09-17 10:24
Any estimations on when it will be fixed?

**Comment by rthadur** [comment] 2019-09-17 17:21
@kangyizhang any thoughts on above comments from @kqtus ?

**Comment by kqtus** [comment] 2019-09-17 17:37
Ok I think I solved it the proper way, having replaced global fetch.

`const nodeFetch = require('node-fetch');`
`global.fetch = nodeFetch;`

It is strange though, because previously I tried passing it as a fetchFunc, but it didn't trigger.

**Comment by rthadur** [comment] 2019-09-17 17:47
thanks for the update , closing this issue.

**Closed by rthadur** 2019-09-17 17:47 UTC
Labels: comp:converter, type:bug

**Comment by kangyizhang** [comment] 2019-09-17 17:50
tf.loadLayersModel() should automatically use node-fetch when it's in Node environment. @dsmilkov any thoughts why `.arrayBuffer()` is not available?

**Comment by dsmilkov** [comment] 2019-09-18 20:09
@kqtus We'd like to understand why you had to manually do `node-fetch`. In Node.js, we do override the global fetch internally so the user doesn't have to. I'm unable to reproduce the bug.

Can you provide a bit more info:
- What version of node you are using?
- We don't seem to have access to the model.json on GCS (Access denied). If you can share the model files publicly, that would be great.
- Can you share the error you are getting by simply calling tf.loadLayersModel(url), without specifying any `fetchFunc` in `options`?

Thank you!

**Comment by dsmilkov** [comment] 2019-09-18 20:19
Another idea. Can you double-check the node-fetch version you had installed before? You may have had previously manually installed node-fetch 1.x which lacks `body.arraybuffer()`, while tfjs depends on node-fetch 2.x.

**Comment by kqtus** [comment] 2019-09-21 10:15
@dsmilkov 

- npm version: 6.9.0
- I deleted the previous model. I have another one, though:
https://storage.googleapis.com/valid-ship-252510.appspot.com/1568368482017-keras_dogs_cats_model/model.json
- Here's the error log https://pastebin.com/z64J4KEj
- I didn't have node-fetch installed prior to fixing the problem by manual assignment. Having it installed, without overriding global fetch function still doesn't solve the case.

**Comment by kangyizhang** [comment] 2019-09-21 23:09
@kqtus can you provide your node version and which operating system you are using?

**Comment by kqtus** [comment] 2019-09-22 13:39
@kangyizhang Node v10.16.3, Windows 10 1903. Here's also package.json: https://pastebin.com/swpTke2q.

One additional thing - we are having frontend app and backend in the same project (Express + React). Frontend is being transpiled and backend is run as-is - maybe that causes ambiguity.
