### ISSUE TITLE
Bodypix@2.0 not available on cdn

### ISSUE THREAD

**Issue by JaeDukSeo** [tensorflow/tfjs#2240] opened 2019-10-21 05:54 UTC
the javascript file is not found

**Comment by rthadur** [comment] 2019-10-21 20:35
this is a duplicate of #2227 , closing this , will wait for Tyler reply.

**Comment by nsthorat** [comment] 2019-10-21 21:53
Apologies, we are preparing to release a new version and updated the README but haven't released yet. This PR reverts the README to v1 so you can see the old API (stay tuned for a new version!)

https://github.com/tensorflow/tfjs-models/pull/327

**Comment by kesar** [comment] 2019-10-29 17:00
waiting for v2 on cdn too 👍

**Comment by dsmilkov** [comment] 2019-11-15 20:57
Closing since we released 2.0 on NPM, as well as uploaded a new demo.

**Closed by dsmilkov** 2019-11-15 20:57 UTC
Labels: bodyPix
