### ISSUE TITLE
tfvis.show.fitCallbacks(): fail faster and give better error messages

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1102] opened 2019-01-17 15:12 UTC
#### TensorFlow.js version
tfjs-vis 0.4.2

The signature of `tfvis.show.fitCallbacks()` is somewhat complicated. instead of failing when `Model.fit()` runs, which is the current behavior and a long feedback loop, it should do the following validation in order to fail fast when the caller provides wrong arguments, 
- That there are at least two arguments
- The second arg is a non-empty list of strings
- The fields in the third argument are valid.

**Comment by gaikwadrahul8** [comment] 2023-10-11 13:47
Hi, @caisq 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:35
Hi, @caisq 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:35 UTC
Labels: type:ux, comp:vis, P3, stat:awaiting response
