### ISSUE TITLE
no data found for this tensor

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#141] opened 2018-04-07 15:01 UTC
_From @riatzukiza on March 18, 2018 18:52_

# Error
I was struggling with a memory leak, then I fix the leak, and I start getting this error.
```
bundle.js:14641 Uncaught (in promise) Error: WebGL backend: No data found for this tensor. Did you change your backend in the middle of the program? New backends can't use Tensors created with previous backends
    at MathBackendWebGL.throwIfNoData (bundle.js:14641)
    at MathBackendWebGL.readSync (bundle.js:14048)
    at MathBackendWebGL.<anonymous> (bundle.js:14093)
    at step (bundle.js:13922)
    at Object.next (bundle.js:13903)
    at fulfilled (bundle.js:13894)
    at <anonymous>
```
# Code
I am rendering data to a canvas, so I have to call data every frame.
## deeplearn logic
Logic to the implementation of conways game of life.
```js
    var kernel = dl.reshape(dl.tensor2d([
        [1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]
    ]), [3, 3, 1, 1]);
    var state0Tensor = dl.randomUniform([H, W]).greater(dl.scalar(0.5, "float32"));
    var state = dl.variable(dl.cast(dl.reshape(state0Tensor, [1, H, W, 1]), "float32"));
    var step = (function step$() {

        var newState = dl.tidy((() => {

            var neighbors = dl.conv2d(state, kernel, [1, 1, 1, 1], "same");
            var survive = dl.logicalAnd(dl.equal(state, dl.scalar(1, "float32")), dl.equal(neighbors, dl.scalar(2, "float32"))),
                born = dl.equal(neighbors, dl.scalar(3, "float32"));
            return dl.cast(dl.logicalOr(survive, born), "float32");

        }));
        state.assign(newState);
        newState.dispose();
        return state;
    });
```

## rendering

Then I itterate over every element of `tensor.data()`, the error points at 

```
return state.data().then(((d) => {
                            ^
```
```js
    render(canvas = this.canvas, state = this.state, shape = this.shape, imageData = this.imageData, ctx = this.ctx) {

        if (!(running__QUERY)) {
            return false;
        };
        var height = shape[0],
            width = shape[1];
        return state.data().then(((d) => {

            var j = 0,
                k = 0;
            for (var i = 0; i < (width * height); ++(i)) {
                j = (i * 4);;
                this._renderCell(d[i], j, imageData)
            };
            return ctx.putImageData(imageData, 0, 0);

        }));

    }
```

_Copied from original issue: tensorflow/tfjs-core#865_

**Comment by nsthorat** [comment] 2018-04-07 15:01
_From @riatzukiza on March 18, 2018 19:1_

The program still renders the sim, one would not know anything was happening if they did not open the debug tools

**Comment by nsthorat** [comment] 2018-04-07 15:01
Hi @riatzukiza, moving this issue, but is your "render" call coming from inside a tidy()? What's likely happening is the tensor is disposed by the time the data() promise resolves.

**Comment by grimmer0125** [comment] 2018-04-27 10:09
Hi,  I am new to TensorFlow and neural network and I get a similar error when I try to train my 2 output network, `await this.nnet.model.fit(xTrain, [yTrain1, yTrain2]`, I do know if this is due to may fault setting or a library's bug. 

 Error: 
```
Uncaught Error: WebGL backend: No data found for this tensor. Did you change your backend in the middle of the program? New backends can't use Tensors created with previous backends
    at MathBackendWebGL../node_modules/@tensorflow/tfjs-core/dist/kernels/backend_webgl.js.MathBackendWebGL.throwIfNoData (backend_webgl.js:805)
    at MathBackendWebGL../node_modules/@tensorflow/tfjs-core/dist/kernels/backend_webgl.js.MathBackendWebGL.uploadToGPU (backend_webgl.js:811)
    at backend_webgl.js:756
    at Array.map (<anonymous>)
    at MathBackendWebGL../node_modules/@tensorflow/tfjs-core/dist/kernels/backend_webgl.js.MathBackendWebGL.compileAndRun (backend_webgl.js:755)
    at MathBackendWebGL../node_modules/@tensorflow/tfjs-core/dist/kernels/backend_webgl.js.MathBackendWebGL.conv2d (backend_webgl.js:681)
    at environment_1.ENV.engine.runKernel.x (conv.js:81)
    at Engine../node_modules/@tensorflow/tfjs-core/dist/engine.js.Engine.runKernel (engine.js:72)
    at ./node_modules/@tensorflow/tfjs-core/dist/ops/conv.js.ConvOps.conv2d (conv.js:81)
    at operation.js:11
    at Object../node_modules/@tensorflow/tfjs-core/dist/tracking.js.Tracking.tidy (tracking.js:36)
    at Object.descriptor.value [as conv2d] (operation.js:11)
    at Object.conv2dWithBias (tfjs_backend.js:812)
    at Conv2D../node_modules/@tensorflow/tfjs-layers/dist/layers/convolutional.js.Conv.call (convolutional.js:100)
    at topology.js:382
```

**Comment by nsthorat** [comment] 2018-04-27 13:51
Could you share your full code with us?

**Comment by grimmer0125** [comment] 2018-04-27 14:35
Sure. Here is the explanation, and I'm sorry that there are too many comments to affect reading.

set up my model:
https://github.com/grimmer0125/alphago-zero-tictactoe-js/blob/master/src/tictactoe/tensorflow/TicTacToeNNet.js

train or predict: 
https://github.com/grimmer0125/alphago-zero-tictactoe-js/blob/master/src/tictactoe/tensorflow/NNet.js

demo site (using pretrained to predict works but self-train error):
https://grimmer.io/alphago-zero-tictactoe-js/
The pretrained keras model's input is a little different than the one I set up. Its input's shape is  [3x3], then reshape, then cnn. Mine is [3, 3, 1], then cnn. 

I port it from another project and its training flow is 
1. run some simulation and get some output from `model.prediction`. Predictoin works here, too. 
2. after getting enough data, start to train, then get the above error.

**Comment by nsthorat** [comment] 2018-04-27 14:50
When I press the button "Start self-Train" I get no errors - is that the right button that throws the error?

**Comment by grimmer0125** [comment] 2018-04-27 15:06
Yes, it is the right button. 

I just updated the site, and the original step1-simulation will run 25x3 episodes and may take 1, 2min.  Now it runs 4x3 episodes and may take 15 seconds. After that, it will start to train. Please try again.

**Comment by grimmer0125** [comment] 2018-04-28 09:37
I notice that 
`backend_webgl.js.MathBackendWebGL.throwIfNoData` indicates that some `dataID` is missing, and I search `dataID` in the library code and also apply some breakpoints,  

When my model is setup, for example, in https://github.com/grimmer0125/alphago-zero-tictactoe-js/blob/master/src/tictactoe/tensorflow/TicTacToeNNet.js#L40
```
    const input = tf.input({ shape: [this.board_x, this.board_y, 1] });
    const h_conv1 = normalize1().apply(normalize1().apply(conv2d_padding().apply(input)));
```
Some actions will try to allocate tensor related objects, but
```
// tensor.js:
TensorBuffer.prototype.toTensor = function () {
    return Tensor.make(this.shape, { values: this.values }, this.dtype); // no pass dataID
};  
```
->
```
// tensor.js:
    Tensor.make = function (shape, data, dtype) {
        return new Tensor_1(shape, dtype, data.values, data.dataId); // no dataID
    };
``` 
->
```
// backend_webgl.js:
    MathBackendWebGL.prototype.register = function (dataId, shape, dtype) {
        if (this.texData.has(dataId)) {
            throw new Error('Data buffer is already registered');
        }
        this.texData.set(dataId, { // no dataID
            shape: shape,
            dtype: dtype,
            values: null,
            texture: null,
            texShape: null,
            texType: tex_util_1.TextureType.FLOAT
        });
    };   
```

This may be a wrong guess.

**Comment by nsthorat** [comment] 2018-04-29 17:09
Apologies for the bad stack trace, I cloned your repo and am having trouble finding the TensorFlow.js entry point where this is throwing as well.

Can you reproduce this issue without the overhead of the rest of the app (since it's a little large it will take me a bit to wrap my head around). Could you reproduce with the same model topology and some dummy data? If you can do that I can look deeper, react is making the stack traces a little difficult.

**Comment by grimmer0125** [comment] 2018-04-30 05:11
Yes, these two are good suggestions. 

When I am trying to simplify and use the dummy data, I notice a key point. 
**Training works if I do not use model.predict several times first !!!**
**Training throw exception if I use model.predict several times first and use dummy data to train**
**Training works if I just call model.predict once first**
`works` means calling model.fit succesffully and I just test to call it once. 

The algorithm I use requires I use model.predict first to get some initialy game data, and this step seems to affect the following training. 

So I can still try to simplfy the React part but the part of `simulation+model.predict first` may need to be kept to reproduct this issue.

**Comment by grimmer0125** [comment] 2018-04-30 06:49
I have created another branch excluding react and add a button to predict once + train once.
https://github.com/grimmer0125/alphago-zero-tictactoe-js/tree/simplifiedToTest

**Comment by grimmer0125** [comment] 2018-04-30 12:39
After comparing the differences between the related codes for these 2 buttons, I got the **key difference.**, thank you for your suggestions again.  

```
// Coach.js 
// this.pnet is the instance of NNetWrapper
this.pnet = deepcopy(this.nnet);  //<-key point
await this.nnet.train(flattenExamples); // start train 

// NNet.js
export class NNetWrapper extends NeuralNet {
  constructor(game) {
    // this.nnet is the instance of TicTacToeNNet, the same property name
    this.nnet = new TicTacToeNNet(game, args);
  }
}  

// TicTacToeNNet.js
export default class TicTacToeNNet {
  constructor(game, args) {
    this.model = tf.model({ inputs: input, outputs: [output1, output2] });
  } 
} 
```
If I remove the line of `this.pnet = deepcopy(this.nnet); `, traning will not throw execpetions !!!!! (at least for my one time training test). Which means, if a object's object's property is `tf.model`, `deepcopy` this object will affect some internal state of `TensorFlow.js/WebGL` and the result is possible exceptioin. 

Why I use `deepcopy` this object is to recoever the related tf.model to some saved state, if the following trained model is not good, it needs to go back to the previous status before training. Using `deeocopy` is my proposed workaround way, and the original Python version code uses `tf.train.Saver().save/restore` to achieve it.

**Comment by nsthorat** [comment] 2018-04-30 13:07
Ahhh yes! That makes a lot of sense. Basically what happens is you deep
copy the tensor, the data ID also gets copied, but TensorFlow.js doesn't
know about it.

So the first Tensor gets cleaned up, destroying that data bucket (keyed by
data ID). The next time you access the second data bucket we don't know
about it.

Just FYI, you can use ".clone()" to clone a Tensor. It will return a new
Tensor, however clone() is extremely cheap. Under the covers we create
another "shell" Tensor pointing to the same data ID.

Nice job finding that!

**Comment by dsmilkov** [comment] 2018-10-24 19:49
Since this issue, we've done global tracking of tensors, as well as transferring tensors between backends, so this error is likely outdated.

**Closed by dsmilkov** 2018-10-24 19:49 UTC
