### ISSUE TITLE
Webcam tfjs on safari

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tfjs#1174] opened 2019-01-30 02:51 UTC
None of the examples on the homepage seem to work on safari such as https://emojiscavengerhunt.withgoogle.com. 
Safari Version 12.0 (14606.1.36.1.9)
on MAC
The video cam just freezes

**Comment by rohanmuplara** [comment] 2019-09-03 23:12
Sorry for the very late reply. I didn't need to test my project without safari but it is still not working and now I need it. This is what happens when I use it on safari but it works fine on chrome.  https://drive.google.com/file/d/1YCni_rY2zmmL0hkOJAx09_cdeKR-0Ri9/view. Version 12.1.1 (14607.2.6.1.1) of safari.  mac 10.14.5  I don't particularly care about this game but I see the same issue in one of my projects so figured  if we can figure the problem out here, we can figure out the problem in my project.

**Comment by rohanmuplara** [comment] 2019-09-06 19:07
@tafsiri I am just drawing attention to this gain. I have attached a link above of a screen recording. I have notice in my own projects, where the webcam just freezes. I grant permission but after a few seconds, the rendering freezes. From my debugging sessions,  tf.frompixels is the one freezing on my browser.

**Comment by rthadur** [comment] 2019-09-06 21:07
@rohanmuplara what version of tfjs you are using ? there is no tf.frompixels it is now [tf.brwoser.fromPixels ](https://js.tensorflow.org/api/1.0.0/#browser.fromPixels)

**Comment by rohanmuplara** [comment] 2019-09-06 22:12
Yes I am using this tf.browser.fromPixels. Sorry I misspoke. I am using @tensorflow/tfjs": "^1.2.7".

**Comment by rohanmuplara** [comment] 2019-09-09 23:26
@rthadur Any updates here or workarounds. This is really blocking as I can't deploy as it doesn't work on safari.

**Comment by tafsiri** [comment] 2019-09-18 22:18
@rohanmuplara Just saw you posted an update. The emojiscavangerhunt is probably using an older version of tensorflow.js so this issue may be fixed. I've been trying to reproduce this on newer builds of tfjs but haven't been able to. Could you please go to the following links and let me know if these demos work for you.

1. https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html
2. https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html
3. https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html

Let us know what you get on each of those pages.

**Comment by rohanmuplara** [comment] 2019-09-18 23:25
The first two links work. For the third, I get webcam not found but I am sure the webcam not configured. Let me look at the code for these newer version and see if they do anything differently. I will pose here with a jsfiddle for my code that is broken.

**Comment by tafsiri** [comment] 2019-09-19 14:18
Thanks that would be great, we might need to update the demo for the third link, but if you could post a jsfiddle or something similar with a recent version of tfjs that would be helpful.

**Comment by bgirschig** [comment] 2019-10-02 16:42
Hi! I'm also having issues with the camera on safari:

- With an older version (@tensorflow-models/posenet: 1.0.3), the camera often gets "stuck" on the first frame. The detection works on that frame, but It looks like running the detection "spoils" the media stream.
- The current demo (https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html) is a bit slower on chrome (~5fps), and super slow on safari (0.5fps)
I've tried on 2 different laptops (both mac-book-air), and the same happens on both

Any idea why that might be happening ? (A solution for the first point would be best, but if the latest model can work ok on safari and chrome, i'll update it)

Thanks!

**Comment by vabarbosa** [comment] 2019-11-21 22:16
hello, i'm also experiencing this problem with Safari browsers. i created a basic demo where i can reproduce the problem: 

1. in a Safari browser go to: https://codepen.io/vabarbosa/pen/bGGZXbz 
1. click on **Start Webcam** and grant permission to access webcam
1. click **Load Model** to load a base model from posenet: https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/float/075/model-stride16.json
1. click **Run Prediction** (with **use requestAnimationFrame** unchecked/disabled) to call `model.predict` once on a frame. (video may pause initially for a brief sec but resumes and subsequent calls are quick and return values always changing)
1. check/enable **use requestAnimationFrame** then click **Run Prediction**. this will repeatedly call `model.predict` using `requestAnimationFrame()`. (at this point the predictions run but the video freezes so returned values never change. unchecking the **use requestAnimationFrame** stops the prediction calls and video resumes)

(4) is OK but (5) is not OK.

the only difference is (5). i see this problem on Safari but not Chrome or Firefox. i also do not notice any errors in the console. i do not have another machine at this moment to try this on but my current environment is:  

- **user-agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
- **tfjs-version**: 1.3.2

any insight is greatly appreciated and if you need me to try something or look into anything let me know.

thank you.

**Comment by rthadur** [comment] 2020-02-14 21:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2020-02-14 21:17 UTC
Labels: stat:awaiting response, type:bug

**Comment by alexionby** [comment] 2020-05-13 13:31
@vabarbosa , did you find any way to avoid this issue?

**Comment by vabarbosa** [comment] 2020-05-13 19:22
@alexionby i did not. i had moved to other projects and hadn't had time to revisit this. however, i did just try it now and i am not seeing the issue
**user-agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
i will play around some more and see if it reproduces again
