### ISSUE TITLE
Failed to execute clientWaitSync

### ISSUE THREAD

**Issue by kirill-konshin** [tensorflow/tfjs#4732] opened 2021-02-23 20:12 UTC
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04.1 64 bit (kernel 5.8.0-43), GeForce GTX 980 Ti**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow.js installed from (npm or script link): 2.8.5
- TensorFlow.js version (use command below):
- Browser version: **88.0.4324.182 (Official Build) (64-bit)**
- Tensorflow.js Converter Version: n/a

**Describe the current behavior**

Caught an error

![image](https://user-images.githubusercontent.com/1530410/108898900-a364c300-75cc-11eb-9f02-b34ec399189f.png)

Traced it to `node_modules/@tensorflow/tfjs-backend-webgl/src/gpgpu_context.ts`:

```ts
  private createFence(gl: WebGLRenderingContext): FenceContext {
    let query: WebGLQuery|WebGLSync;
    let isFencePassed: () => boolean;

    if (env().getBool('WEBGL_FENCE_API_ENABLED')) {
      const gl2 = gl as WebGL2RenderingContext;

      const sync = gl2.fenceSync(gl2.SYNC_GPU_COMMANDS_COMPLETE, 0);
      gl.flush();

      isFencePassed = () => {
        const status = gl2.clientWaitSync(sync, 0, 0); // <----- failed here
        return status === gl2.ALREADY_SIGNALED ||
            status === gl2.CONDITION_SATISFIED;
      };
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**

Unfortunately it's almost impossible to create a good reproducible case for this kind of error.

**Comment by rthadur** [comment] 2021-02-26 01:02
@kirill-konshin it is very hard for us to help with out reproduction code. Are you trying to load in web worker ?

**Comment by kirill-konshin** [comment] 2021-02-26 01:30
@rthadur yes, the code is in web worker.

**Comment by pyu10055** [comment] 2021-02-26 17:35
@kirill-konshin Here is an [simple example](https://codepen.io/pyu10055/pen/LYbQdMj) of running tfjs in webworker, it tries to download the tensor from webgl backend, it did not encounter the fencing error.
Can you try to create a reproducible example based on that? thanks.

**Comment by kirill-konshin** [comment] 2021-03-05 20:06
@pyu10055 I know it's hard to investigate w/o code, but I can't make the concise example because then I will have to drag the entire image processing system that we have... I've traced the error to TF code, it's something internal. The issue does not reproduce 100% of times, it's very sporadic.

**Comment by pyu10055** [comment] 2021-03-08 02:50
@kirill-konshin TF code you traced to looks fine, we need to figure out under what condition the fenceSync function is not longer valid.    A good way to isolate the problem is to look at the output of your image processing part before it feed into TF code.

**Comment by kirill-konshin** [comment] 2021-03-18 22:50
> @kirill-konshin TF code you traced to looks fine, we need to figure out under what condition the fenceSync function is not longer valid. A good way to isolate the problem is to look at the output of your image processing part before it feed into TF code.

Nothing changes on our side, we're just passing more and more frames from camera to TF but at some point in time the `fenceSync`, which is not accessible by us, is breaking in a way described earlier...

**Comment by bikubi** [comment] 2021-08-04 13:49
I ran into the same error, and since this is the only result and my setup seems similar ("more and more frames"), it could apply.

setup:

* Arch Linux 5.12.12-arch1-1
* tfjs 3.8.0 via npm
* **not** in webworker
* model: mobilenet_v2_100_224
* Chromium 91.0.4472.114 (Firefox 90.0 is OK!)

The error happens [in gpugpu_context](https://github.com/tensorflow/tfjs/blob/04633433fdb1806fbac58b0db31d0f0313ff3a05/tfjs-backend-webgl/src/gpgpu_context.ts#L243) when 

```
 const sync = gl2.fenceSync(gl2.SYNC_GPU_COMMANDS_COMPLETE, 0);
```

fails, and `sync` is null.  
I couldn't manage to `try catch` this error. I also tried calling `fenceSync` on the same canvas/context before calling TF, but there it succeeded.

My app had problems before. I (naively) created lots of canvases and contexts and ran into context losses. I dealt with them by "baking" the renders into static 2d contexts. Still, I had a hard time disposing of the objects and GPU memory in general (I generate with THREE.js).

The problem stopped occurring when I reduced the number of intermediate create-render-bake steps, so I assumed that *zombie contexts* might be lurking somewhere, or there might be timing problems/race conditions (I read somewhere that Chrom* and Firefox handle this differently).

I tried several approaches to improve the cleanup of my canvas map, but
what fixed the problem (ultimately, I hope) was to throw in THREE.js's [forceContextLoss()](https://threejs.org/docs/index.html?q=renderer#api/en/renderers/WebGLRenderer.forceContextLoss).

I'd share some code, but my app is still in development and quite messy.  
HTH anyway :)

**Comment by gaikwadrahul8** [comment] 2023-05-15 15:16
Hi, @kirill-konshin 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Closed** 2023-05-29 16:43 UTC
Labels: type:bug, stat:awaiting response, stalled, comp:backend-webgl
