### ISSUE TITLE
Error dumping weights duplicate weight name kernel

### ISSUE THREAD

**Issue by VineetKumar02** [tensorflow/tfjs#8233] opened 2024-04-07 12:49 UTC
```
from keras.models import Sequential
from keras.layers import LSTM, Dense
import tensorflowjs as tfjs

# Create a dictionary to store models for each bin
bin_models = {}

# Loop through each bin
for bin_name in field_names:
    # Create a new model for each bin with unique layer names
    model = Sequential([
        LSTM(50, return_sequences=True, input_shape=(time_steps, n_cols), name='lstm_1'),
        LSTM(64, return_sequences=False, name='lstm_2'),
        Dense(32, name='dense_1'),
        Dense(16, name='dense_2'),
        Dense(n_cols, name='dense_output')
    ])

    # Compile the model
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])

    # Train the model for the current bin
    mae, rmse, mse = lstm_for_bin(model, bin_name)
    print(f"Metrics for {bin_name}: MAE={mae}, RMSE={rmse}, MSE={mse}")

    # Save the model for each bin
    model_name = f"{bin_name}_lstm_model.h5"
    model.save(model_name)
    print(f"Model for {bin_name} saved as {model_name}")

    # Store the model in the dictionary
    bin_models[bin_name] = model

    # Convert the saved model to TensorFlow.js format
    tfjs.converters.save_keras_model(model, f'tfjs_models/{bin_name}')
```

I tried both ways to convert my keras model to tensorflowjs model. The error looks like this:
![image](https://github.com/tensorflow/tfjs/assets/84562170/e394bb86-b1bc-4c0e-bd2f-3922129b4a6d)
![image](https://github.com/tensorflow/tfjs/assets/84562170/70c991fb-5fc4-45d2-bbd5-5b9b13c9d3d4)

ANY IDEA HOW TO RESOLVE THIS ISSUE!!?

For questions on how to work with TensorFlow.js, or support for problems that are not verified bugs in TensorFlow.js, please go to [StackOverflow](https://stackoverflow.com/tags/tensorflow.js).

**Comment by gaikwadrahul8** [comment] 2024-04-12 05:11
Hi, @VineetKumar02 

I apologize for the delay in my response. I'm attempting to replicate the behavior you achieved in your Google Colab notebook. However, after running the preprocessing section code, I'm encountering `NaN` values in the pandas DataFrame. This is resulting in a `ValueError: Input contains NaN` error message.

For your reference, you can find the relevant Google Colab code snippet here: [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/1b9a418d42f6ba419593c09d23a224cf/issue-8233.ipynb).

I've carefully reviewed the code and ensured I'm using the same version as yours. However, I'm still unable to replicate the expected behavior. Could there be any additional steps or considerations I might be missing?

Thank you for your cooperation and patience.

**Comment by VineetKumar02** [comment] 2024-04-12 08:17
I'm not sure on why you are facing that issue. But i was able to find a temperory solution for this problem. When I install the  tensorflowjs package in colab, it's also installing tensorflow 2.16.1 which is causing the issue. So the workround that i found was to install the tensorflowjs first and thn force install tensorflow 2.15.0, then I was able to convert without any issue. You can see the gist file below: 
https://github.com/VineetKumar02/sample_lstm_code/blob/fa43dffee2408215d5ec2312c45aa98820a57b4a/fyp_lstm_all_download.ipynb

The model saved using tensorflow 2.15.0 looks like this:
![image](https://github.com/tensorflow/tfjs/assets/84562170/422604c8-6c7e-4a70-967e-7ab5dd93103c)

So i think the issue is with the latest version of tensorflow

**Comment by gaikwadrahul8** [comment] 2024-04-12 11:27
Hi, @VineetKumar02

My bad there was some issue with `Smart bins Argyle Square` dataset which I downloaded but now I have downloaded correct dataset and I'm able to run your Google colab [notebook](https://colab.sandbox.google.com/gist/gaikwadrahul8/520b05b2a1a407f273ad48241c57fa37/issue-8233-tfjs-converter.ipynb) without any error with Tensorflow.js version `4.17.0` and `Tensorflow 2.15.0` and yes you're absolutely correct after downloading the latest Tensorflow.js version it's installing the Tensorflow version `2.16.1`and it seems like tfjs- converter is not compatible with Tensorflow version 2.16.1 at the moment, thank you for bringing this issue to our attention and our team will work on this issue to make tfjs-converter compatible with Tensorflow version `2.16.1` soon

I'm able to replicate the previous issue also with latest version of `Tensorflow 2.16.1` and `Tensorflow.js 4.17.0`, for reference here is Google colab [notebook](https://colab.sandbox.google.com/gist/gaikwadrahul8/5c5e7fe7350715cbc064ecb909358d1d/issue-8233-not-working.ipynb)

If you are no longer experiencing problems after downgrading TensorFlow version to `2.15.0` before installing the `Tensorflow.js` , please feel free to close this issue

Thank you for your cooperation and patience.

**Closed** 2024-04-13 11:30 UTC
Labels: comp:converter, type:others, stat:awaiting response

**Comment by turbobuilt** [comment] 2024-04-16 12:33
I can't downgrade because I get another error

WARNING:root:Failure to load the inference.so custom c++ tensorflow ops. This error is likely caused the version of TensorFlow and TensorFlow Decision Forests are not compatible. Full error:/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE

  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/__init__.py", line 21, in <module>
    from tensorflowjs.converters.converter import convert
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 37, in <module>
    from tensorflowjs.converters import tf_saved_model_conversion_v2
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 28, in <module>
    import tensorflow_decision_forests
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/__init__.py", line 64, in <module>
    from tensorflow_decision_forests import keras
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/keras/__init__.py", line 53, in <module>
    from tensorflow_decision_forests.keras import core
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/keras/core.py", line 64, in <module>
    from tensorflow_decision_forests.keras import core_inference
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/keras/core_inference.py", line 38, in <module>
    from tensorflow_decision_forests.tensorflow.ops.inference import api as tf_op
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/api.py", line 179, in <module>
    from tensorflow_decision_forests.tensorflow.ops.inference import op
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/op.py", line 15, in <module>
    from tensorflow_decision_forests.tensorflow.ops.inference.op_dynamic import *
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/op_dynamic.py", line 24, in <module>
    raise e
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/op_dynamic.py", line 21, in <module>
    ops = tf.load_op_library(resource_loader.get_path_to_datafile("inference.so"))
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.10/dist-packages/tensorflow_decision_forests/tensorflow/ops/inference/inference.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKN4absl12lts_202308026StatusE

**Comment by VineetKumar02** [comment] 2024-04-17 04:30
@turbobuilt . Are you using google colab or running on your local system?

**Comment by myekini** [comment] 2024-04-18 12:35
i'm having this error too. 

File "/Users/muhammadyekini/Downloads/Muhammad_Yekini/CNN Image detection/venv/lib/python3.11/site-packages/tensorflowjs/write_weights.py", line 118, in write_weights
    _assert_no_duplicate_weight_names(weight_groups)
  File "/Users/muhammadyekini/Downloads/Muhammad_Yekini/CNN Image detection/venv/lib/python3.11/site-packages/tensorflowjs/write_weights.py", line 346, in _assert_no_duplicate_weight_names
    raise Exception(
Exception: Error dumping weights, duplicate weight name gamma
