### ISSUE TITLE
tfjs-models/qna demo fails 

### ISSUE THREAD

**Issue by sivi** [tensorflow/tfjs#3861] opened 2020-08-28 00:31 UTC
Current version of https://github.com/tensorflow/tfjs-models/tree/master/qna "findAnswers" outputs empty array, and running demo does not yield any answer, 
On the other hand, the same demo on [google hosted demo page](https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html) yields answers for the same question.

Difference between scripts in demo page source on google (<script src="./demo.e31bb0bc.js"></script>) and equivalent produced running demo from github repo is large.

As a matter of fact, I would appreciate, if someone can direct me how to download version that runs on google as a library that can be used, regardless of version.

**Comment by Download** [comment] 2020-08-28 07:33
> Current version of https://github.com/tensorflow/tfjs-models/tree/master/qna "findAnswers" outputs empty array

See #3858 which seems similar, because it also outputs just empty array.

**Comment by sivi** [comment] 2020-08-28 09:15
Version in https://github.com/tensorflow/tfjs-models/tree/244d4cdc6eee673ab1d03baccdb06db26bde86fa when extracted from built demo (whole set of steps on [stackoverflow](https://stackoverflow.com/a/63630389/14178011)) works as expected, even with @tensorflow/tfjs v.2.3.0.

What caused, I the problem, I do not know. Nevertheless, I appreciate GitHub history, which resolved my problem.

**Comment by guimcaballero** [comment] 2020-09-01 09:11
It seems like pinning `@tensorflow-models/qna` to version `1.0.0-alpha1` makes it work. I'm not sure what changed between that version and `1.0.0`, is anyone more knowledgeable than me able to take a look?

I'm using @tensorflow/tfjs v.2.3.0 too, in case it matters.

**Comment by pyu10055** [comment] 2020-09-03 21:58
@sivi @guimcaballero There are some difference with the model itself between the version. the alpha is trained on squad 1.0 dataset while 1.0.0 is trained on squad 2.0.
I have tried the demo with the latest tfjs 2.3.0 build, it is work for the question I asked.
Can you help with a codepen example with the question you asked that produce the empty answers? This would help us to reproduce the problem. thanks.

**Comment by mocleiri** [comment] 2020-12-02 11:47
FYI the demo at: https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html is broken now due to:

Error: 'multiply' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen

Full console trace:
```
Uncaught (in promise) Error: 'multiply' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen
    at av (tfjs:17)
    at t.multiply (tfjs:17)
    at Bt.runKernelFunc.a (demo.e31bb0bc.js:12672)
    at tfjs:17
    at tfjs:17
    at e.t.scopedRun (tfjs:17)
    at e.t.tidy (tfjs:17)
    at p (tfjs:17)
    at tfjs:17
    at e.t.scopedRun (tfjs:17)
```

**Comment by rthadur** [comment] 2020-12-14 21:08
@pyu10055 @jasonmayes can you please help fix the above issue.

**Comment by Zeesy** [comment] 2021-02-03 20:02
Any update on this issue? It would be helpful to know a timeline if possible. This is a great demo, there are a lot of us who would love to play with it again.

**Comment by mattsoulanille** [comment] 2021-02-11 22:52
Should be fixed. You may have to open dev tools, right click reload, and 'empty cache and hard reload' to make sure you get the new version. Also note that the demo has to download ~100Mb of model files before it responds to queries. It should really have a loading bar, but for now you can check the progress in the network panel of the browser developer tools.

**Closed by mattsoulanille** 2021-02-11 22:52 UTC
Labels: comp:models, type:bug
