### ISSUE TITLE
KeyError: 'class_name' while converting a tfjs_layers_model to tfjs_graph_model

### ISSUE THREAD

**Issue by harshithdwivedi** [tensorflow/tfjs#2623] opened 2019-12-27 16:32 UTC
#### TensorFlow.js version
1.4.0

#### Describe the problem or feature request
As mentioned in the title, I'm unable to convert a tfjs_layers_model to a corresponding tfjs_graph_model using the converter.

The command I used: 
```
tensorflowjs_converter --input_format tfjs_layers_model --output_format tfjs_graph_model model.json pb/ 
```

Error I got: 
```
2019-12-27 22:01:52.176799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "c:\users\harsh\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\harsh\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\harsh\Miniconda3\Scripts\tensorflowjs_converter.exe\__main__.py", line 7, in <module>
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 645, in pip_main
    main([' '.join(sys.argv[1:])])
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 649, in main
    convert(argv[0].split(' '))
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 625, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 366, in dispatch_tfjs_layers_model_to_tfjs_graph_conversion
    model = keras_tfjs_loader.load_keras_model(config_json_path)
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflowjs\converters\keras_tfjs_loader.py", line 218, in load_keras_model
    use_unique_name_scope=use_unique_name_scope)
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflowjs\converters\keras_tfjs_loader.py", line 65, in _deserialize_keras_model
    model = keras.models.model_from_json(json.dumps(model_topology_json))
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "c:\users\harsh\miniconda3\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 97, in deserialize
    layer_class_name = config['class_name']
KeyError: 'class_name' 
```

**Comment by rthadur** [comment] 2020-01-23 22:59
@harshithdwivedi can you please provide these things 
1) steps to reproduce the error.
2) Is it possible to try with latest tfjs version
3) please provide your system configuration.
Thanks

**Comment by rthadur** [comment] 2020-02-03 22:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2020-02-03 22:06 UTC
Labels: comp:converter, stat:awaiting response, type:support
