### ISSUE TITLE
Could you please elaborate the slowness of the first inference

### ISSUE THREAD

**Issue by msektrier** [tensorflow/tfjs#1715] opened 2019-07-02 09:31 UTC
### TensorFlow.js version
all. Part of the TFJS converter documentation.

#### Describe the problem or feature request
The [documentation of the TFJS converter](https://github.com/tensorflow/tfjs-converter/blob/master/README.md) states:

> "The time of first call also includes the compilation time of WebGL shader programs for the model. After the first call the shader programs are cached, which makes the subsequent calls much faster. You can warm up the cache by calling the predict method with an all zero inputs, right after the completion of the model loading."

This is correct and at the moment I do the warm up with a dummy. 

```
function init(model){
	const dummy = tf.zeros([1, 1, 1, 3], 'int32');
	console.log("dummy init ");
	return model.executeAsync( {[INPUT_TENSOR]: dummy}, OUTPUT_TENSOR ).then(function(result){
    	console.log('disposing my dummy');
		dummy.dispose();
		return result;
	});
}
```

However, it is blocking and I would like to know how to improve the user experience.
The models we load are between 3-10 MBytes but this warm-up takes several seconds to complete. 

Is there another way to do the warm up of these "WebGL shader programs" ? Do you have a suggestion to increase the warm up speed or at least how I can avoid the blocking?

**Comment by tafsiri** [comment] 2019-07-02 15:30
@msektrier Is the warmup time for a single model taking several seconds or is this the combined time for multiple models? Do you have any more precise timing info (along with device & browser information)? Also are these models internally constructing particularly large tensors (this will have an effect on the textures that need to be created). If the topology is something you could share we could take a closer look. The warmup time can be affected by the model architecture.

At the moment there isn't currently a way around the blocking nature of the shader program initialization, so to speed this up would involve looking into how to optimize the model itself to do fewer operations.

**Comment by msektrier** [comment] 2019-07-03 09:39
@tafsiri Many thanks that you take your time. 
At the moment it is about SSDLite Mobilnet V2 networks which we re-train. This is for me a single model. 
Usually it is running on my notebook with i7-855U with 16GB RAM. The webservers I am using is either NGINX or Cordova web platform. I am testing only in Chrome. 
The models are pretty small. The one I just tested is about 12 Mbytes (with converter quantization much smaller even).
[slow-ssdlite-mobilenetv2-model.zip](https://github.com/tensorflow/tfjs/files/3354258/slow-ssdlite-mobilenetv2-model.zip)
When I execute this code:

```
const INPUT_TENSOR = 'image_tensor';
const OUTPUT_TENSOR = ['detection_boxes', 'detection_scores'] 

function init(model){
	const dummy = tf.zeros([1, 10, 10, 3], 'int32');
	return model.executeAsync( {[INPUT_TENSOR]: dummy}, OUTPUT_TENSOR ).then(function(result){
		dummy.dispose();
		return result;
	});
}

let model = loadModel().then(function(model){
		predictionModel = model;
		console.log('model loaded.');
		console.log('current time before first prediction: '+new Date());
		console.log('Maximum texture size is ['+tf.ENV.getNumber('WEBGL_MAX_TEXTURE_SIZE')+']');
		console.log(tf.ENV.features);

		return init(predictionModel).then(function(dummyResult){
			console.log('init run completed.');
			console.log('current time after first prediction: '+new Date());
			freeMemory(dummyResult);
			return predictionModel;
		})
	})
```

Then this piece of code takes 11 seconds and WebGL is enabled. 

![image](https://user-images.githubusercontent.com/49950048/60581102-82f84d00-9d86-11e9-95c8-9d5027ccc892.png)

I think it is quite a lot of time. When we use the quantized version (1byte) of 3 MBytes then the time is also 11-12 seconds. 

![image](https://user-images.githubusercontent.com/49950048/60581341-e8e4d480-9d86-11e9-8f5f-d75c31626b16.png)
****
On my mobile phone it also takes some time to load.

**Comment by tafsiri** [comment] 2019-07-03 15:07
That does sound quite long, and just to confirm, your experience is that after the first inference execution is faster? 

Could you post how long it takes to do an inference after the first one is complete?

Secondly, could you turn on debug mode and profile the inference? The code for that will look something like this

```js
tf.ENV.set('DEBUG', true);
const profile = await tf.profile(async () => {
	// do your model inference here
});
console.log(profile);
tf.ENV.set('DEBUG', false);
```

The output of this may be a quite large object, so it would probably be best to copy it into a text file and upload it here. See this[ article](https://scottwhittaker.net/chrome-devtools/2016/02/29/chrome-devtools-copy-object.html) for a description of how to copy from console.

**Comment by jessetrana** [comment] 2019-07-04 03:07
As a reference point, I have an unquantized 12MB model derived from MobileNetV2 with some custom layers on the end. My computer is one of the i7-based Lenovo Flex 5's. I do a similar load + fake warmup call and it takes 6-7 seconds executing in the context of a Firefox plugin. A bit faster, yes, but roughly the same order of magnitude.
Inferences after that go down significantly as reported over [here](https://github.com/tensorflow/tfjs/issues/1530)

**Comment by msektrier** [comment] 2019-07-05 07:12
@tafsiri yes the second execution takes milliseconds. 

I executed 

```
async function init(model){
	tf.ENV.set('DEBUG', true);
	const profile = await tf.profile(async () => {
		const dummy = tf.zeros([1, 10, 10, 3], 'int32');
		model.executeAsync( {[INPUT_TENSOR]: dummy}, OUTPUT_TENSOR ).then(function(result){
			dummy.dispose();
			return result;
		});
	});
	console.log(profile);
	tf.ENV.set('DEBUG', false);

	return profile;
}
```

Of course due to "async" the execution of the scripts continued directly but it remains blocking. 

![image](https://user-images.githubusercontent.com/49950048/60704507-ec9e6580-9f04-11e9-887f-c74abe2835ec.png)

The output of "profile" is attached. Many thanks. 
[log.txt](https://github.com/tensorflow/tfjs/files/3361514/log.txt)

**Comment by tafsiri** [comment] 2019-07-08 14:11
@msektrier Could you try adding `tf.ENV.set('WEBGL_PACK', false)` near the top of your program (before any operations are called) and report if that makes any difference. It would also be helpful for us to know which version of tfjs you are using in the browser.

cc @annxingyuan Might this be related to the other issue you are working on that @jessetrana mentioned here.

**Comment by msektrier** [comment] 2019-07-09 12:17
@tafsiri we are taking the latest version 
`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script> `

I have to say setting `tf.ENV.set('WEBGL_PACK', false)` has nearly no impact. However, the load is about 3-4 seconds faster compared to `tf.ENV.set('WEBGL_PACK', true)`. Still, my load time is about 10 seconds. 

![image](https://user-images.githubusercontent.com/49950048/60887245-27313680-a254-11e9-9f28-fb3747a78523.png)

Just for my information: Does WEBGL_PACK disable the WebGL engine? I ask since if I execute `tf.getBackend()` in the console it will show "webgl" with enabled/disabled WEBGL_PACK.

**Comment by msektrier** [comment] 2019-07-15 09:53
Any updates on this topic?

**Comment by jessetrana** [comment] 2019-07-17 05:41
Well, on the off chance it is related to the other issue (#1530), I think trying it with a pre-1.x version (if possible/easy) would be worth doing and then reporting the numbers. Then we would know if it is a regression or perhaps just the current state of performance.

**Comment by tafsiri** [comment] 2019-09-23 21:27
Hi there, not sure if you found another solution in the meantime, but I have some updated thoughts. Unfortunately there is no clean direct answer to why this may take so long.

1. In the past couple of months we've made some improvements to how the converted models are executed, this should reduce the number of nodes that are evaluated and potentially the number of shaders/textures created. So I would start by trying out the latest version of tfjs and seeing how long it takes.
2. Doing a warmup with a tensor that doesn't match the size of what you will be passing in later doesn't help all that much. Shaders will be recompiled with new tensor shapes and the texture cache won't really be helpful if the warmup tensors is very different from the actual thing you want to run inference on.
3. An idea I had to make the initialization block the UI less is to do the warmup execution (with a realistically sized tensor) through the model in chunks. i.e. you would call `model.executeAsync` from the input to a number of intermediate nodes in series, and in between you can return control to the UI. It would look something like calling model.executeAsync many times progressively getting close to the actual outputs you want. I have no suggestions on which intermediate nodes to use though. They just need to be along the path from input to output. This does not change overall warmup time, but tries to break it up into chunks.
4. The profile log file you uploaded had very few ops. I think there was an `await` missing in the line calling `model.executeAsync` adding that should give a more accurate profile. I was mostly curious to look at peak memory usage and compare that with available gpu memory on the device you are testing.

To answer your question about WEBGL_PACK, it does not turn off webgl. It just changes how we write data to textures.

**Comment by rthadur** [comment] 2020-02-05 21:07
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2020-02-05 21:07 UTC
Labels: comp:converter, comp:core, type:support
