### ISSUE TITLE
object detection not same with the python detect using same custom model

### ISSUE THREAD

**Issue by yclau** [tensorflow/tfjs#7565] opened 2023-04-09 15:30 UTC
I'm new in machine learning and I try to build object detection to count steel.
 
 Below Image is my output in python using ssd_mobilenet_v2_320x320_coco17_tpu-8
![detection_output2](https://user-images.githubusercontent.com/4135524/230781528-c362d4fe-aca7-41d7-95db-147a334bace4.png)

After that I use the tensorflowjs_wizard to convert saved_model to model.json and using below code to detect , but it keep detect 1 object only. May I know is it my model problem or code problem ??

Below is my code 
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.9.0"></script> 
</head>
<body>
    <img src="Img/19.jpg" id="myImage"  />
    <canvas id="outputCanvas"></canvas>
    <span id="total"></span> 
    <script type="text/javascript"> 

        const imgElement = document.getElementById('myImage');
        const canvas = document.getElementById('outputCanvas'); 

        tf.ready().then(() => {

            tf.setBackend('cpu');

            tf.loadGraphModel('https://localhost:44349/web_model/model.json').then(model => {

                const input = tf.browser.fromPixels(imgElement);

                const resized = tf.image.resizeBilinear(input, [1, 1]);

                const normalized = resized.div(tf.scalar(255)).sub(tf.scalar(1));

                const batched = normalized.expandDims(0).toInt();

                model.executeAsync(batched).then(predictions => {
                    const boxes = predictions[0].dataSync();
                    const scores = predictions[1].dataSync(); 
                    const numDetections = predictions[3].dataSync()[0];  

                    const detections = [];
                    for (let i = 0; i < numDetections; i++) { 
                        const score = scores[i];
                        const bbox = [boxes[i * 4 + 1],
                        boxes[i * 4],
                        boxes[i * 4 + 3],
                        boxes[i * 4 + 2],
                        ];
                        detections.push({ score, bbox });
                    } 
                   
                    canvas.width = imgElement.width;
                    canvas.height = imgElement.height;
                    const ctx = canvas.getContext('2d');
                    ctx.drawImage(imgElement, 0, 0);

                    var total = 0;
                    detections.forEach((detection) => {
                        if (detection.score > 0.3) {
                            const [ymin, xmin, ymax, xmax] = detection.bbox;
                            const left = xmin * imgElement.width;
                            const top = ymin * imgElement.height;
                            const right = xmax * imgElement.width;
                            const bottom = ymax * imgElement.height;
                            const width = right - left;
                            const height = bottom - top; 
                            total++; 
                            ctx.strokeStyle = '#f70101';  
                            ctx.lineWidth = 10;
                            ctx.strokeRect(left, top, width, height); 
                        }
                    }); 
                    document.getElementById('total').innerText = total;  
                }); 
            });
        }); 
    </script>
</body>
</html>
```

**Comment by gaikwadrahul8** [comment] 2023-04-10 06:59
Hi, @yclau 

Apologize for the delayed response and if possible could you please help us with model files(model.json and .bin files in zip folder) after `tfjs-convertor `command so we'll try to reproduce the same issue from our end ? Thank you!

**Comment by yclau** [comment] 2023-04-10 13:08
Below is my model.json and bin folder
[web_model.zip](https://github.com/tensorflow/tfjs/files/11190629/web_model.zip)

I using tensorflowjs_wizard to convert, below is my command

![Screenshot 2023-04-10 210658](https://user-images.githubusercontent.com/4135524/230906999-0dc48857-10f1-47e5-b714-2f6874c5f7af.png)

**Comment by yclau** [comment] 2023-04-13 06:50
Hi ,
I found the problem executeAsync inside prediction result array will random. for example when my model load, predictions[0] maybe is other value not the box value. 

thx for support

**Comment by gaikwadrahul8** [comment] 2023-04-13 10:58
Hi, @yclau 

Good to hear that you resolved your issue and I was trying to replicate the issue from my end but unfortunately I was getting this error message `Not allowed to load local resource: file://users/gaikwadrahul/Desktop/TFJS/Img:19.jpg` and I was trying to go with browser setting option under Privacy and Security section to select `No protection (not recommended)` option get rid of that error message but I was unable to do it may be due to my system security anyway but I'm glad you able to resolve it from your end only 

If you're looking to map the exact values in `executeAsync()` then you can do something like below if I'm not wrong

```
const test_result = await model.executeAsync({ image_tensor: tf4d }, ['detection_boxes', 'num_detections', 'detection_classes', 'detection_scores']) as tf.Tensor[];
        
        const detection_boxes = test_result[0].dataSync();
        const num_detections = test_result[1].dataSync();
        const detection_classes = test_result[2].dataSync();
        const detection_scores = test_result[3].dataSync();
```
I would request you to please refer this [object detection example](https://github.com/tensorflow/tfjs-models/blob/master/coco-ssd/src/index.ts) and also refer implementation of `executeAsync()` [here](https://github.com/tensorflow/tfjs/blob/5cc0c776c188f074757744c2eec9e965b8e2eb89/tfjs-converter/src/executor/graph_model.ts#L510-L521) which may help you to understand and solve your issue 

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? 

If issue still persists please let us know ? Thank you!

**Closed** 2023-04-27 11:12 UTC
Labels: comp:converter, comp:models, type:others, stat:awaiting response, stalled
