### ISSUE TITLE
Obtain a different model by converting the tensorflow JS (tfjs) to python (keras)

### ISSUE THREAD

**Issue by wirlsawyer** [tensorflow/tfjs#5498] opened 2021-08-16 01:56 UTC
**System information**
- Have I written custom code : [download](https://drive.google.com/file/d/10alQ8HIwix_EcWYLO6X8Jt5-rw1wA6PF/view?usp=drivesdk)
- OS Platform and Distribution : MacOS v11.0.1
- Mobile device : None
- TensorFlow.js installed from (npm or script link): script link https://unpkg.com/ml5@0.6.1/dist/ml5.min.js
- TensorFlow.js version (use command below): P5 v1.4.0, ML5 v0.6.1
- Browser version: Chrome v92.0.4515.107 
- Tensorflow.js Converter Version: v3.7.0

**Describe the current behavior**
The goal is to convert the tensorflow JS (tfjs) to python (keras). However, input the same parameters to both tfjs and keras will get the different results.

**Describe the expected behavior**
If we input the same parameters to both tfjs and keras, the result should be the same.

**Standalone code to reproduce the issue**
Step1. Construct a simple model to learn the summation of two units digits by using tfjs. Then, train the model.
Step2. Save the trained model, which automatically generates three files, such as “model_meta.json”, “model.json”, “model.weights.bin”.
Step3. (js2h5.py)Convert three files from step2 to python, and obtained a file called “model.h5”
Step4. Using python (keras) to read “model.h5”
Step5. Input the same arguments to predict the result. However, the result is different between tfjs and keras. For example, input 8+4, tfjs gets 12.5162(sum.html), but keras gets 1(predict.py).

To clarify this problem, my approach is to use the official released tool “tensorflowjs_converter” to convert “model.h5” to tfjs. However, it only outputs two files “group1-shard1of1.bin” and “model.json”.
By using the binary compared tool, we can find that:
“model.json” is different from the file “model.json” obtained from step2.
“group1-shard1of1.bin” is same as the file “model.json” obtained from step2.

Furthermore, if I use tfjs to read both “group1-shard1of1.bin” and “model.json”, it shows an error message:
Uncaught (in promise) Error: Weight file with basename 'group1-shard1of1.bin' is not provided.

**Comment by rthadur** [comment] 2021-08-16 19:34
Hi @wirlsawyer , we will not be supporting https://unpkg.com/ml5@0.6.1/dist/ml5.min.js as this is thrid party library , please reach out to ml5. You can follow these below using latest tfjs version 
1) train the model and save using [model.save](https://js.tensorflow.org/api/latest/#tf.LayersModel.save).
2) then convert the model using tfjs-converter
3) Load the model in Keras using tf.keras.load_model(...)

**Comment by rthadur** [comment] 2021-08-16 19:34
Closing this as this is not a bug or feature request for tfjs library.

**Closed by rthadur** 2021-08-16 19:34 UTC
Labels: type:bug
