### ISSUE TITLE
Implement op: BatchMatMul

### ISSUE THREAD

**Issue by hmartiro** [tensorflow/tfjs#255] opened 2018-05-01 23:43 UTC
Wanted to document an operation I'm missing for a 3D computer vision app: BatchMatMul

Other missing ops:
 * StridedSlice (https://github.com/tensorflow/tfjs/issues/242)
 * Unpack
 * ClipByValue (very minor)

python package versions:
tensorflowjs==0.2.1, tensorflow==1.7.0

**Comment by loretoparisi** [comment] 2018-07-27 13:05
@hmartiro @dsmilkov Other operations missing

- MatrixBandPart
- RandomShuffleQueueV2
- QueueDequeueManyV2

**Comment by dsmilkov** [comment] 2018-08-27 14:54
Duplicate of https://github.com/tensorflow/tfjs/issues/539

**Closed by dsmilkov** 2018-08-27 14:54 UTC
Labels: converter, core
