### ISSUE TITLE
Error when trying to load  a Sesquential model

### ISSUE THREAD

**Issue by RilRil** [tensorflow/tfjs#1613] opened 2019-05-25 18:01 UTC
#### TensorFlow.js version
1.1.2

#### Browser version
Chrome Version 74.0.3729.169 (Official Build) (64-bit)

#### Describe the problem or feature request
Hello, 
I have a working Sequential model (which is saved correctly in my indexeddb) and I try to load it using `tf.loadLayersModel('indexeddb://mymodel')`
when I try to load it I get this error: ` Error: The first layer in a Sequential model must get an 'inputShape' or 'batchInputShape' argument.`

I can't try it via localstorage because the model is too big but I did try it via files and  got the exact same error.

any idea on what I did wrong here ?

thanks !

**Comment by caisq** [comment] 2019-05-26 02:01
@RilRil Can you tell us how the model was created? Was it constructed in TensorFlow.js or converted from Python?

**Comment by RilRil** [comment] 2019-05-26 09:06
hi @caisq ! It was fully created in Tensorflow.js

here is a sample code :
```
  const model = tfjs.sequential()

  const input = tfjs.input({ shape: [SEQ_LEN, 2] })
  const lstm1 = tfjs.layers.lstm({ units: 128, returnSequences: true })
  lstm1.apply(input)
  model.add(lstm1)
  model.add(tfjs.layers.dropout({ rate: 0.2 }))
  model.add(tfjs.layers.batchNormalization())

[...]
```

**Comment by RilRil** [comment] 2019-05-26 09:46
@caisq I tried another way to construct my first layer and it worked !
I define the input layer in the 'inputShape' property of the LSTM function instead of creating an input and applying it to the LSTM (see code above)

here the code now
```
  const lstm1 = tfjs.layers.lstm({ units: 128, returnSequences: true, inputShape: [SEQ_LEN, 2] })
  model.add(lstm1)
  model.add(tfjs.layers.dropout({ rate: 0.2 }))
  model.add(tfjs.layers.batchNormalization())
 [...]
```
I can load my model like described in the documentation now \o/

I dont know if I was doing a mistake before or this is a bug.

**Comment by caisq** [comment] 2019-05-26 14:02
@RilRil Thanks for the info. I think TensorFlow.js is working as intended in this case. If you use `apply()` to connect layers, you should construct a model using `tf.model()`, instead of `tf.sequential()`. I'll close the issue now. Feel free to comment or reopen the issue if you have further thoughts.

**Closed by caisq** 2019-05-26 14:02 UTC
Labels: comp:layers
