### ISSUE TITLE
bug: The `tf.all` operation has incorrect behavior in browser in windows 10

### ISSUE THREAD

**Issue by somombo** [tensorflow/tfjs#968] opened 2018-12-06 14:44 UTC
#### TensorFlow.js version
0.14.0

#### Browser version
Tried it on the following browser in Windows 10:
- Chrome 71.0.3578.8
- Firefox 63.0.3 (64-bit)
- Edge 42.17134.1.0

#### Describe the problem
The operation `tf.all([0, 1, 1, 1, 1])` incorrectly results in `1`. This appears to be the case regardless of how many additional ones you had to the input array. However if they are less than 4 ones then it works fine. I also briefly tested this in tf-nodejs (and the equivalent thing in python) and that works as expected.

#### Code to reproduce the bug
See the following [live code here](https://codepen.io/somombo/pen/NEQbGX?editors=0011).

```html
<html>
  <head>
    <!-- Load TensorFlow.js -->
    <script 
      src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.14.0/dist/tf.min.js">
    </script>

  </head>

  <body>
    <script>

      tf.tensor([0, 1, 1, 1, 1])
        .cast('bool')
        .all() 
        .print() // outputs 1 in browser instead of the 0 that this outputs in nodejs/python 

      tf.tensor([0, 1, 1, 1])
        .cast('bool')
        .all()  
        .print() // however this outputs 0
              
    </script>
  </body>
</html>
```

**Comment by rthadur** [comment] 2018-12-07 23:46
@somombo  tried to reproduce the issue but it gave me 0 both time.

**Comment by somombo** [comment] 2018-12-08 02:30
@rthadur that's odd..
I have also tried in Firefox, Edge and Chrome. I'm using windows 10.

For what it's worth, here is a screenshot of what i'm seeing

![image](https://user-images.githubusercontent.com/5506400/49680830-f90f2c80-faa1-11e8-843d-19887318d84d.png)

**Comment by somombo** [comment] 2018-12-10 00:48
@rthadur after asking around, a friend who has a mac machine and and one with linux ... it appears those OS's are working fine. However, another friend was able to consistently reproduce this issue on windows 10

**Comment by sblabms** [comment] 2018-12-10 07:12
Bug confirmed!
Also: tf.all() fails on Chrome on Windows for every 4 elements added to a 1D boolean tensor.

Using Chrome Version 71.0.3578.80 (Official Build) (64-bit) in Windows 8:

Start with a boolean 5 element 1D tensor. tf.all fails. Keep adding a 0 element. You will find that tf.all fails for every 4 elements (9, 13, 17, 21...) added to the 1D tensor. See image.
![tfallfailinchromeonwindows](https://user-images.githubusercontent.com/20588611/49716144-7361bd00-fc18-11e8-9a49-773313863512.png)

**Comment by somombo** [comment] 2018-12-10 07:32
wow thanks for finding that as well @sblabms, this is quite peculiar! So to be clear, it works fine if there are any other numbers of zeros except those consistent with that arithmetic sequence. So for example [1,0,0,0,0,1] (for zeros) works and so does [1,0,0,0,0,0,0,0,0,1] (eight zeros) passes the test

**Comment by somombo** [comment] 2018-12-10 21:09
@tafsiri or @rthadur, kindly confirm you've been able to reproduce this issue (on windows), so that we can start having productive discussions about potential causes.

**Comment by tafsiri** [comment] 2018-12-11 15:13
cc @dsmilkov any chance you could look at this on a windows machine?

**Comment by somombo** [comment] 2019-03-07 09:56
@nsthorat how has the "stable" version v1.0.0 been released when this issue (which is a major bug in my opinion) is still open??

**Comment by rthadur** [comment] 2019-09-05 22:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2019-09-05 22:55 UTC
Labels: type:bug
