### ISSUE TITLE
When in webgl backend,  tf.isNaN() produces incorrect results

### ISSUE THREAD

**Issue by liliquan0118** [tensorflow/tfjs#5800] opened 2021-11-01 08:23 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): script link
- TensorFlow.js version (use command below): 3.11.0
- Browser version:   Google Chrome  93.0.4577.63
- Tensorflow.js Converter Version:
- 
**Describe the current behavior**
tf.isNaN() has different results when running on different backends. For example, for the following code:
```
     const y = tf.tensor1d([Infinity, .5, 4, -38.8, NaN]);
     y.isNaN().print();
```
In **webgl backend**, the output is 
```
    Tensor
    [false, false, false, false, false]
```
In **cpu backend**, the output is 
```
    Tensor
    [false, false, false, false, true]
```
In **wasm backend**, get the error is 
```
Uncaught (in promise) Error: Kernel 'IsNan' not registered for backend 'wasm'
```
**These results indicate that tf.isNaN()cannot correctly recognize NaN in webgl backend.**

**Describe the expected behavior**
According to the official documentation，tf.isNaN(x) RReturns which elements of x are NaN.
Therefore, the correct result should be
```
    Tensor
    [false, false, false, false, true]
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
the code to reproduce the problem is
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
</head>
<body>
<script>
 async function nan_test() {
     const y = tf.tensor1d([Infinity, .5, 4, -38.8, NaN]);  
     tf.setBackend("webgl");
     await tf.ready();
     console.log("webgl backend result:");
     y.isNaN().print();
     tf.setBackend("cpu");
     await tf.ready();
     console.log("cpu backend result:");
     y.isNaN().print();
     tf.setBackend("wasm");
     await tf.ready();
     console.log("wasm backend result:");
     y.isNaN().print();
    }
    nan_test();
</script>
</body>
</html>

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached
the code to reproduce the problem
[nan_test.zip](https://github.com/tensorflow/tfjs/files/7451685/nan_test.zip)
.

**Comment by rthadur** [comment] 2021-11-01 16:43
I tried in lates chrome browser(MAC OS) and was not able to see above behavior 
![image](https://user-images.githubusercontent.com/43972606/139707905-c6f8ae3c-60c1-4bfe-b35a-073a58afa264.png)

**Comment by liliquan0118** [comment] 2021-11-02 09:48
@rthadur Thank you for your prompt reply.  I did the test again, and this problem does exist on **ubuntu** (ThinkPad and Dell).  I also tested it on Mac and Windows, and I really can't see this behavior. This is strange, what is the reason?
The output of chrome on Ubuntu is as follows:
![image](https://user-images.githubusercontent.com/68681463/139823893-6d9d3d10-15a5-419c-8ca6-a836f29003fd.png)

**Comment by rthadur** [comment] 2021-11-02 16:23
Can you try run this https://js.tensorflow.org/debug/ and provide screenshot ?

**Comment by liliquan0118** [comment] 2021-11-02 16:33
This is screenshot:
![image](https://user-images.githubusercontent.com/68681463/139906826-4084707e-32d6-4ecf-b0ae-3c50b8c852bc.png)

**Comment by rthadur** [comment] 2021-11-02 16:36
can you please upgrade to Chrome latest and try ?

**Comment by liliquan0118** [comment] 2021-11-02 16:53
I have updated Chrome to version 95.0.4638.69 and the error still exists. In addition, there is the same error on firefox.
The debug information is as follows
![Selection_139](https://user-images.githubusercontent.com/68681463/139910003-bfa858c6-1076-44db-b814-7848697c9016.png)

**Comment by liliquan0118** [comment] 2021-11-23 19:13
![image](https://user-images.githubusercontent.com/68681463/143088806-027cedbc-eea4-4c5d-b58a-86d1bb1eab8c.png)
Thank you for fixing this issue, but I have some doubts. First , I feel that the current changes cannot explain the incorrect results under Linux. In your fix,  delete ` return (val > 0.0 || val < 0.0) ? false : val != 0.0;` and add `return val != val;` . However, in Linux, when ` val=NaN`, the result of `(val > 0.0 || val < 0.0) ? false : val != 0.0` a is TRUE, as expected . So is this issue caused by the insufficient webgl support under Linux? as stated by ahmedsabie “Modify the implementation to also support UHD Graphics on Linux” .  Second, I would like to ask if this fix will be updated to the future version？ Thanks again.

**Comment by ahmedsabie** [comment] 2021-11-29 19:25
The issue is caused by WebGL being optimized and supported slightly differently across different GPUs so behavior isn't always consistent. The issue is more of an Intel UHD Graphics issue rather than a Linux one. Yes the fix will be added to the next release once merged!

**Comment by shaoboyan** [comment] 2022-01-26 06:26
@ahmedsabie @liliquan0118 
I have a [PR](https://github.com/tensorflow/tfjs/pull/6075) to implement isnan in webgpu backend. The implementation follows [IEEE 754-1985](https://en.wikipedia.org/wiki/IEEE_754-1985#Representation_of_non-numbers) which should be platform-independent and strict. So
- Is this bit-level check isnan implementaion suitable for tfjs?
- Do you think is it possible to have similar implementation in webgl backend?

**Comment by rthadur** [comment] 2022-03-10 15:53
Related PR has been merged , closing this request. Thank you

**Closed by rthadur** 2022-03-10 15:53 UTC
Labels: type:bug
