### ISSUE TITLE
tf.Conv2D on WebGL unreliable for large inputs

### ISSUE THREAD

**Issue by manueldois** [tensorflow/tfjs#1936] opened 2019-08-28 19:53 UTC
#### TensorFlow.js version
1.2.8

#### Browser version
Brave. Version 0.67.123 Chromium: 76.0.3809.87 (Official Build) (64-bit)

#### Describe the problem or feature request
tf.Conv2D, when used on a WebGL backend, sometimes returns a seemingly random output when the input image tensor is large ( > 200 )

I am using TF to run Conway's Game of Life.
The world is an int32 tensor where 0 is a dead cell and 1 is a living cell
The convolution is used to count the number of neighbors alive around each cell.
This is done using the filter:

```javascript
        const FILTER = tf.tensor(
            [
                [[[1]], [[1]], [[1]]],
                [[[1]], [[0]], [[1]]],
                [[[1]], [[1]], [[1]]]
            ]
        )
```
And stride `[1, 1]`

The app is done and works for world sizes of up to 2000 * 2000.
Just for certain world sizes, around 200 * 200 and 300 * 300, the tf.conv2D returns incorrect neighbor counts. The exact same code works on most world sizes.

When running with a CPU backend the problem is no more.

#### Code to reproduce the bug / link to feature request
A live test app is available at https://codesandbox.io/s/tensorflow-conv2dtest-4oudz

[TF-Conv2DTest.zip](https://github.com/tensorflow/tfjs/files/3552575/TF-Conv2DTest.zip)

Ubuntu 18.04.3 LTS, 64bit
Graphics: Intel® Haswell Mobile

**Comment by tafsiri** [comment] 2019-08-30 18:13
Hi @manueldois, thanks for the live reproduction. I wasn't able to get the result you describe on my machine though (also running linux, tried in Chrome and Firefox).

Here is the link to the version i made https://codesandbox.io/s/tensorflow-conv2dtest-l4jw1

I edited yours to just focus on the '300' case which you were having issues with. I added a block of code to check the difference between the output from cpu backend and output from webgl. Here is the output i get.

```
Testing with a 2D Tensor of size: 300 * 300 ... 
WORLD 
Tensor
    [[0, 0, 1, ..., 1, 1, 0],
     [0, 1, 0, ..., 1, 1, 1],
     [1, 1, 0, ..., 0, 0, 1],
     ...,
     [1, 0, 1, ..., 1, 0, 0],
     [0, 0, 1, ..., 1, 0, 1],
     [0, 1, 1, ..., 0, 0, 1]] 
Rank:  
2

Shape:  
[300, 300]

Type:  
int32 
N_NEIGHBORS 
Tensor
    [[1, 2, 1, ..., 3, 4, 3],
     [3, 3, 4, ..., 4, 5, 3],
     [4, 4, 4, ..., 4, 6, 3],
     ...,
     [1, 4, 2, ..., 2, 4, 1],
     [2, 5, 3, ..., 1, 4, 1],
     [1, 2, 2, ..., 1, 3, 1]] 
Rank:  
2

Shape:  
[300, 300]

Type:  
int32 
The above does NOT work for me. Tensor N_NEIGHBORS is NOT the sum of the cells around each cell in Tensor WORLD, but something seemingly random. 
Testing with a 2D Tensor of size: 300 * 300 ... 
WORLD 
Tensor
    [[0, 0, 1, ..., 1, 1, 0],
     [0, 1, 0, ..., 1, 1, 1],
     [1, 1, 0, ..., 0, 0, 1],
     ...,
     [1, 0, 1, ..., 1, 0, 0],
     [0, 0, 1, ..., 1, 0, 1],
     [0, 1, 1, ..., 0, 0, 1]] 
Rank:  
2

Shape:  
[300, 300]

Type:  
int32 
N_NEIGHBORS 
Tensor
    [[1, 2, 1, ..., 3, 4, 3],
     [3, 3, 4, ..., 4, 5, 3],
     [4, 4, 4, ..., 4, 6, 3],
     ...,
     [1, 4, 2, ..., 2, 4, 1],
     [2, 5, 3, ..., 1, 4, 1],
     [1, 2, 2, ..., 1, 3, 1]] 
Rank:  
2

Shape:  
[300, 300]

Type:  
int32 
Works, correct but different output than with GPU 
diff 
Tensor
    [[false, false, false, ..., false, false, false],
     [false, false, false, ..., false, false, false],
     [false, false, false, ..., false, false, false],
     ...,
     [false, false, false, ..., false, false, false],
     [false, false, false, ..., false, false, false],
     [false, false, false, ..., false, false, false]] 
diffsum 
Tensor
    0 
```

The last value suggests that the two tensors are the same. Are you getting different results?

@rthadur If you have a chance to open the link above in chrome and check the final line of console output to see if is zero or not.

**Comment by rthadur** [comment] 2019-08-30 18:28
@tafsiri i got the same result in both chrome and Firefox with output zero.

**Comment by tafsiri** [comment] 2019-08-30 19:05
@rthadur any chance you could try in brave? It shouldn't be different but would be good to know.

**Comment by manueldois** [comment] 2019-08-30 19:51
Thank you both! It's best to fight a bug together!

Apparently the bug depends on the machine. I ran tafsiri's code on my laptop and phone:

```
Testing tafsiri's live app at https://codesandbox.io/s/tensorflow-conv2dtest-l4jw1

On my laptop...

Using Brave on Ubuntu on my laptop:

    Testing with a 2D Tensor of size: 300 * 300 ... 
    WORLD Tensor
        [[0, 0, 1, ..., 1, 1, 0],
        [0, 1, 0, ..., 1, 1, 1],
        [1, 1, 0, ..., 0, 0, 1],
        ...,
        [1, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 1, 0, 1],
        [0, 1, 1, ..., 0, 0, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    N_NEIGHBORS Tensor
        [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 1, 2, 1],
        [0, 1, 1, ..., 1, 2, 2],
        ...,
        [1, 1, 0, ..., 1, 1, 0],
        [1, 1, 1, ..., 1, 1, 0],
        [0, 0, 1, ..., 1, 1, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    The above does NOT work for me. Tensor N_NEIGHBORS is NOT the sum of the cells around each cell in Tensor WORLD, but something seemingly random. 
    Testing with a 2D Tensor of size: 300 * 300 ... 
    WORLD Tensor
        [[0, 0, 1, ..., 1, 1, 0],
        [0, 1, 0, ..., 1, 1, 1],
        [1, 1, 0, ..., 0, 0, 1],
        ...,
        [1, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 1, 0, 1],
        [0, 1, 1, ..., 0, 0, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    N_NEIGHBORS Tensor
        [[1, 2, 1, ..., 3, 4, 3],
        [3, 3, 4, ..., 4, 5, 3],
        [4, 4, 4, ..., 4, 6, 3],
        ...,
        [1, 4, 2, ..., 2, 4, 1],
        [2, 5, 3, ..., 1, 4, 1],
        [1, 2, 2, ..., 1, 3, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    Works, correct but different output than with GPU 
    HIHI 
    diff 
    Tensor
        [[true , true , true , ..., true , true , true ],
        [true , true , true , ..., true , true , true ],
        [true , true , true , ..., true , true , true ],
        ...,
        [false, true , true , ..., true , true , true ],
        [true , true , true , ..., false, true , true ],
        [true , true , true , ..., false, true , false]] 
    diffsum 
    Tensor
        81891 


Using Firefox on Ubuntu on my laptop:
    // Same as above (Brave on Ubuntu on laptop)

Using Chromium on Ubuntu on my laptop:
    // Same as above (Brave on Ubuntu on laptop)




On Mobile...

Using Brave on Android on Samsung A6:

    Testing with a 2D Tensor of size: 300 * 300 ... 
    WORLD Tensor
        [[0, 0, 1, ..., 1, 1, 0],
        [0, 1, 0, ..., 1, 1, 1],
        [1, 1, 0, ..., 0, 0, 1],
        ...,
        [1, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 1, 0, 1],
        [0, 1, 1, ..., 0, 0, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    N_NEIGHBORS Tensor
        [[1, 2, 1, ..., 3, 4, 3],
        [2, 3, 4, ..., 4, 5, 3],
        [3, 4, 4, ..., 4, 6, 3],
        ...,
        [1, 4, 2, ..., 2, 4, 1],
        [2, 5, 3, ..., 1, 4, 1],
        [1, 2, 2, ..., 1, 3, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    The above does NOT work for me. Tensor N_NEIGHBORS is NOT the sum of the cells around each cell in Tensor WORLD, but something seemingly random. 
    Testing with a 2D Tensor of size: 300 * 300 ... 
    WORLD Tensor
        [[0, 0, 1, ..., 1, 1, 0],
        [0, 1, 0, ..., 1, 1, 1],
        [1, 1, 0, ..., 0, 0, 1],
        ...,
        [1, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 1, 0, 1],
        [0, 1, 1, ..., 0, 0, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    N_NEIGHBORS Tensor
        [[1, 2, 1, ..., 3, 4, 3],
        [3, 3, 4, ..., 4, 5, 3],
        [4, 4, 4, ..., 4, 6, 3],
        ...,
        [1, 4, 2, ..., 2, 4, 1],
        [2, 5, 3, ..., 1, 4, 1],
        [1, 2, 2, ..., 1, 3, 1]] Rank:  
    2
    Shape:  
    [300, 300]
    Type:  int32 
    Works, correct but different output than with GPU 
    HIHI 
    diff 
    Tensor
        [[false, false, false, ..., false, false, false],
        [true , false, false, ..., false, false, false],
        [true , false, false, ..., false, false, false],
        ...,
        [false, false, false, ..., false, false, false],
        [false, false, false, ..., false, false, false],
        [false, false, false, ..., false, false, false]] 
    diffsum 
    Tensor
        138 

Using Chrome on Android on Samsung A6+:
    // Same as above (Brave on Android on phone)
```

I tried to dig some info about the driver on my laptop and got the output below.
I don't know how to do the same on my phone. (Could Termux help?)
Let me know of any extra info you need about my hardware.

[laptop-graphics-info.txt](https://github.com/tensorflow/tfjs/files/3561294/laptop-graphics-info.txt)
[tfConv2D-outputs.txt](https://github.com/tensorflow/tfjs/files/3561295/tfConv2D-outputs.txt)

**Comment by tafsiri** [comment] 2019-08-30 20:42
@manueldois Screenshotting the output you get on both machines from https://js.tensorflow.org/debug/ and pasting it here might be helpful.

**Comment by rthadur** [comment] 2019-08-30 20:55
> @rthadur any chance you could try in brave? It shouldn't be different but would be good to know.

@tafsiri i will try on my personal mac and will let you know.

**Comment by manueldois** [comment] 2019-08-30 23:09
On mobile.
On the laptop later

![Screenshot_20190831-000748_Brave](https://user-images.githubusercontent.com/37387843/64055292-7ffdbb00-cb83-11e9-9e5e-bab313e0a2de.jpg)

**Comment by dsmilkov** [comment] 2019-09-06 18:44
@manueldois Can you add `tf.ENV.set('WEBGL_PACK', false);` add the beginning of your js program (before you run any TF.js code) and see if that resolves the issue?

`WEBGL_PACK` is an optimization, but I'm curious if that causes some problems on your machine.

**Comment by manueldois** [comment] 2019-09-09 19:43
It worked! Thank you!

Adding `tf.ENV.set('WEBGL_PACK', false)` solved the issue.
https://codesandbox.io/s/tensorflow-conv2dtest-3d9ni

How does having this disable impact performance tough?

**Comment by dsmilkov** [comment] 2019-09-18 20:26
@annxingyuan This seems related to packing since setting WEBGL_PACK to false solved the issue. Though it will probably be tricky to reproduce because it requires an Intel GPU. When you get a chance, would be worth trying to reproduce on our Windows laptop.

**Comment by annxingyuan** [comment] 2019-09-25 14:43
@dsmilkov Unfortunately I can't reproduce this issue on our Windows laptop.

@manueldois Thanks for bearing with us. Would you mind trying a few more things:

- Does `WORLD_SIZE` of 400 work?
- What if instead of changing `WEBGL_PACK` to false, you only changed `WEBGL_CONV_IM2COL` to false?
- Could you upload the full printout for the `N_NEIGHBORS` tensor given `WORLD_SIZE` 300?

Thank you!

**Comment by manueldois** [comment] 2019-09-26 22:49
`WORLD_SIZE` 400 works,
`WEBGL_CONV_IM2COL` to false solves the issue,
[Conv2D test.zip](https://github.com/tensorflow/tfjs/files/3660162/Conv2D.test.zip) with many printouts inside of failed tests. (perhaps over-engineered.......)

I noticed that when the test fails it's execution time is much faster than when the test is successful.

**Comment by rthadur** [comment] 2020-03-06 18:15
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rthadur** 2020-03-06 18:15 UTC
Labels: comp:core, type:support
