### ISSUE TITLE
yarn test fails on tfjs-backend-webgl on windows

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#5660] opened 2021-09-24 07:30 UTC
Steps to reproduce:
1. Get latest tfjs resource code.
2. cd tfjs-backend-webgl
3.  yarn && yarn test
Below error will be reported
```
iBazel [3:14PM]: Running :tfjs-backend-webgl2_test
Loading:
Loading: 0 packages loaded
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (0 packages loaded, 0 targets configured)
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (1 packages loaded, 35 targets configured)
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (1 packages loaded, 35 targets configured)
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (1 packages loaded, 35 targets configured)
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (1 packages loaded, 35 targets configured)
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (1 packages loaded, 35 targets configured)
INFO: Repository python3_interpreter instantiated at:
  D:/workspace/jiajia/tfjs/tfjs/WORKSPACE:231:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/jqin7/_bazel_jqin7/6lxz3o43/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
Analyzing: target //tfjs-backend-webgl:tfjs-backend-webgl2_test (1 packages loaded, 35 targets configured)
INFO: Repository 'python3_interpreter' used the following cache hits instead of downloading the corresponding file.
 * Hash 'fb1a1114ebfe9e97199603c6083e20b236a0e007a2c51f29283ffb50c1420fb2' for https://www.python.org/ftp/python/3.8.11/
Python-3.8.11.tar.xz
If the definition of 'python3_interpreter' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'python3_interpreter':
   Traceback (most recent call last):
        File "C:/users/jqin7/_bazel_jqin7/6lxz3o43/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, colum
n 10, in _http_archive_impl
                patch(ctx)
        File "C:/users/jqin7/_bazel_jqin7/6lxz3o43/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, colu
mn 21, in patch
                fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command
if [[ "$OSTYPE" == "darwin"* ]]; then
    ./configure --prefix=$(pwd)/bazel_install_py3 --with-openssl=$(brew --prefix openssl)
else
    ./configure --prefix=$(pwd)/bazel_install_py3
fi
:
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking for python3.8... no
checking for python3... no
checking for python... python
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "mingw64_nt-10.0-177633"
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/users/jqin7/_bazel_jqin7/6lxz3o43/external/python3_interpreter':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/jqin7/_bazel_jqin7/6lxz3o43/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, colum
n 10, in _http_archive_impl
                patch(ctx)
        File "C:/users/jqin7/_bazel_jqin7/6lxz3o43/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, colu
mn 21, in patch
                fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command
if [[ "$OSTYPE" == "darwin"* ]]; then
    ./configure --prefix=$(pwd)/bazel_install_py3 --with-openssl=$(brew --prefix openssl)
else
    ./configure --prefix=$(pwd)/bazel_install_py3
fi
:
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking for python3.8... no
checking for python3... no
checking for python... python
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "mingw64_nt-10.0-177633"
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/users/jqin7/_bazel_jqin7/6lxz3o43/external/python3_interpreter':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: D:/workspace/jiajia/tfjs/tfjs/tfjs-converter/python/BUILD:6:11: //tfjs-converter/python:python3_runtime depends o
n @python3_interpreter//:files in repository @python3_interpreter which failed to fetch. no such package '@python3_inter
preter//': Error applying patch command
if [[ "$OSTYPE" == "darwin"* ]]; then
    ./configure --prefix=$(pwd)/bazel_install_py3 --with-openssl=$(brew --prefix openssl)
else
    ./configure --prefix=$(pwd)/bazel_install_py3
fi
:
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking for python3.8... no
checking for python3... no
checking for python... python
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "mingw64_nt-10.0-177633"
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/users/jqin7/_bazel_jqin7/6lxz3o43/external/python3_interpreter':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: D:/workspace/jiajia/tfjs/tfjs/tfjs-converter/python/BUILD:6:11: //tfjs-converter/python:python3_runtime depends o
n @python3_interpreter//:python3_bin in repository @python3_interpreter which failed to fetch. no such package '@python3
_interpreter//': Error applying patch command
if [[ "$OSTYPE" == "darwin"* ]]; then
    ./configure --prefix=$(pwd)/bazel_install_py3 --with-openssl=$(brew --prefix openssl)
else
    ./configure --prefix=$(pwd)/bazel_install_py3
fi
:
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-pc-mingw64
checking for python3.8... no
checking for python3... no
checking for python... python
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "mingw64_nt-10.0-177633"
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/c/users/jqin7/_bazel_jqin7/6lxz3o43/external/python3_interpreter':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: Analysis of target '//tfjs-backend-webgl:tfjs-backend-webgl2_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 40.135s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 35 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 35 targets configured)
iBazel [3:15PM]: Error running Bazel exit status 1
error Command failed with exit code 4.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by qjia7** [comment] 2021-09-24 07:30
cc @mattsoulanille

**Comment by mattsoulanille** [comment] 2021-09-24 22:13
Thanks for reporting this @qjia7. This looks like it's caused by the recent change that builds tfjs-converter with Bazel. That change builds specific versions of python 2 and 3 from source for consistency across machines. We were hoping this would make setting up converter more convenient, but it seems like in this case, it's getting in the way of testing other packages. I'll bring this up with the team.

I expect that if you install the required libraries for compiling python2 and 3 from source,  the webgl tests will run. We've [documented this on the `tfjs-converter` readme](https://github.com/tensorflow/tfjs/blob/master/WORKSPACE#L287-L297), but perhaps it should be moved up to the main readme since it affects other packages as well. [Here's a  link to Python's docs on how to build Python from source on Windows](https://devguide.python.org/setup/#windows).

**Comment by gyagp** [comment] 2021-09-26 06:48
Instead of building python from source, can we simply provide related binaries for consistency? In Chromium development, depot_tools (https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html) is used for this sake. To maintain the build on various platforms are much harder than maintaining the binaries. 
For this case, if I run "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" to set the compiler path, I may advance a bit, then I will encounter the below error (related to pthread support):
checking for pthread_create in -lcma... no
configure: error: could not find pthreads on your system
ERROR: Analysis of target '//tfjs-backend-webgl:tfjs-backend-webgl2_test' failed; build aborted: Analysis failed.

Windows is a very important platform for us to develop and test. Will you consider adding a Windows bot to catch such kind of regression?

**Comment by mattsoulanille** [comment] 2021-10-12 18:25
I'm able to reproduce this error, and I'm working on fixing it. Thanks for reporting it, @gyagp!

For CI, we don't actually use Compute Engine. Instead, we use [Cloud Build](https://cloud.google.com/build), which, as far as I can tell, only supports Linux containers (I'll try Windows anyway, but I don't expect it to work). There are other containers for building Windows-specific things on GCP, like the [dotnet builder](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/dotnet), but they are based on Linux. We might be able to use something like [remote-builder](https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/remote-builder) to launch a Windows VM from a Cloud Build docker container, but I'll have to investigate more.

**Comment by haoyunfeix** [comment] 2021-11-08 06:09
Verified and it also works for WebGPU backend testing using Bazel tool.
Another question: Will it support `--grep` in command line like the describe in https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md#testing ?

**Comment by qjia7** [comment] 2021-11-12 06:58
@mattsoulanille I tried the new way to build on wsl. It works for me. Thanks for you great efforts on this. I have the save question as Yunfei. How should we use `--grep`? It seems that `yarn test --grep='packed'` not work for me.

And another issue I met is it always reports that `Google Chrome can't read and write to its data directory /tmp/karma-16220143`. Failed to create data directory. Currently, I just click ok and ignore it.

**Comment by rthadur** [comment] 2022-09-23 23:20
Related PR has been merged , closing this issue. Thank you

**Closed by rthadur** 2022-09-23 23:20 UTC
Labels: type:build/install, bazel
