### ISSUE TITLE
Local development should auto-update libtensorflow

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#608] opened 2018-08-14 18:19 UTC
Local development of the Node.js binding package results in symlink'd libtensorflow.*. This works great for local development since the engineer doesn't have to download libtensorflow.* on every `yarn` command. However, it is easy to get out-of-sync with what the supported version needs.

This task should make libtensorflow cleanup easier for developer workflows (npm installs use a move command and ensure that the latest libtensorflow.* is used).

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:45
Hi, @nkreeger 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:45 UTC
Labels: P2, comp:node.js, type:others, stat:awaiting response
