### ISSUE TITLE
Chaining is broken with round

### ISSUE THREAD

**Issue by nbardy** [tensorflow/tfjs#307] opened 2018-05-18 01:47 UTC
Issue shows up locally and with example code in the docs

https://js.tensorflow.org/api/0.10.0/#round

NOTE:
`tf.round` works fine.

**Comment by caisq** [comment] 2018-05-18 03:15
Confirming I can reproduce this bug on tfjs website at the URL provided by @nbardy

**Comment by ManrajGrover** [comment] 2018-05-18 05:04
Cannot reproduce this error from HEAD. This was fixed in https://github.com/tensorflow/tfjs-core/pull/994

**Comment by caisq** [comment] 2018-05-18 13:17
Thanks, @ManrajGrover ! I'll close this issue for now.

**Closed by caisq** 2018-05-18 13:17 UTC
Labels: bug, core
