### ISSUE TITLE
Implement tf.layers.dot() for 4D (Dot Merge Layer) 

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#19] opened 2018-03-27 17:40 UTC
The PyKeras code is at: https://github.com/keras-team/keras/blob/master/keras/layers/merge.py#L408

**Comment by HassanAzzam** [comment] 2018-04-14 17:13
When will it be available?

**Comment by caisq** [comment] 2018-04-14 18:32
Thanks, @HassanAzzam 

Just for my curiosity: what model are you planning to write or port that requires Dot?

**Comment by HassanAzzam** [comment] 2018-04-14 20:54
Currently, trying to practice it on a skip-gram model.

**Comment by caisq** [comment] 2018-04-15 01:33
Thanks, @HassanAzzam . We'll prioritize adding Dot.

**Comment by HassanAzzam** [comment] 2018-04-15 06:51
Thanks alot, @caisq😃

**Comment by euler16** [comment] 2018-10-13 03:03
is anyone working on this issue? if not then I would like to try working on it. In that case @caisq  could you give me some pointers to start.

**Comment by caisq** [comment] 2018-10-13 03:06
@euler16 The just released v0.13.2 should have tf.layers.dot included. Please give it a try. Note that it currently doesn't support 4D or higher dimensions as inputs.

**Comment by caisq** [comment] 2018-10-13 03:09
I'm leaving this issue open because the support for 4D+ cases is not implemented yet.

**Comment by gaikwadrahul8** [comment] 2023-09-12 10:14
Hi, @caisq 

Apologize for the delayed response and I was trying to use tensors of 4D or higher rank and I was getting this error message `Dot layer does not support tensors of 4D or higher rank yet.` so it seems like we haven't implemented this feature request yet. Thank you!

![image](https://github.com/tensorflow/tfjs/assets/115997457/693a5b7f-f2d2-41a9-b759-3786e6e9a1d6)

**Comment by gaikwadrahul8** [comment] 2023-10-11 14:31
Hi, @caisq 

Thank you for opening this issue for tracking purposes. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.11.0) with the latest compatible hardware configuration which could potentially resolve the issue. We can keep the issue open if it is still relevant. Please confirm if we need to keep the issue open.

Thank you for your support and cooperation.

**Comment by gaikwadrahul8** [comment] 2023-10-18 19:48
Hi, @caisq 

We have not received any confirmation from you, so we are closing this issue now. If the issue is still relevant, please let us know, either we'll re-open this issue or please feel free to create new issue after trying with latest version of Tensorflow.js. Thank you!

**Closed by gaikwadrahul8** 2023-10-18 19:48 UTC
Labels: type:feature, comp:layers, P3, stat:awaiting response
